// Generated by scripts/import-japanese-data.mjs — do not edit by hand.
// Source: https://kanjiapi.dev (JLPT N5 kanji set)
import type { KanjiChar } from './types'

export const KANJI: KanjiChar[] = [
  {
    "char": "一",
    "meanings": [
      "one",
      "one radical (no.1)"
    ],
    "onYomi": [
      "イチ",
      "イツ"
    ],
    "kunYomi": [
      "ひと-",
      "ひと.つ"
    ],
    "strokeCount": 1
  },
  {
    "char": "七",
    "meanings": [
      "seven"
    ],
    "onYomi": [
      "シチ"
    ],
    "kunYomi": [
      "なな",
      "なな.つ",
      "なの"
    ],
    "strokeCount": 2
  },
  {
    "char": "九",
    "meanings": [
      "nine"
    ],
    "onYomi": [
      "キュウ",
      "ク"
    ],
    "kunYomi": [
      "ここの",
      "ここの.つ"
    ],
    "strokeCount": 2
  },
  {
    "char": "二",
    "meanings": [
      "two",
      "two radical (no. 7)"
    ],
    "onYomi": [
      "ニ",
      "ジ"
    ],
    "kunYomi": [
      "ふた",
      "ふた.つ",
      "ふたたび"
    ],
    "strokeCount": 2
  },
  {
    "char": "人",
    "meanings": [
      "person"
    ],
    "onYomi": [
      "ジン",
      "ニン"
    ],
    "kunYomi": [
      "ひと",
      "-り",
      "-と"
    ],
    "strokeCount": 2
  },
  {
    "char": "入",
    "meanings": [
      "enter",
      "insert"
    ],
    "onYomi": [
      "ニュウ",
      "ジュ"
    ],
    "kunYomi": [
      "い.る",
      "-い.る",
      "-い.り",
      "い.れる",
      "-い.れ",
      "はい.る"
    ],
    "strokeCount": 2
  },
  {
    "char": "八",
    "meanings": [
      "eight",
      "eight radical (no. 12)"
    ],
    "onYomi": [
      "ハチ",
      "ハツ"
    ],
    "kunYomi": [
      "や",
      "や.つ",
      "やっ.つ",
      "よう"
    ],
    "strokeCount": 2
  },
  {
    "char": "十",
    "meanings": [
      "ten"
    ],
    "onYomi": [
      "ジュウ",
      "ジッ",
      "ジュッ"
    ],
    "kunYomi": [
      "とお",
      "と",
      "そ"
    ],
    "strokeCount": 2
  },
  {
    "char": "万",
    "meanings": [
      "ten thousand",
      "10,000"
    ],
    "onYomi": [
      "マン",
      "バン"
    ],
    "kunYomi": [
      "よろず"
    ],
    "strokeCount": 3
  },
  {
    "char": "三",
    "meanings": [
      "three"
    ],
    "onYomi": [
      "サン",
      "ゾウ"
    ],
    "kunYomi": [
      "み",
      "み.つ",
      "みっ.つ"
    ],
    "strokeCount": 3
  },
  {
    "char": "上",
    "meanings": [
      "above",
      "up"
    ],
    "onYomi": [
      "ジョウ",
      "ショウ",
      "シャン"
    ],
    "kunYomi": [
      "うえ",
      "-うえ",
      "うわ-",
      "かみ",
      "あ.げる",
      "-あ.げる",
      "あ.がる",
      "-あ.がる",
      "あ.がり",
      "-あ.がり",
      "のぼ.る",
      "のぼ.り",
      "のぼ.せる",
      "のぼ.す",
      "たてまつ.る"
    ],
    "strokeCount": 3
  },
  {
    "char": "下",
    "meanings": [
      "below",
      "down",
      "descend",
      "give",
      "low",
      "inferior"
    ],
    "onYomi": [
      "カ",
      "ゲ"
    ],
    "kunYomi": [
      "した",
      "しも",
      "もと",
      "さ.げる",
      "さ.がる",
      "くだ.る",
      "くだ.り",
      "くだ.す",
      "-くだ.す",
      "くだ.さる",
      "お.ろす",
      "お.りる"
    ],
    "strokeCount": 3
  },
  {
    "char": "千",
    "meanings": [
      "thousand"
    ],
    "onYomi": [
      "セン"
    ],
    "kunYomi": [
      "ち"
    ],
    "strokeCount": 3
  },
  {
    "char": "土",
    "meanings": [
      "soil",
      "earth",
      "ground",
      "Turkey"
    ],
    "onYomi": [
      "ド",
      "ト"
    ],
    "kunYomi": [
      "つち"
    ],
    "strokeCount": 3
  },
  {
    "char": "大",
    "meanings": [
      "large",
      "big"
    ],
    "onYomi": [
      "ダイ",
      "タイ"
    ],
    "kunYomi": [
      "おお-",
      "おお.きい",
      "-おお.いに"
    ],
    "strokeCount": 3
  },
  {
    "char": "女",
    "meanings": [
      "woman",
      "female"
    ],
    "onYomi": [
      "ジョ",
      "ニョ",
      "ニョウ"
    ],
    "kunYomi": [
      "おんな",
      "め"
    ],
    "strokeCount": 3
  },
  {
    "char": "子",
    "meanings": [
      "child",
      "sign of the rat",
      "11PM-1AM",
      "first sign of Chinese zodiac"
    ],
    "onYomi": [
      "シ",
      "ス",
      "ツ"
    ],
    "kunYomi": [
      "こ",
      "-こ",
      "ね"
    ],
    "strokeCount": 3
  },
  {
    "char": "小",
    "meanings": [
      "little",
      "small"
    ],
    "onYomi": [
      "ショウ"
    ],
    "kunYomi": [
      "ちい.さい",
      "こ-",
      "お-",
      "さ-"
    ],
    "strokeCount": 3
  },
  {
    "char": "山",
    "meanings": [
      "mountain"
    ],
    "onYomi": [
      "サン",
      "セン"
    ],
    "kunYomi": [
      "やま"
    ],
    "strokeCount": 3
  },
  {
    "char": "川",
    "meanings": [
      "stream",
      "river",
      "river or three-stroke river radical (no. 47)"
    ],
    "onYomi": [
      "セン"
    ],
    "kunYomi": [
      "かわ"
    ],
    "strokeCount": 3
  },
  {
    "char": "中",
    "meanings": [
      "in",
      "inside",
      "middle",
      "mean",
      "center"
    ],
    "onYomi": [
      "チュウ"
    ],
    "kunYomi": [
      "なか",
      "うち",
      "あた.る"
    ],
    "strokeCount": 4
  },
  {
    "char": "五",
    "meanings": [
      "five"
    ],
    "onYomi": [
      "ゴ"
    ],
    "kunYomi": [
      "いつ",
      "いつ.つ"
    ],
    "strokeCount": 4
  },
  {
    "char": "今",
    "meanings": [
      "now"
    ],
    "onYomi": [
      "コン",
      "キン"
    ],
    "kunYomi": [
      "いま"
    ],
    "strokeCount": 4
  },
  {
    "char": "六",
    "meanings": [
      "six"
    ],
    "onYomi": [
      "ロク",
      "リク"
    ],
    "kunYomi": [
      "む",
      "む.つ",
      "むっ.つ",
      "むい"
    ],
    "strokeCount": 4
  },
  {
    "char": "円",
    "meanings": [
      "circle",
      "yen",
      "round"
    ],
    "onYomi": [
      "エン"
    ],
    "kunYomi": [
      "まる.い",
      "まる",
      "まど",
      "まど.か",
      "まろ.やか"
    ],
    "strokeCount": 4
  },
  {
    "char": "午",
    "meanings": [
      "noon",
      "sign of the horse",
      "11AM-1PM",
      "seventh sign of Chinese zodiac"
    ],
    "onYomi": [
      "ゴ"
    ],
    "kunYomi": [
      "うま"
    ],
    "strokeCount": 4
  },
  {
    "char": "友",
    "meanings": [
      "friend"
    ],
    "onYomi": [
      "ユウ"
    ],
    "kunYomi": [
      "とも"
    ],
    "strokeCount": 4
  },
  {
    "char": "天",
    "meanings": [
      "heavens",
      "sky",
      "imperial"
    ],
    "onYomi": [
      "テン"
    ],
    "kunYomi": [
      "あまつ",
      "あめ",
      "あま-"
    ],
    "strokeCount": 4
  },
  {
    "char": "日",
    "meanings": [
      "day",
      "sun",
      "Japan",
      "counter for days"
    ],
    "onYomi": [
      "ニチ",
      "ジツ"
    ],
    "kunYomi": [
      "ひ",
      "-び",
      "-か"
    ],
    "strokeCount": 4
  },
  {
    "char": "月",
    "meanings": [
      "month",
      "moon"
    ],
    "onYomi": [
      "ゲツ",
      "ガツ"
    ],
    "kunYomi": [
      "つき"
    ],
    "strokeCount": 4
  },
  {
    "char": "木",
    "meanings": [
      "tree",
      "wood"
    ],
    "onYomi": [
      "ボク",
      "モク"
    ],
    "kunYomi": [
      "き",
      "こ-"
    ],
    "strokeCount": 4
  },
  {
    "char": "水",
    "meanings": [
      "water"
    ],
    "onYomi": [
      "スイ"
    ],
    "kunYomi": [
      "みず",
      "みず-"
    ],
    "strokeCount": 4
  },
  {
    "char": "火",
    "meanings": [
      "fire"
    ],
    "onYomi": [
      "カ"
    ],
    "kunYomi": [
      "ひ",
      "-び",
      "ほ-"
    ],
    "strokeCount": 4
  },
  {
    "char": "父",
    "meanings": [
      "father"
    ],
    "onYomi": [
      "フ"
    ],
    "kunYomi": [
      "ちち"
    ],
    "strokeCount": 4
  },
  {
    "char": "出",
    "meanings": [
      "exit",
      "leave",
      "go out",
      "come out",
      "put out",
      "protrude"
    ],
    "onYomi": [
      "シュツ",
      "スイ"
    ],
    "kunYomi": [
      "で.る",
      "-で",
      "だ.す",
      "-だ.す",
      "い.でる",
      "い.だす"
    ],
    "strokeCount": 5
  },
  {
    "char": "北",
    "meanings": [
      "north"
    ],
    "onYomi": [
      "ホク"
    ],
    "kunYomi": [
      "きた"
    ],
    "strokeCount": 5
  },
  {
    "char": "半",
    "meanings": [
      "half",
      "middle",
      "odd number",
      "semi-",
      "part-"
    ],
    "onYomi": [
      "ハン"
    ],
    "kunYomi": [
      "なか.ば"
    ],
    "strokeCount": 5
  },
  {
    "char": "右",
    "meanings": [
      "right"
    ],
    "onYomi": [
      "ウ",
      "ユウ"
    ],
    "kunYomi": [
      "みぎ"
    ],
    "strokeCount": 5
  },
  {
    "char": "四",
    "meanings": [
      "four"
    ],
    "onYomi": [
      "シ"
    ],
    "kunYomi": [
      "よ",
      "よ.つ",
      "よっ.つ",
      "よん"
    ],
    "strokeCount": 5
  },
  {
    "char": "外",
    "meanings": [
      "outside"
    ],
    "onYomi": [
      "ガイ",
      "ゲ"
    ],
    "kunYomi": [
      "そと",
      "ほか",
      "はず.す",
      "はず.れる",
      "と-"
    ],
    "strokeCount": 5
  },
  {
    "char": "左",
    "meanings": [
      "left"
    ],
    "onYomi": [
      "サ",
      "シャ"
    ],
    "kunYomi": [
      "ひだり"
    ],
    "strokeCount": 5
  },
  {
    "char": "本",
    "meanings": [
      "book",
      "present",
      "main",
      "origin",
      "true",
      "real",
      "counter for long cylindrical things"
    ],
    "onYomi": [
      "ホン"
    ],
    "kunYomi": [
      "もと"
    ],
    "strokeCount": 5
  },
  {
    "char": "母",
    "meanings": [
      "mother"
    ],
    "onYomi": [
      "ボ"
    ],
    "kunYomi": [
      "はは",
      "も"
    ],
    "strokeCount": 5
  },
  {
    "char": "生",
    "meanings": [
      "life",
      "genuine",
      "birth"
    ],
    "onYomi": [
      "セイ",
      "ショウ"
    ],
    "kunYomi": [
      "い.きる",
      "い.かす",
      "い.ける",
      "う.まれる",
      "うま.れる",
      "う.まれ",
      "うまれ",
      "う.む",
      "お.う",
      "は.える",
      "は.やす",
      "き",
      "なま",
      "なま-",
      "な.る",
      "な.す",
      "む.す",
      "-う"
    ],
    "strokeCount": 5
  },
  {
    "char": "白",
    "meanings": [
      "white"
    ],
    "onYomi": [
      "ハク",
      "ビャク"
    ],
    "kunYomi": [
      "しろ",
      "しら-",
      "しろ.い"
    ],
    "strokeCount": 5
  },
  {
    "char": "休",
    "meanings": [
      "rest",
      "day off",
      "retire",
      "sleep"
    ],
    "onYomi": [
      "キュウ"
    ],
    "kunYomi": [
      "やす.む",
      "やす.まる",
      "やす.める"
    ],
    "strokeCount": 6
  },
  {
    "char": "先",
    "meanings": [
      "before",
      "ahead",
      "previous",
      "future",
      "precedence"
    ],
    "onYomi": [
      "セン"
    ],
    "kunYomi": [
      "さき",
      "ま.ず"
    ],
    "strokeCount": 6
  },
  {
    "char": "名",
    "meanings": [
      "name",
      "noted",
      "distinguished",
      "reputation"
    ],
    "onYomi": [
      "メイ",
      "ミョウ"
    ],
    "kunYomi": [
      "な",
      "-な"
    ],
    "strokeCount": 6
  },
  {
    "char": "年",
    "meanings": [
      "year",
      "counter for years"
    ],
    "onYomi": [
      "ネン"
    ],
    "kunYomi": [
      "とし"
    ],
    "strokeCount": 6
  },
  {
    "char": "毎",
    "meanings": [
      "every"
    ],
    "onYomi": [
      "マイ"
    ],
    "kunYomi": [
      "ごと",
      "-ごと.に"
    ],
    "strokeCount": 6
  },
  {
    "char": "気",
    "meanings": [
      "spirit",
      "mind",
      "air",
      "atmosphere",
      "mood"
    ],
    "onYomi": [
      "キ",
      "ケ"
    ],
    "kunYomi": [
      "いき",
      "き"
    ],
    "strokeCount": 6
  },
  {
    "char": "百",
    "meanings": [
      "hundred"
    ],
    "onYomi": [
      "ヒャク",
      "ビャク"
    ],
    "kunYomi": [
      "もも"
    ],
    "strokeCount": 6
  },
  {
    "char": "行",
    "meanings": [
      "going",
      "journey",
      "carry out",
      "conduct",
      "act",
      "line",
      "row",
      "bank"
    ],
    "onYomi": [
      "コウ",
      "ギョウ",
      "アン"
    ],
    "kunYomi": [
      "い.く",
      "ゆ.く",
      "-ゆ.き",
      "-ゆき",
      "-い.き",
      "-いき",
      "おこな.う",
      "おこ.なう"
    ],
    "strokeCount": 6
  },
  {
    "char": "西",
    "meanings": [
      "west",
      "Spain"
    ],
    "onYomi": [
      "セイ",
      "サイ",
      "ス"
    ],
    "kunYomi": [
      "にし"
    ],
    "strokeCount": 6
  },
  {
    "char": "何",
    "meanings": [
      "what"
    ],
    "onYomi": [
      "カ"
    ],
    "kunYomi": [
      "なに",
      "なん",
      "なに-",
      "なん-"
    ],
    "strokeCount": 7
  },
  {
    "char": "来",
    "meanings": [
      "come",
      "due",
      "next",
      "cause",
      "become"
    ],
    "onYomi": [
      "ライ",
      "タイ"
    ],
    "kunYomi": [
      "く.る",
      "きた.る",
      "きた.す",
      "き.たす",
      "き.たる",
      "き",
      "こ"
    ],
    "strokeCount": 7
  },
  {
    "char": "男",
    "meanings": [
      "male"
    ],
    "onYomi": [
      "ダン",
      "ナン"
    ],
    "kunYomi": [
      "おとこ",
      "お"
    ],
    "strokeCount": 7
  },
  {
    "char": "見",
    "meanings": [
      "see",
      "hopes",
      "chances",
      "idea",
      "opinion",
      "look at",
      "visible"
    ],
    "onYomi": [
      "ケン"
    ],
    "kunYomi": [
      "み.る",
      "み.える",
      "み.せる"
    ],
    "strokeCount": 7
  },
  {
    "char": "車",
    "meanings": [
      "car"
    ],
    "onYomi": [
      "シャ"
    ],
    "kunYomi": [
      "くるま"
    ],
    "strokeCount": 7
  },
  {
    "char": "国",
    "meanings": [
      "country"
    ],
    "onYomi": [
      "コク"
    ],
    "kunYomi": [
      "くに"
    ],
    "strokeCount": 8
  },
  {
    "char": "学",
    "meanings": [
      "study",
      "learning",
      "science"
    ],
    "onYomi": [
      "ガク"
    ],
    "kunYomi": [
      "まな.ぶ"
    ],
    "strokeCount": 8
  },
  {
    "char": "東",
    "meanings": [
      "east"
    ],
    "onYomi": [
      "トウ"
    ],
    "kunYomi": [
      "ひがし"
    ],
    "strokeCount": 8
  },
  {
    "char": "金",
    "meanings": [
      "gold"
    ],
    "onYomi": [
      "キン",
      "コン",
      "ゴン"
    ],
    "kunYomi": [
      "かね",
      "かな-",
      "-がね"
    ],
    "strokeCount": 8
  },
  {
    "char": "長",
    "meanings": [
      "long",
      "leader",
      "superior",
      "senior"
    ],
    "onYomi": [
      "チョウ"
    ],
    "kunYomi": [
      "なが.い",
      "おさ"
    ],
    "strokeCount": 8
  },
  {
    "char": "雨",
    "meanings": [
      "rain"
    ],
    "onYomi": [
      "ウ"
    ],
    "kunYomi": [
      "あめ",
      "あま-",
      "-さめ"
    ],
    "strokeCount": 8
  },
  {
    "char": "前",
    "meanings": [
      "in front",
      "before"
    ],
    "onYomi": [
      "ゼン"
    ],
    "kunYomi": [
      "まえ",
      "-まえ"
    ],
    "strokeCount": 9
  },
  {
    "char": "南",
    "meanings": [
      "south"
    ],
    "onYomi": [
      "ナン",
      "ナ"
    ],
    "kunYomi": [
      "みなみ"
    ],
    "strokeCount": 9
  },
  {
    "char": "後",
    "meanings": [
      "behind",
      "back",
      "later"
    ],
    "onYomi": [
      "ゴ",
      "コウ"
    ],
    "kunYomi": [
      "のち",
      "うし.ろ",
      "うしろ",
      "あと",
      "おく.れる"
    ],
    "strokeCount": 9
  },
  {
    "char": "食",
    "meanings": [
      "eat",
      "food"
    ],
    "onYomi": [
      "ショク",
      "ジキ"
    ],
    "kunYomi": [
      "く.う",
      "く.らう",
      "た.べる",
      "は.む"
    ],
    "strokeCount": 9
  },
  {
    "char": "時",
    "meanings": [
      "time",
      "hour"
    ],
    "onYomi": [
      "ジ"
    ],
    "kunYomi": [
      "とき",
      "-どき"
    ],
    "strokeCount": 10
  },
  {
    "char": "書",
    "meanings": [
      "write"
    ],
    "onYomi": [
      "ショ"
    ],
    "kunYomi": [
      "か.く",
      "-が.き",
      "-がき"
    ],
    "strokeCount": 10
  },
  {
    "char": "校",
    "meanings": [
      "exam",
      "school",
      "printing",
      "proof",
      "correction"
    ],
    "onYomi": [
      "コウ",
      "キョウ"
    ],
    "kunYomi": [],
    "strokeCount": 10
  },
  {
    "char": "高",
    "meanings": [
      "tall",
      "high",
      "expensive"
    ],
    "onYomi": [
      "コウ"
    ],
    "kunYomi": [
      "たか.い",
      "たか",
      "-だか",
      "たか.まる",
      "たか.める"
    ],
    "strokeCount": 10
  },
  {
    "char": "間",
    "meanings": [
      "interval",
      "space"
    ],
    "onYomi": [
      "カン",
      "ケン"
    ],
    "kunYomi": [
      "あいだ",
      "ま",
      "あい"
    ],
    "strokeCount": 12
  },
  {
    "char": "話",
    "meanings": [
      "tale",
      "talk"
    ],
    "onYomi": [
      "ワ"
    ],
    "kunYomi": [
      "はな.す",
      "はなし"
    ],
    "strokeCount": 13
  },
  {
    "char": "電",
    "meanings": [
      "electricity"
    ],
    "onYomi": [
      "デン"
    ],
    "kunYomi": [],
    "strokeCount": 13
  },
  {
    "char": "聞",
    "meanings": [
      "hear",
      "ask",
      "listen"
    ],
    "onYomi": [
      "ブン",
      "モン"
    ],
    "kunYomi": [
      "き.く",
      "き.こえる"
    ],
    "strokeCount": 14
  },
  {
    "char": "語",
    "meanings": [
      "word",
      "speech",
      "language"
    ],
    "onYomi": [
      "ゴ"
    ],
    "kunYomi": [
      "かた.る",
      "かた.らう"
    ],
    "strokeCount": 14
  },
  {
    "char": "読",
    "meanings": [
      "read"
    ],
    "onYomi": [
      "ドク",
      "トク",
      "トウ"
    ],
    "kunYomi": [
      "よ.む",
      "-よ.み"
    ],
    "strokeCount": 14
  }
]
