// Generated by scripts/import-japanese-data.mjs — do not edit by hand.
// Source: https://github.com/elzup/jlpt-word-list (MIT)
import type { JapaneseWord } from '../types'

export const N4: JapaneseWord[] = [
  {
    "id": "n4-0001",
    "jp": "踏む",
    "reading": "ふむ",
    "romaji": "fumu",
    "meaning": "to step on, to tread on"
  },
  {
    "id": "n4-0002",
    "jp": "～区",
    "reading": "～く",
    "romaji": "～ku",
    "meaning": "~ district, ~ ward, ~ borough"
  },
  {
    "id": "n4-0003",
    "jp": "すっと",
    "reading": "すっと",
    "romaji": "sutto",
    "meaning": "straight, quickly"
  },
  {
    "id": "n4-0004",
    "jp": "盗む",
    "reading": "ぬすむ",
    "romaji": "nusumu",
    "meaning": "to steal; to rob"
  },
  {
    "id": "n4-0005",
    "jp": "大抵",
    "reading": "たいてい",
    "romaji": "taitei",
    "meaning": "generally, usually"
  },
  {
    "id": "n4-0006",
    "jp": "とうとう",
    "reading": "とうとう",
    "romaji": "toutou",
    "meaning": "finally, at last"
  },
  {
    "id": "n4-0007",
    "jp": "ガソリン",
    "reading": "ガソリン",
    "romaji": "ガソリン",
    "meaning": "gasoline, petrol"
  },
  {
    "id": "n4-0008",
    "jp": "鳴る",
    "reading": "なる",
    "romaji": "naru",
    "meaning": "to sound, to ring (v.i.)"
  },
  {
    "id": "n4-0009",
    "jp": "しっかり",
    "reading": "しっかり",
    "romaji": "shikkari",
    "meaning": "firmly, steady"
  },
  {
    "id": "n4-0010",
    "jp": "生きる",
    "reading": "いきる",
    "romaji": "ikiru",
    "meaning": "to live"
  },
  {
    "id": "n4-0011",
    "jp": "苦い",
    "reading": "にがい",
    "romaji": "nigai",
    "meaning": "bitter"
  },
  {
    "id": "n4-0012",
    "jp": "沸く",
    "reading": "わく",
    "romaji": "waku",
    "meaning": "to boil, to grow hot"
  },
  {
    "id": "n4-0013",
    "jp": "意見",
    "reading": "いけん",
    "romaji": "iken",
    "meaning": "opinion, view, idea"
  },
  {
    "id": "n4-0014",
    "jp": "やはり; やっぱり",
    "reading": "やはり; やっぱり",
    "romaji": "yahari; yappari",
    "meaning": "as I thought, absolutely"
  },
  {
    "id": "n4-0015",
    "jp": "漫画",
    "reading": "まんが",
    "romaji": "manga",
    "meaning": "comic (book), cartoon"
  },
  {
    "id": "n4-0016",
    "jp": "ステレオ",
    "reading": "ステレオ",
    "romaji": "ステレオ",
    "meaning": "stereo"
  },
  {
    "id": "n4-0017",
    "jp": "医学",
    "reading": "いがく",
    "romaji": "igaku",
    "meaning": "medical science"
  },
  {
    "id": "n4-0018",
    "jp": "テキスト",
    "reading": "テキスト",
    "romaji": "テキスト",
    "meaning": "text; text book"
  },
  {
    "id": "n4-0019",
    "jp": "～月",
    "reading": "～つき",
    "romaji": "～tsuki",
    "meaning": "month"
  },
  {
    "id": "n4-0020",
    "jp": "折る",
    "reading": "おる",
    "romaji": "oru",
    "meaning": "to snap, to break; to bend"
  },
  {
    "id": "n4-0021",
    "jp": "～会",
    "reading": "～かい",
    "romaji": "～kai",
    "meaning": "~ meeting"
  },
  {
    "id": "n4-0022",
    "jp": "うかがう",
    "reading": "うかがう",
    "romaji": "ukagau",
    "meaning": "to ask"
  },
  {
    "id": "n4-0023",
    "jp": "聞こえる",
    "reading": "きこえる",
    "romaji": "kikoeru",
    "meaning": "to be heard, to be audible"
  },
  {
    "id": "n4-0024",
    "jp": "僕",
    "reading": "ぼく",
    "romaji": "boku",
    "meaning": "I (used by men towards those of equal or lower status)"
  },
  {
    "id": "n4-0025",
    "jp": "必ず",
    "reading": "かならず",
    "romaji": "kanarazu",
    "meaning": "surely, certainly"
  },
  {
    "id": "n4-0026",
    "jp": "壊す",
    "reading": "こわす",
    "romaji": "kowasu",
    "meaning": "to break, to break down"
  },
  {
    "id": "n4-0027",
    "jp": "怒る",
    "reading": "おこる",
    "romaji": "okoru",
    "meaning": "to get angry; to scold angrily"
  },
  {
    "id": "n4-0028",
    "jp": "床屋",
    "reading": "とこや",
    "romaji": "tokoya",
    "meaning": "barber's (shop)"
  },
  {
    "id": "n4-0029",
    "jp": "オートバイ",
    "reading": "オートバイ",
    "romaji": "オートバイ",
    "meaning": "motorcycle (lit: auto-bi(ke))"
  },
  {
    "id": "n4-0030",
    "jp": "運動",
    "reading": "うんどうする",
    "romaji": "undousuru",
    "meaning": "exercise"
  },
  {
    "id": "n4-0031",
    "jp": "止む",
    "reading": "やむ",
    "romaji": "yamu",
    "meaning": "to cease, to stop"
  },
  {
    "id": "n4-0032",
    "jp": "もし",
    "reading": "もし",
    "romaji": "moshi",
    "meaning": "if"
  },
  {
    "id": "n4-0033",
    "jp": "表",
    "reading": "おもて",
    "romaji": "omote",
    "meaning": "surface; front; outside"
  },
  {
    "id": "n4-0034",
    "jp": "大学生",
    "reading": "だいがくせい",
    "romaji": "daigakusei",
    "meaning": "college student, university student"
  },
  {
    "id": "n4-0035",
    "jp": "運転手",
    "reading": "うんてんしゅ",
    "romaji": "untenshu",
    "meaning": "driver (by occupation)"
  },
  {
    "id": "n4-0036",
    "jp": "予習",
    "reading": "よしゅう",
    "romaji": "yoshuu",
    "meaning": "preparation of lessons (for class)"
  },
  {
    "id": "n4-0037",
    "jp": "心配",
    "reading": "しんぱいする",
    "romaji": "shinpaisuru",
    "meaning": "worry, concern"
  },
  {
    "id": "n4-0038",
    "jp": "別",
    "reading": "べつ",
    "romaji": "betsu",
    "meaning": "distinction, different"
  },
  {
    "id": "n4-0039",
    "jp": "非常に",
    "reading": "ひじょうに",
    "romaji": "hijouni",
    "meaning": "extremely; very"
  },
  {
    "id": "n4-0040",
    "jp": "お宅",
    "reading": "おたく",
    "romaji": "otaku",
    "meaning": "(someone else's) house; home -- polite word for 家 (いえ) --"
  },
  {
    "id": "n4-0041",
    "jp": "柔らかい",
    "reading": "やわらかい",
    "romaji": "yawarakai",
    "meaning": "soft (in reference to texture), tender"
  },
  {
    "id": "n4-0042",
    "jp": "拾う",
    "reading": "ひろう",
    "romaji": "hirou",
    "meaning": "to pick up (something), to find"
  },
  {
    "id": "n4-0043",
    "jp": "～ございます",
    "reading": "～ございます",
    "romaji": "～gozaimasu",
    "meaning": "to be (polite), to exist"
  },
  {
    "id": "n4-0044",
    "jp": "気",
    "reading": "き",
    "romaji": "ki",
    "meaning": "spirit, mood"
  },
  {
    "id": "n4-0045",
    "jp": "比べる",
    "reading": "くらべる",
    "romaji": "kuraberu",
    "meaning": "to compare"
  },
  {
    "id": "n4-0046",
    "jp": "ほとんど",
    "reading": "ほとんど",
    "romaji": "hotondo",
    "meaning": "mostly, almost"
  },
  {
    "id": "n4-0047",
    "jp": "つもり",
    "reading": "つもり",
    "romaji": "tsumori",
    "meaning": "intention, plan"
  },
  {
    "id": "n4-0048",
    "jp": "郊外",
    "reading": "こうがい",
    "romaji": "kougai",
    "meaning": "suburb, outskirts"
  },
  {
    "id": "n4-0049",
    "jp": "だめ",
    "reading": "だめ",
    "romaji": "dame",
    "meaning": "useless, no good, hopeless"
  },
  {
    "id": "n4-0050",
    "jp": "売り場",
    "reading": "うりば",
    "romaji": "uriba",
    "meaning": "place where things are sold"
  },
  {
    "id": "n4-0051",
    "jp": "正月",
    "reading": "しょうがつ",
    "romaji": "shougatsu",
    "meaning": "New Year, New Year's Day"
  },
  {
    "id": "n4-0052",
    "jp": "規則",
    "reading": "きそく",
    "romaji": "kisoku",
    "meaning": "rule, regulation"
  },
  {
    "id": "n4-0053",
    "jp": "うん",
    "reading": "うん",
    "romaji": "un",
    "meaning": "yes (informal), all right (ok)"
  },
  {
    "id": "n4-0054",
    "jp": "発音",
    "reading": "はつおん",
    "romaji": "hatsuon",
    "meaning": "pronunciation"
  },
  {
    "id": "n4-0055",
    "jp": "焼く",
    "reading": "やく",
    "romaji": "yaku",
    "meaning": "to bake, to grill"
  },
  {
    "id": "n4-0056",
    "jp": "屋上",
    "reading": "おくじょう",
    "romaji": "okujou",
    "meaning": "rooftop"
  },
  {
    "id": "n4-0057",
    "jp": "失礼",
    "reading": "しつれい",
    "romaji": "shitsurei",
    "meaning": "discourtesy, impoliteness; Excuse me"
  },
  {
    "id": "n4-0058",
    "jp": "ごみ",
    "reading": "ごみ",
    "romaji": "gomi",
    "meaning": "trash, garbage"
  },
  {
    "id": "n4-0059",
    "jp": "アフリカ",
    "reading": "アフリカ",
    "romaji": "アフリカ",
    "meaning": "Africa"
  },
  {
    "id": "n4-0060",
    "jp": "点",
    "reading": "てん",
    "romaji": "ten",
    "meaning": "mark, score, grade; point, dot"
  },
  {
    "id": "n4-0061",
    "jp": "一生懸命",
    "reading": "いっしょうけんめい",
    "romaji": "isshoukenmei",
    "meaning": "very hard (as in \"to work hard\"), with utmost effort"
  },
  {
    "id": "n4-0062",
    "jp": "今度",
    "reading": "こんど",
    "romaji": "kondo",
    "meaning": "now, this time, near future, one of these days, next time"
  },
  {
    "id": "n4-0063",
    "jp": "機会",
    "reading": "きかい",
    "romaji": "kikai",
    "meaning": "chance, opportunity"
  },
  {
    "id": "n4-0064",
    "jp": "建てる",
    "reading": "たてる",
    "romaji": "tateru",
    "meaning": "to build"
  },
  {
    "id": "n4-0065",
    "jp": "複雑",
    "reading": "ふくざつ",
    "romaji": "fukuzatsu",
    "meaning": "complexity, complication"
  },
  {
    "id": "n4-0066",
    "jp": "彼",
    "reading": "かれ",
    "romaji": "kare",
    "meaning": "he, boyfriend"
  },
  {
    "id": "n4-0067",
    "jp": "いらっしゃる",
    "reading": "いらっしゃる",
    "romaji": "irassharu",
    "meaning": "-- honorific expression for いく, くる, and いる --"
  },
  {
    "id": "n4-0068",
    "jp": "布団",
    "reading": "ふとん",
    "romaji": "futon",
    "meaning": "futon"
  },
  {
    "id": "n4-0069",
    "jp": "大事",
    "reading": "だいじ",
    "romaji": "daiji",
    "meaning": "important, valuable, serious matter"
  },
  {
    "id": "n4-0070",
    "jp": "贈り物",
    "reading": "おくりもの",
    "romaji": "okurimono",
    "meaning": "a gift; a present"
  },
  {
    "id": "n4-0071",
    "jp": "泥棒",
    "reading": "どろぼう",
    "romaji": "dorobou",
    "meaning": "thief; burglar"
  },
  {
    "id": "n4-0072",
    "jp": "～製",
    "reading": "～せい",
    "romaji": "～sei",
    "meaning": "made in ~"
  },
  {
    "id": "n4-0073",
    "jp": "注意",
    "reading": "ちゅうい",
    "romaji": "chuui",
    "meaning": "caution, attention"
  },
  {
    "id": "n4-0074",
    "jp": "台風",
    "reading": "たいふう",
    "romaji": "taifuu",
    "meaning": "typhoon"
  },
  {
    "id": "n4-0075",
    "jp": "日",
    "reading": "ひ",
    "romaji": "hi",
    "meaning": "sun, sunshine, day"
  },
  {
    "id": "n4-0076",
    "jp": "～軒",
    "reading": "～けん",
    "romaji": "～ken",
    "meaning": "counter for houses"
  },
  {
    "id": "n4-0077",
    "jp": "そう",
    "reading": "そう",
    "romaji": "sou",
    "meaning": "really, (is that) so; yes, right"
  },
  {
    "id": "n4-0078",
    "jp": "通る",
    "reading": "とおる",
    "romaji": "tooru",
    "meaning": "to pass (by), to go through"
  },
  {
    "id": "n4-0079",
    "jp": "過ぎる",
    "reading": "すぎる",
    "romaji": "sugiru",
    "meaning": "to exceed, to go beyond"
  },
  {
    "id": "n4-0080",
    "jp": "レポート; リポート",
    "reading": "レポート; リポート",
    "romaji": "レポート; リポート",
    "meaning": "report"
  },
  {
    "id": "n4-0081",
    "jp": "葉",
    "reading": "は",
    "romaji": "ha",
    "meaning": "leaf"
  },
  {
    "id": "n4-0082",
    "jp": "必要",
    "reading": "ひつよう",
    "romaji": "hitsuyou",
    "meaning": "necessary"
  },
  {
    "id": "n4-0083",
    "jp": "課長",
    "reading": "かちょう",
    "romaji": "kachou",
    "meaning": "section manager"
  },
  {
    "id": "n4-0084",
    "jp": "地震",
    "reading": "じしん",
    "romaji": "jishin",
    "meaning": "earthquake"
  },
  {
    "id": "n4-0085",
    "jp": "すると",
    "reading": "すると",
    "romaji": "suruto",
    "meaning": "and, then"
  },
  {
    "id": "n4-0086",
    "jp": "止める",
    "reading": "やめる",
    "romaji": "yameru",
    "meaning": "to end, to stop"
  },
  {
    "id": "n4-0087",
    "jp": "ガラス",
    "reading": "ガラス",
    "romaji": "ガラス",
    "meaning": "glass, pane"
  },
  {
    "id": "n4-0088",
    "jp": "～学部",
    "reading": "～がくぶ",
    "romaji": "～gakubu",
    "meaning": "department of a university"
  },
  {
    "id": "n4-0089",
    "jp": "厳しい",
    "reading": "きびしい",
    "romaji": "kibishii",
    "meaning": "hard; rigorous; strict"
  },
  {
    "id": "n4-0090",
    "jp": "エスカレーター",
    "reading": "エスカレーター",
    "romaji": "エスカレーター",
    "meaning": "escalator"
  },
  {
    "id": "n4-0091",
    "jp": "人口",
    "reading": "じんこう",
    "romaji": "jinkou",
    "meaning": "population"
  },
  {
    "id": "n4-0092",
    "jp": "月",
    "reading": "つき",
    "romaji": "tsuki",
    "meaning": "moon"
  },
  {
    "id": "n4-0093",
    "jp": "絹",
    "reading": "きぬ",
    "romaji": "kinu",
    "meaning": "silk"
  },
  {
    "id": "n4-0094",
    "jp": "ちっとも",
    "reading": "ちっとも",
    "romaji": "chittomo",
    "meaning": "not at all (neg. verb)"
  },
  {
    "id": "n4-0095",
    "jp": "深い",
    "reading": "ふかい",
    "romaji": "fukai",
    "meaning": "deep, profound"
  },
  {
    "id": "n4-0096",
    "jp": "壊れる",
    "reading": "こわれる",
    "romaji": "kowareru",
    "meaning": "to be broken, to break"
  },
  {
    "id": "n4-0097",
    "jp": "揺れる",
    "reading": "ゆれる",
    "romaji": "yureru",
    "meaning": "to shake, to sway"
  },
  {
    "id": "n4-0098",
    "jp": "落る",
    "reading": "おちる",
    "romaji": "ochiru",
    "meaning": "to fall, to drop"
  },
  {
    "id": "n4-0099",
    "jp": "できるだけ",
    "reading": "できるだけ",
    "romaji": "dekirudake",
    "meaning": "if at all possible, as much as possible"
  },
  {
    "id": "n4-0100",
    "jp": "悲しい",
    "reading": "かなしい",
    "romaji": "kanashii",
    "meaning": "sad, sorrowful"
  },
  {
    "id": "n4-0101",
    "jp": "中学校",
    "reading": "ちゅうがっこう",
    "romaji": "chuugakkou",
    "meaning": "junior high school pupil"
  },
  {
    "id": "n4-0102",
    "jp": "ガス",
    "reading": "ガス",
    "romaji": "ガス",
    "meaning": "gas"
  },
  {
    "id": "n4-0103",
    "jp": "祈る",
    "reading": "いのる",
    "romaji": "inoru",
    "meaning": "to pray; to wish"
  },
  {
    "id": "n4-0104",
    "jp": "盛ん",
    "reading": "さかん",
    "romaji": "sakan",
    "meaning": "prosperous, active, thriving"
  },
  {
    "id": "n4-0105",
    "jp": "アルバイト",
    "reading": "アルバイト",
    "romaji": "アルバイト",
    "meaning": "part-time job"
  },
  {
    "id": "n4-0106",
    "jp": "起こす",
    "reading": "おこす",
    "romaji": "okosu",
    "meaning": "to wake (someone) up"
  },
  {
    "id": "n4-0107",
    "jp": "致す",
    "reading": "いたす",
    "romaji": "itasu",
    "meaning": "-- extra-modest expression for する --"
  },
  {
    "id": "n4-0108",
    "jp": "噛む",
    "reading": "かむ",
    "romaji": "kamu",
    "meaning": "to bite, to chew"
  },
  {
    "id": "n4-0109",
    "jp": "赤ちゃん",
    "reading": "あかちゃん",
    "romaji": "akachan",
    "meaning": "baby, infant"
  },
  {
    "id": "n4-0110",
    "jp": "浅い",
    "reading": "あさい",
    "romaji": "asai",
    "meaning": "shallow, superficial"
  },
  {
    "id": "n4-0111",
    "jp": "うそ",
    "reading": "嘘",
    "romaji": "嘘",
    "meaning": "lie"
  },
  {
    "id": "n4-0112",
    "jp": "小説",
    "reading": "しょうせつ",
    "romaji": "shousetsu",
    "meaning": "novel"
  },
  {
    "id": "n4-0113",
    "jp": "親",
    "reading": "おや",
    "romaji": "oya",
    "meaning": "a parent"
  },
  {
    "id": "n4-0114",
    "jp": "それに",
    "reading": "それに",
    "romaji": "soreni",
    "meaning": "moreover; besides"
  },
  {
    "id": "n4-0115",
    "jp": "西洋",
    "reading": "せいよう",
    "romaji": "seiyou",
    "meaning": "the West, Western countries"
  },
  {
    "id": "n4-0116",
    "jp": "思う",
    "reading": "おもう",
    "romaji": "omou",
    "meaning": "to think, to feel"
  },
  {
    "id": "n4-0117",
    "jp": "パート (タイム)",
    "reading": "パート (タイム)",
    "romaji": "パート (タイム)",
    "meaning": "part time (esp. female part time employees)"
  },
  {
    "id": "n4-0118",
    "jp": "時代",
    "reading": "じだい",
    "romaji": "jidai",
    "meaning": "age, period, epoch, era"
  },
  {
    "id": "n4-0119",
    "jp": "申し上げる",
    "reading": "もうしあげる",
    "romaji": "moushiageru",
    "meaning": "(humble)to say, to tell"
  },
  {
    "id": "n4-0120",
    "jp": "～式",
    "reading": "～しき",
    "romaji": "～shiki",
    "meaning": "~ ceremony; ~ style"
  },
  {
    "id": "n4-0121",
    "jp": "出席",
    "reading": "しゅっせきする",
    "romaji": "shussekisuru",
    "meaning": "attendance"
  },
  {
    "id": "n4-0122",
    "jp": "～家",
    "reading": "～か",
    "romaji": "～ka",
    "meaning": "person who is specialized in ~"
  },
  {
    "id": "n4-0123",
    "jp": "迎える",
    "reading": "むかえる",
    "romaji": "mukaeru",
    "meaning": "to welcome; to meet; to greet"
  },
  {
    "id": "n4-0124",
    "jp": "触る",
    "reading": "さわる",
    "romaji": "sawaru",
    "meaning": "to touch, to feel"
  },
  {
    "id": "n4-0125",
    "jp": "建て",
    "reading": "～だて",
    "romaji": "～date",
    "meaning": "~ storied, separate housing"
  },
  {
    "id": "n4-0126",
    "jp": "社長",
    "reading": "しゃちょう",
    "romaji": "shachou",
    "meaning": "president of a company"
  },
  {
    "id": "n4-0127",
    "jp": "動物園",
    "reading": "どうぶつえん",
    "romaji": "doubutsuen",
    "meaning": "zoo"
  },
  {
    "id": "n4-0128",
    "jp": "捕まえる",
    "reading": "つかまえる",
    "romaji": "tsukamaeru",
    "meaning": "to catch, to arrest"
  },
  {
    "id": "n4-0129",
    "jp": "季節",
    "reading": "きせつ",
    "romaji": "kisetsu",
    "meaning": "season (in reference to weather)"
  },
  {
    "id": "n4-0130",
    "jp": "寄る",
    "reading": "よる",
    "romaji": "yoru",
    "meaning": "to stop by"
  },
  {
    "id": "n4-0131",
    "jp": "決まる",
    "reading": "きまる",
    "romaji": "kimaru",
    "meaning": "to be set; fixed (v.i.)"
  },
  {
    "id": "n4-0132",
    "jp": "開く",
    "reading": "ひらく",
    "romaji": "hiraku",
    "meaning": "to open; to hold (an event)"
  },
  {
    "id": "n4-0133",
    "jp": "逃げる",
    "reading": "にげる",
    "romaji": "nigeru",
    "meaning": "to escape, to run away"
  },
  {
    "id": "n4-0134",
    "jp": "だから",
    "reading": "だから",
    "romaji": "dakara",
    "meaning": "so; therefore"
  },
  {
    "id": "n4-0135",
    "jp": "残念",
    "reading": "ざんねん",
    "romaji": "zannen",
    "meaning": "regret; regrettable"
  },
  {
    "id": "n4-0136",
    "jp": "畳",
    "reading": "たたみ",
    "romaji": "tatami",
    "meaning": "tatami mat (Japanese straw mat)"
  },
  {
    "id": "n4-0137",
    "jp": "丁寧",
    "reading": "ていねい",
    "romaji": "teinei",
    "meaning": "polite, courteous, careful"
  },
  {
    "id": "n4-0138",
    "jp": "地理",
    "reading": "ちり",
    "romaji": "chiri",
    "meaning": "geography"
  },
  {
    "id": "n4-0139",
    "jp": "さっき",
    "reading": "さっき",
    "romaji": "sakki",
    "meaning": "a little while ago"
  },
  {
    "id": "n4-0140",
    "jp": "怖い",
    "reading": "こわい",
    "romaji": "kowai",
    "meaning": "scary, frightening"
  },
  {
    "id": "n4-0141",
    "jp": "包む",
    "reading": "つつむ",
    "romaji": "tsutsumu",
    "meaning": "to wrap, to cover"
  },
  {
    "id": "n4-0142",
    "jp": "なるべく",
    "reading": "なるべく",
    "romaji": "narubeku",
    "meaning": "if possible, as much as possible"
  },
  {
    "id": "n4-0143",
    "jp": "無理",
    "reading": "むり",
    "romaji": "muri",
    "meaning": "unreasonable, impossible"
  },
  {
    "id": "n4-0144",
    "jp": "サンドイッチ",
    "reading": "サンドイッチ",
    "romaji": "サンドイッチ",
    "meaning": "sandwich"
  },
  {
    "id": "n4-0145",
    "jp": "会議室",
    "reading": "かいぎしつ",
    "romaji": "kaigishitsu",
    "meaning": "conference room"
  },
  {
    "id": "n4-0146",
    "jp": "品物",
    "reading": "しなもの",
    "romaji": "shinamono",
    "meaning": "goods"
  },
  {
    "id": "n4-0147",
    "jp": "人形",
    "reading": "にんぎょう",
    "romaji": "ningyou",
    "meaning": "doll, figure"
  },
  {
    "id": "n4-0148",
    "jp": "利用",
    "reading": "りよう",
    "romaji": "riyou",
    "meaning": "use, utilization"
  },
  {
    "id": "n4-0149",
    "jp": "飾る",
    "reading": "かざる",
    "romaji": "kazaru",
    "meaning": "to decorate, to adorn"
  },
  {
    "id": "n4-0150",
    "jp": "止める",
    "reading": "とめる",
    "romaji": "tomeru",
    "meaning": "to stop (something)"
  },
  {
    "id": "n4-0151",
    "jp": "恥ずかしい",
    "reading": "はずかしい",
    "romaji": "hazukashii",
    "meaning": "ashamed, embarrassed"
  },
  {
    "id": "n4-0152",
    "jp": "いくら～ても",
    "reading": "いくら～ても",
    "romaji": "ikura～temo",
    "meaning": "however much one may ~"
  },
  {
    "id": "n4-0153",
    "jp": "用事",
    "reading": "ようじ",
    "romaji": "youji",
    "meaning": "business to take care of; tasks; errands"
  },
  {
    "id": "n4-0154",
    "jp": "ビル",
    "reading": "ビル",
    "romaji": "ビル",
    "meaning": "(abbr.) building"
  },
  {
    "id": "n4-0155",
    "jp": "けんかする",
    "reading": "けんかする",
    "romaji": "kenkasuru",
    "meaning": "quarrel"
  },
  {
    "id": "n4-0156",
    "jp": "頑張る",
    "reading": "がんばる",
    "romaji": "ganbaru",
    "meaning": "to try one's best, to try hard, to persist"
  },
  {
    "id": "n4-0157",
    "jp": "投げる",
    "reading": "なげる",
    "romaji": "nageru",
    "meaning": "to pitch, to cast away"
  },
  {
    "id": "n4-0158",
    "jp": "故障",
    "reading": "こしょうする",
    "romaji": "koshousuru",
    "meaning": "breakdown"
  },
  {
    "id": "n4-0159",
    "jp": "力",
    "reading": "ちから",
    "romaji": "chikara",
    "meaning": "strength, power"
  },
  {
    "id": "n4-0160",
    "jp": "受ける",
    "reading": "うける",
    "romaji": "ukeru",
    "meaning": "to take (an examination, interview, etc.); to receive"
  },
  {
    "id": "n4-0161",
    "jp": "気分",
    "reading": "きぶん",
    "romaji": "kibun",
    "meaning": "feeling, mood"
  },
  {
    "id": "n4-0162",
    "jp": "間違える",
    "reading": "まちがえる",
    "romaji": "machigaeru",
    "meaning": "to make a mistake"
  },
  {
    "id": "n4-0163",
    "jp": "そんな",
    "reading": "そんな",
    "romaji": "sonna",
    "meaning": "such, like that, that sort of"
  },
  {
    "id": "n4-0164",
    "jp": "星",
    "reading": "ほし",
    "romaji": "hoshi",
    "meaning": "star"
  },
  {
    "id": "n4-0165",
    "jp": "場合",
    "reading": "ばあい",
    "romaji": "baai",
    "meaning": "case, situation"
  },
  {
    "id": "n4-0166",
    "jp": "やっと",
    "reading": "やっと",
    "romaji": "yatto",
    "meaning": "at last, finally"
  },
  {
    "id": "n4-0167",
    "jp": "足りる",
    "reading": "たりる",
    "romaji": "tariru",
    "meaning": "to be sufficient; to be enough"
  },
  {
    "id": "n4-0168",
    "jp": "行う",
    "reading": "おこなう",
    "romaji": "okonau",
    "meaning": "to carry out; to conduct (typically used in written language)"
  },
  {
    "id": "n4-0169",
    "jp": "ぶどう",
    "reading": "ぶどう",
    "romaji": "budou",
    "meaning": "grapes"
  },
  {
    "id": "n4-0170",
    "jp": "無くなる",
    "reading": "なくなる",
    "romaji": "nakunaru",
    "meaning": "to disappear, to get lost"
  },
  {
    "id": "n4-0171",
    "jp": "準備",
    "reading": "じゅんびする",
    "romaji": "junbisuru",
    "meaning": "prepare"
  },
  {
    "id": "n4-0172",
    "jp": "世界",
    "reading": "せかい",
    "romaji": "sekai",
    "meaning": "world"
  },
  {
    "id": "n4-0173",
    "jp": "住所",
    "reading": "じゅうしょ",
    "romaji": "juusho",
    "meaning": "address; place of residence"
  },
  {
    "id": "n4-0174",
    "jp": "再来月",
    "reading": "さらいげつ",
    "romaji": "saraigetsu",
    "meaning": "the month after next"
  },
  {
    "id": "n4-0175",
    "jp": "林",
    "reading": "はやし",
    "romaji": "hayashi",
    "meaning": "woods, forest"
  },
  {
    "id": "n4-0176",
    "jp": "倍",
    "reading": "ばい",
    "romaji": "bai",
    "meaning": "double"
  },
  {
    "id": "n4-0177",
    "jp": "痩せる",
    "reading": "やせる",
    "romaji": "yaseru",
    "meaning": "to lose weight"
  },
  {
    "id": "n4-0178",
    "jp": "線",
    "reading": "せん",
    "romaji": "sen",
    "meaning": "line, wire"
  },
  {
    "id": "n4-0179",
    "jp": "戦争",
    "reading": "せんそう",
    "romaji": "sensou",
    "meaning": "war"
  },
  {
    "id": "n4-0180",
    "jp": "決める",
    "reading": "きめる",
    "romaji": "kimeru",
    "meaning": "to decide (v.t.)"
  },
  {
    "id": "n4-0181",
    "jp": "調べる",
    "reading": "しらべる",
    "romaji": "shiraberu",
    "meaning": "to check; to look up; to inquire; to search"
  },
  {
    "id": "n4-0182",
    "jp": "寝坊",
    "reading": "ねぼう",
    "romaji": "nebou",
    "meaning": "sleeping in late"
  },
  {
    "id": "n4-0183",
    "jp": "パパ",
    "reading": "パパ",
    "romaji": "パパ",
    "meaning": "papa, daddy"
  },
  {
    "id": "n4-0184",
    "jp": "光る",
    "reading": "ひかる",
    "romaji": "hikaru",
    "meaning": "to shine, to glitter"
  },
  {
    "id": "n4-0185",
    "jp": "夫",
    "reading": "おっと",
    "romaji": "otto",
    "meaning": "husband"
  },
  {
    "id": "n4-0186",
    "jp": "雲",
    "reading": "くも",
    "romaji": "kumo",
    "meaning": "cloud"
  },
  {
    "id": "n4-0187",
    "jp": "坂",
    "reading": "さか",
    "romaji": "saka",
    "meaning": "slope, hill"
  },
  {
    "id": "n4-0188",
    "jp": "～(て) しまう",
    "reading": "～(て) しまう",
    "romaji": "～(te) shimau",
    "meaning": "to end up ~"
  },
  {
    "id": "n4-0189",
    "jp": "飛行場",
    "reading": "ひこうじょう",
    "romaji": "hikoujou",
    "meaning": "airport"
  },
  {
    "id": "n4-0190",
    "jp": "柔道",
    "reading": "じゅうどう",
    "romaji": "juudou",
    "meaning": "judo"
  },
  {
    "id": "n4-0191",
    "jp": "決して",
    "reading": "けっして",
    "romaji": "kesshite",
    "meaning": "never"
  },
  {
    "id": "n4-0192",
    "jp": "事務所",
    "reading": "じむしょ",
    "romaji": "jimusho",
    "meaning": "office"
  },
  {
    "id": "n4-0193",
    "jp": "連絡",
    "reading": "れんらく",
    "romaji": "renraku",
    "meaning": "communication, contact, connection"
  },
  {
    "id": "n4-0194",
    "jp": "小学校",
    "reading": "しょうがっこう",
    "romaji": "shougakkou",
    "meaning": "elementary school"
  },
  {
    "id": "n4-0195",
    "jp": "客",
    "reading": "きゃく",
    "romaji": "kyaku",
    "meaning": "guest, customer"
  },
  {
    "id": "n4-0196",
    "jp": "昔",
    "reading": "むかし",
    "romaji": "mukashi",
    "meaning": "old days; past"
  },
  {
    "id": "n4-0197",
    "jp": "美しい",
    "reading": "うつくしい",
    "romaji": "utsukushii",
    "meaning": "beautiful, lovely"
  },
  {
    "id": "n4-0198",
    "jp": "捨てる",
    "reading": "すてる",
    "romaji": "suteru",
    "meaning": "throw away (trash), dump, discard"
  },
  {
    "id": "n4-0199",
    "jp": "なさる",
    "reading": "なさる",
    "romaji": "nasaru",
    "meaning": "-- honorific expression for する --"
  },
  {
    "id": "n4-0200",
    "jp": "事",
    "reading": "こと",
    "romaji": "koto",
    "meaning": "thing(s), matter(s), fact"
  },
  {
    "id": "n4-0201",
    "jp": "どんどん",
    "reading": "どんどん",
    "romaji": "dondon",
    "meaning": "quickly and steadily; at a rapid pace"
  },
  {
    "id": "n4-0202",
    "jp": "試合",
    "reading": "しあい",
    "romaji": "shiai",
    "meaning": "match, game, competition"
  },
  {
    "id": "n4-0203",
    "jp": "適当",
    "reading": "てきとう",
    "romaji": "tekitou",
    "meaning": "fitness, suitability"
  },
  {
    "id": "n4-0204",
    "jp": "素晴らしい",
    "reading": "すばらしい",
    "romaji": "subarashii",
    "meaning": "wonderful; terrific"
  },
  {
    "id": "n4-0205",
    "jp": "美術館",
    "reading": "びじゅつかん",
    "romaji": "bijutsukan",
    "meaning": "art gallery, art museum"
  },
  {
    "id": "n4-0206",
    "jp": "文法",
    "reading": "ぶんぽう",
    "romaji": "bunpou",
    "meaning": "grammar"
  },
  {
    "id": "n4-0207",
    "jp": "終わり",
    "reading": "おわり",
    "romaji": "owari",
    "meaning": "end"
  },
  {
    "id": "n4-0208",
    "jp": "壁",
    "reading": "かべ",
    "romaji": "kabe",
    "meaning": "wall"
  },
  {
    "id": "n4-0209",
    "jp": "一度",
    "reading": "いちど",
    "romaji": "ichido",
    "meaning": "once, one time"
  },
  {
    "id": "n4-0210",
    "jp": "お礼",
    "reading": "おれい",
    "romaji": "orei",
    "meaning": "expression of gratitude; thanking; gift of appreciation; bow"
  },
  {
    "id": "n4-0211",
    "jp": "親切",
    "reading": "しんせつ",
    "romaji": "shinsetsu",
    "meaning": "kindness"
  },
  {
    "id": "n4-0212",
    "jp": "知らせる",
    "reading": "しらせる",
    "romaji": "shiraseru",
    "meaning": "to notify"
  },
  {
    "id": "n4-0213",
    "jp": "歯医者",
    "reading": "はいしゃ",
    "romaji": "haisha",
    "meaning": "dentist"
  },
  {
    "id": "n4-0214",
    "jp": "熱心",
    "reading": "ねっしん",
    "romaji": "nesshin",
    "meaning": "enthusiasm"
  },
  {
    "id": "n4-0215",
    "jp": "始める",
    "reading": "はじめる",
    "romaji": "hajimeru",
    "meaning": "to start, to begin"
  },
  {
    "id": "n4-0216",
    "jp": "もらう",
    "reading": "もらう",
    "romaji": "morau",
    "meaning": "to receive"
  },
  {
    "id": "n4-0217",
    "jp": "泣く",
    "reading": "なく",
    "romaji": "naku",
    "meaning": "to cry"
  },
  {
    "id": "n4-0218",
    "jp": "治る",
    "reading": "なおる",
    "romaji": "naoru",
    "meaning": "to get better; to recover from illness (v.i.)"
  },
  {
    "id": "n4-0219",
    "jp": "熱",
    "reading": "ねつ",
    "romaji": "netsu",
    "meaning": "fever, temperature"
  },
  {
    "id": "n4-0220",
    "jp": "お祭り",
    "reading": "おまつり",
    "romaji": "omatsuri",
    "meaning": "festival"
  },
  {
    "id": "n4-0221",
    "jp": "水道",
    "reading": "すいどう",
    "romaji": "suidou",
    "meaning": "water service, water line"
  },
  {
    "id": "n4-0222",
    "jp": "匂い",
    "reading": "におい",
    "romaji": "nioi",
    "meaning": "odor, smell"
  },
  {
    "id": "n4-0223",
    "jp": "ベル",
    "reading": "ベル",
    "romaji": "ベル",
    "meaning": "bell"
  },
  {
    "id": "n4-0224",
    "jp": "赤ん坊",
    "reading": "あかんぼう",
    "romaji": "akanbou",
    "meaning": "baby"
  },
  {
    "id": "n4-0225",
    "jp": "おかしい",
    "reading": "おかしい",
    "romaji": "okashii",
    "meaning": "strange; odd; funny"
  },
  {
    "id": "n4-0226",
    "jp": "事故",
    "reading": "じこ",
    "romaji": "jiko",
    "meaning": "accident"
  },
  {
    "id": "n4-0227",
    "jp": "変",
    "reading": "へん",
    "romaji": "hen",
    "meaning": "strange, odd"
  },
  {
    "id": "n4-0228",
    "jp": "辞典",
    "reading": "じてん",
    "romaji": "jiten",
    "meaning": "encyclopedia, reference book"
  },
  {
    "id": "n4-0229",
    "jp": "残る",
    "reading": "のこる",
    "romaji": "nokoru",
    "meaning": "to remain (v.i.), to be left"
  },
  {
    "id": "n4-0230",
    "jp": "立てる",
    "reading": "たてる",
    "romaji": "tateru",
    "meaning": "to stand (something) up, to erect (something)"
  },
  {
    "id": "n4-0231",
    "jp": "くれる",
    "reading": "くれる",
    "romaji": "kureru",
    "meaning": "to give, to do for"
  },
  {
    "id": "n4-0232",
    "jp": "～員",
    "reading": "～いん",
    "romaji": "～in",
    "meaning": "member of ~"
  },
  {
    "id": "n4-0233",
    "jp": "原因",
    "reading": "げんいん",
    "romaji": "gen'in",
    "meaning": "cause, origin, source"
  },
  {
    "id": "n4-0234",
    "jp": "驚く",
    "reading": "おどろく",
    "romaji": "odoroku",
    "meaning": "to be surprised, to be astonished"
  },
  {
    "id": "n4-0235",
    "jp": "いただく",
    "reading": "頂く",
    "romaji": "頂ku",
    "meaning": "-- extra-modest expression for たべる and のむ; humble expression for もらう --"
  },
  {
    "id": "n4-0236",
    "jp": "祖母",
    "reading": "そぼ",
    "romaji": "sobo",
    "meaning": "grandmother"
  },
  {
    "id": "n4-0237",
    "jp": "場所",
    "reading": "ばしょ",
    "romaji": "basho",
    "meaning": "place, location"
  },
  {
    "id": "n4-0238",
    "jp": "答",
    "reading": "こたえ",
    "romaji": "kotae",
    "meaning": "answer, response"
  },
  {
    "id": "n4-0239",
    "jp": "もちろん",
    "reading": "もちろん",
    "romaji": "mochiron",
    "meaning": "certainly, of course"
  },
  {
    "id": "n4-0240",
    "jp": "漬ける",
    "reading": "つける",
    "romaji": "tsukeru",
    "meaning": "to soak, to moisten, to pickle"
  },
  {
    "id": "n4-0241",
    "jp": "受付",
    "reading": "うけつけ",
    "romaji": "uketsuke",
    "meaning": "reception(ist) desk"
  },
  {
    "id": "n4-0242",
    "jp": "内",
    "reading": "うち",
    "romaji": "uchi",
    "meaning": "within, inside"
  },
  {
    "id": "n4-0243",
    "jp": "スクリーン",
    "reading": "スクリーン",
    "romaji": "スクリーン",
    "meaning": "screen"
  },
  {
    "id": "n4-0244",
    "jp": "増える",
    "reading": "ふえる",
    "romaji": "fueru",
    "meaning": "to increase, to multiply"
  },
  {
    "id": "n4-0245",
    "jp": "または",
    "reading": "または",
    "romaji": "mataha",
    "meaning": "or, otherwise"
  },
  {
    "id": "n4-0246",
    "jp": "けがする",
    "reading": "けがする",
    "romaji": "kegasuru",
    "meaning": "injury (to animate object), hurt"
  },
  {
    "id": "n4-0247",
    "jp": "以下",
    "reading": "いか",
    "romaji": "ika",
    "meaning": "less than, below"
  },
  {
    "id": "n4-0248",
    "jp": "選ぶ",
    "reading": "えらぶ",
    "romaji": "erabu",
    "meaning": "to choose; to select"
  },
  {
    "id": "n4-0249",
    "jp": "～ばかり",
    "reading": "～ばかり",
    "romaji": "～bakari",
    "meaning": "just did ~, only"
  },
  {
    "id": "n4-0250",
    "jp": "心",
    "reading": "こころ",
    "romaji": "kokoro",
    "meaning": "heart, mind"
  },
  {
    "id": "n4-0251",
    "jp": "～だす",
    "reading": "～だす",
    "romaji": "～dasu",
    "meaning": "to start doing ~"
  },
  {
    "id": "n4-0252",
    "jp": "サラダ",
    "reading": "サラダ",
    "romaji": "サラダ",
    "meaning": "salad"
  },
  {
    "id": "n4-0253",
    "jp": "届ける",
    "reading": "とどける",
    "romaji": "todokeru",
    "meaning": "to deliver (v.t.)"
  },
  {
    "id": "n4-0254",
    "jp": "あいさつする",
    "reading": "挨拶",
    "romaji": "挨拶",
    "meaning": "greet(ing)"
  },
  {
    "id": "n4-0255",
    "jp": "景色",
    "reading": "けしき",
    "romaji": "keshiki",
    "meaning": "scenery, landscape"
  },
  {
    "id": "n4-0256",
    "jp": "確か",
    "reading": "たしか",
    "romaji": "tashika",
    "meaning": "if I remember correctly; certain, definite"
  },
  {
    "id": "n4-0257",
    "jp": "ステーキ",
    "reading": "ステーキ",
    "romaji": "ステーキ",
    "meaning": "steak"
  },
  {
    "id": "n4-0258",
    "jp": "食料品",
    "reading": "しょくりょうひん",
    "romaji": "shokuryouhin",
    "meaning": "foodstuff, groceries"
  },
  {
    "id": "n4-0259",
    "jp": "森",
    "reading": "もり",
    "romaji": "mori",
    "meaning": "forest"
  },
  {
    "id": "n4-0260",
    "jp": "以内",
    "reading": "いない",
    "romaji": "inai",
    "meaning": "within, less (no more) than"
  },
  {
    "id": "n4-0261",
    "jp": "予定",
    "reading": "よてい",
    "romaji": "yotei",
    "meaning": "plans, arrangement, schedule"
  },
  {
    "id": "n4-0262",
    "jp": "オーバー",
    "reading": "オーバー",
    "romaji": "オーバー",
    "meaning": "overcoat; over, exceeding, exaggeration"
  },
  {
    "id": "n4-0263",
    "jp": "乾く",
    "reading": "かわく",
    "romaji": "kawaku",
    "meaning": "to get dry"
  },
  {
    "id": "n4-0264",
    "jp": "石",
    "reading": "いし",
    "romaji": "ishi",
    "meaning": "stone"
  },
  {
    "id": "n4-0265",
    "jp": "思い出す",
    "reading": "おもいだす",
    "romaji": "omoidasu",
    "meaning": "to recall, to remember"
  },
  {
    "id": "n4-0266",
    "jp": "踊る",
    "reading": "おどる",
    "romaji": "odoru",
    "meaning": "to dance"
  },
  {
    "id": "n4-0267",
    "jp": "細かい",
    "reading": "こまかい",
    "romaji": "komakai",
    "meaning": "small; fine, minute"
  },
  {
    "id": "n4-0268",
    "jp": "塗る",
    "reading": "ぬる",
    "romaji": "nuru",
    "meaning": "to paint, to plaster"
  },
  {
    "id": "n4-0269",
    "jp": "ご主人",
    "reading": "ごしゅじん",
    "romaji": "goshujin",
    "meaning": "(your, her) husband"
  },
  {
    "id": "n4-0270",
    "jp": "珍しい",
    "reading": "めずらしい",
    "romaji": "mezurashii",
    "meaning": "unusual, rare"
  },
  {
    "id": "n4-0271",
    "jp": "用",
    "reading": "よう",
    "romaji": "you",
    "meaning": "errand, task, business (to take care of)"
  },
  {
    "id": "n4-0272",
    "jp": "公務員",
    "reading": "こうむいん",
    "romaji": "koumuin",
    "meaning": "government worker, public servant"
  },
  {
    "id": "n4-0273",
    "jp": "お嬢さん",
    "reading": "おじょうさん",
    "romaji": "ojousan",
    "meaning": "(someone's) daughter (polite)"
  },
  {
    "id": "n4-0274",
    "jp": "用意",
    "reading": "ようい",
    "romaji": "youi",
    "meaning": "preparation"
  },
  {
    "id": "n4-0275",
    "jp": "探す",
    "reading": "さがす",
    "romaji": "sagasu",
    "meaning": "to search, to seek, to look for"
  },
  {
    "id": "n4-0276",
    "jp": "形",
    "reading": "かたち",
    "romaji": "katachi",
    "meaning": "shape"
  },
  {
    "id": "n4-0277",
    "jp": "運転",
    "reading": "うんてんする",
    "romaji": "untensuru",
    "meaning": "driving"
  },
  {
    "id": "n4-0278",
    "jp": "すっかり",
    "reading": "すっかり",
    "romaji": "sukkari",
    "meaning": "all, completely"
  },
  {
    "id": "n4-0279",
    "jp": "アナウンサー",
    "reading": "アナウンサー",
    "romaji": "アナウンサー",
    "meaning": "announcer"
  },
  {
    "id": "n4-0280",
    "jp": "お土産",
    "reading": "おみやげ",
    "romaji": "omiyage",
    "meaning": "souvenir"
  },
  {
    "id": "n4-0281",
    "jp": "消しゴム",
    "reading": "けしゴム",
    "romaji": "keshiゴム",
    "meaning": "eraser"
  },
  {
    "id": "n4-0282",
    "jp": "旅館",
    "reading": "りょかん",
    "romaji": "ryokan",
    "meaning": "a Japanese inn"
  },
  {
    "id": "n4-0283",
    "jp": "海岸",
    "reading": "かいがん",
    "romaji": "kaigan",
    "meaning": "coast, seashore"
  },
  {
    "id": "n4-0284",
    "jp": "寂しい",
    "reading": "さびしい",
    "romaji": "sabishii",
    "meaning": "lonely, lonesome"
  },
  {
    "id": "n4-0285",
    "jp": "火",
    "reading": "ひ",
    "romaji": "hi",
    "meaning": "fire"
  },
  {
    "id": "n4-0286",
    "jp": "育てる",
    "reading": "そだてる",
    "romaji": "sodateru",
    "meaning": "to raise (v.t.); to bring up"
  },
  {
    "id": "n4-0287",
    "jp": "味噌",
    "reading": "みそ",
    "romaji": "miso",
    "meaning": "miso, bean paste"
  },
  {
    "id": "n4-0288",
    "jp": "お祝い",
    "reading": "おいわい",
    "romaji": "oiwai",
    "meaning": "congratulation, celebration"
  },
  {
    "id": "n4-0289",
    "jp": "乗り物",
    "reading": "のりもの",
    "romaji": "norimono",
    "meaning": "vehicle"
  },
  {
    "id": "n4-0290",
    "jp": "案内",
    "reading": "あんないする",
    "romaji": "annaisuru",
    "meaning": "information, guidance"
  },
  {
    "id": "n4-0291",
    "jp": "通う",
    "reading": "かよう",
    "romaji": "kayou",
    "meaning": "to go back and forth; to commute"
  },
  {
    "id": "n4-0292",
    "jp": "連れる",
    "reading": "つれる",
    "romaji": "tsureru",
    "meaning": "to lead, to take (a person)"
  },
  {
    "id": "n4-0293",
    "jp": "技術",
    "reading": "ぎじゅつ",
    "romaji": "gijutsu",
    "meaning": "technique, technology, skill"
  },
  {
    "id": "n4-0294",
    "jp": "小鳥",
    "reading": "ことり",
    "romaji": "kotori",
    "meaning": "small bird"
  },
  {
    "id": "n4-0295",
    "jp": "下宿",
    "reading": "げしゅく",
    "romaji": "geshuku",
    "meaning": "lodging, boarding house"
  },
  {
    "id": "n4-0296",
    "jp": "ジャム",
    "reading": "ジャム",
    "romaji": "ジャム",
    "meaning": "jam"
  },
  {
    "id": "n4-0297",
    "jp": "招待",
    "reading": "しょうたいする",
    "romaji": "shoutaisuru",
    "meaning": "invitation"
  },
  {
    "id": "n4-0298",
    "jp": "鏡",
    "reading": "かがみ",
    "romaji": "kagami",
    "meaning": "mirror"
  },
  {
    "id": "n4-0299",
    "jp": "はず",
    "reading": "はず",
    "romaji": "hazu",
    "meaning": "it should be so"
  },
  {
    "id": "n4-0300",
    "jp": "法律",
    "reading": "ほうりつ",
    "romaji": "houritsu",
    "meaning": "law"
  },
  {
    "id": "n4-0301",
    "jp": "進む",
    "reading": "すすむ",
    "romaji": "susumu",
    "meaning": "to advance, to proceed"
  },
  {
    "id": "n4-0302",
    "jp": "楽む",
    "reading": "たのしむ",
    "romaji": "tanoshimu",
    "meaning": "to enjoy"
  },
  {
    "id": "n4-0303",
    "jp": "貿易",
    "reading": "ぼうえき",
    "romaji": "boueki",
    "meaning": "trade"
  },
  {
    "id": "n4-0304",
    "jp": "反対",
    "reading": "はんたい",
    "romaji": "hantai",
    "meaning": "oppose, opposition, resistance"
  },
  {
    "id": "n4-0305",
    "jp": "おる",
    "reading": "おる",
    "romaji": "oru",
    "meaning": "-- extra-modest expression for いる --"
  },
  {
    "id": "n4-0306",
    "jp": "申す",
    "reading": "もうす",
    "romaji": "mousu",
    "meaning": "-- extra-modest (humble) expression for 言う (いう) --"
  },
  {
    "id": "n4-0307",
    "jp": "試験",
    "reading": "しけん",
    "romaji": "shiken",
    "meaning": "an exam"
  },
  {
    "id": "n4-0308",
    "jp": "真面目",
    "reading": "まじめ",
    "romaji": "majime",
    "meaning": "diligent, serious"
  },
  {
    "id": "n4-0309",
    "jp": "店員",
    "reading": "てんいん",
    "romaji": "ten'in",
    "meaning": "clerk; shop-employee"
  },
  {
    "id": "n4-0310",
    "jp": "泊まる",
    "reading": "とまる",
    "romaji": "tomaru",
    "meaning": "to stay (over night) (v.i.)"
  },
  {
    "id": "n4-0311",
    "jp": "よろしい",
    "reading": "よろしい",
    "romaji": "yoroshii",
    "meaning": "(hon.) good, OK, all right"
  },
  {
    "id": "n4-0312",
    "jp": "今夜",
    "reading": "こんや",
    "romaji": "kon'ya",
    "meaning": "this evening, tonight"
  },
  {
    "id": "n4-0313",
    "jp": "おつり",
    "reading": "おつり",
    "romaji": "otsuri",
    "meaning": "change; balance of money returned to the purchaser"
  },
  {
    "id": "n4-0314",
    "jp": "チェックする",
    "reading": "チェックする",
    "romaji": "チェックsuru",
    "meaning": "check"
  },
  {
    "id": "n4-0315",
    "jp": "会話",
    "reading": "かいわ",
    "romaji": "kaiwa",
    "meaning": "conversation"
  },
  {
    "id": "n4-0316",
    "jp": "空気",
    "reading": "くうき",
    "romaji": "kuuki",
    "meaning": "air, atmosphere"
  },
  {
    "id": "n4-0317",
    "jp": "交通",
    "reading": "こうつう",
    "romaji": "koutsuu",
    "meaning": "traffic, transportation"
  },
  {
    "id": "n4-0318",
    "jp": "ワープロ",
    "reading": "ワープロ",
    "romaji": "ワープロ",
    "meaning": "word processor"
  },
  {
    "id": "n4-0319",
    "jp": "喜ぶ",
    "reading": "よろこぶ",
    "romaji": "yorokobu",
    "meaning": "to rejoice, to be delighted, to be glad"
  },
  {
    "id": "n4-0320",
    "jp": "急行",
    "reading": "きゅうこう",
    "romaji": "kyuukou",
    "meaning": "express train or bus"
  },
  {
    "id": "n4-0321",
    "jp": "皆",
    "reading": "みな",
    "romaji": "mina",
    "meaning": "everyone"
  },
  {
    "id": "n4-0322",
    "jp": "味",
    "reading": "あじ",
    "romaji": "aji",
    "meaning": "flavor, taste"
  },
  {
    "id": "n4-0323",
    "jp": "空港",
    "reading": "くうこう",
    "romaji": "kuukou",
    "meaning": "airport"
  },
  {
    "id": "n4-0324",
    "jp": "手袋",
    "reading": "てぶくろ",
    "romaji": "tebukuro",
    "meaning": "glove(s)"
  },
  {
    "id": "n4-0325",
    "jp": "校長",
    "reading": "こうちょう",
    "romaji": "kouchou",
    "meaning": "principal, headmaster"
  },
  {
    "id": "n4-0326",
    "jp": "ごちそう",
    "reading": "ごちそう",
    "romaji": "gochisou",
    "meaning": "feast, treating (someone)"
  },
  {
    "id": "n4-0327",
    "jp": "踊り",
    "reading": "おどり",
    "romaji": "odori",
    "meaning": "dance"
  },
  {
    "id": "n4-0328",
    "jp": "興味",
    "reading": "きょうみ",
    "romaji": "kyoumi",
    "meaning": "interest (in something)"
  },
  {
    "id": "n4-0329",
    "jp": "引っ越す",
    "reading": "ひっこす",
    "romaji": "hikkosu",
    "meaning": "to move to a new place of residence"
  },
  {
    "id": "n4-0330",
    "jp": "冷房",
    "reading": "れいぼう",
    "romaji": "reibou",
    "meaning": "cooling, air conditioning"
  },
  {
    "id": "n4-0331",
    "jp": "都合",
    "reading": "つごう",
    "romaji": "tsugou",
    "meaning": "circumstances, convenience"
  },
  {
    "id": "n4-0332",
    "jp": "遠慮",
    "reading": "えんりょする",
    "romaji": "enryosuru",
    "meaning": "restraint, reserve, hesitate"
  },
  {
    "id": "n4-0333",
    "jp": "亡くなる",
    "reading": "なくなる",
    "romaji": "nakunaru",
    "meaning": "to pass away"
  },
  {
    "id": "n4-0334",
    "jp": "科学",
    "reading": "かがく",
    "romaji": "kagaku",
    "meaning": "science"
  },
  {
    "id": "n4-0335",
    "jp": "はっきり",
    "reading": "はっきり",
    "romaji": "hakkiri",
    "meaning": "clearly, distinctly"
  },
  {
    "id": "n4-0336",
    "jp": "差し上げる",
    "reading": "さしあげる",
    "romaji": "sashiageru",
    "meaning": "-- humble expression for あげる --"
  },
  {
    "id": "n4-0337",
    "jp": "気持ち",
    "reading": "きもち",
    "romaji": "kimochi",
    "meaning": "feeling, sensation, mood"
  },
  {
    "id": "n4-0338",
    "jp": "祖父",
    "reading": "そふ",
    "romaji": "sofu",
    "meaning": "grandfather"
  },
  {
    "id": "n4-0339",
    "jp": "港",
    "reading": "みなと",
    "romaji": "minato",
    "meaning": "harbor, port"
  },
  {
    "id": "n4-0340",
    "jp": "予約",
    "reading": "よやく",
    "romaji": "yoyaku",
    "meaning": "reservation"
  },
  {
    "id": "n4-0341",
    "jp": "凄い",
    "reading": "すごい",
    "romaji": "sugoi",
    "meaning": "terrific, great"
  },
  {
    "id": "n4-0342",
    "jp": "入学",
    "reading": "にゅうがくする",
    "romaji": "nyuugakusuru",
    "meaning": "entry to school or university"
  },
  {
    "id": "n4-0343",
    "jp": "片付ける",
    "reading": "かたづける",
    "romaji": "katazukeru",
    "meaning": "to (clean) tidy up (v.t.), to put away"
  },
  {
    "id": "n4-0344",
    "jp": "写す",
    "reading": "うつす",
    "romaji": "utsusu",
    "meaning": "to copy (v.t.); to photograph"
  },
  {
    "id": "n4-0345",
    "jp": "パソコン",
    "reading": "パソコン",
    "romaji": "パソコン",
    "meaning": "(personal) computer"
  },
  {
    "id": "n4-0346",
    "jp": "部長",
    "reading": "ぶちょう",
    "romaji": "buchou",
    "meaning": "department (division) manager"
  },
  {
    "id": "n4-0347",
    "jp": "火事",
    "reading": "かじ",
    "romaji": "kaji",
    "meaning": "fire"
  },
  {
    "id": "n4-0348",
    "jp": "足す",
    "reading": "たす",
    "romaji": "tasu",
    "meaning": "to add (numbers)"
  },
  {
    "id": "n4-0349",
    "jp": "教会",
    "reading": "きょうかい",
    "romaji": "kyoukai",
    "meaning": "church"
  },
  {
    "id": "n4-0350",
    "jp": "彼ら",
    "reading": "かれら",
    "romaji": "karera",
    "meaning": "they (usually male)"
  },
  {
    "id": "n4-0351",
    "jp": "いっぱい",
    "reading": "一杯",
    "romaji": "一杯",
    "meaning": "full, to the utmost"
  },
  {
    "id": "n4-0352",
    "jp": "アメリカ",
    "reading": "アメリカ",
    "romaji": "アメリカ",
    "meaning": "America, U.S.A."
  },
  {
    "id": "n4-0353",
    "jp": "男性",
    "reading": "だんせい",
    "romaji": "dansei",
    "meaning": "man; male"
  },
  {
    "id": "n4-0354",
    "jp": "理由",
    "reading": "りゆう",
    "romaji": "riyuu",
    "meaning": "reason"
  },
  {
    "id": "n4-0355",
    "jp": "生産",
    "reading": "せいさんする",
    "romaji": "seisansuru",
    "meaning": "production; to produce"
  },
  {
    "id": "n4-0356",
    "jp": "着物",
    "reading": "きもの",
    "romaji": "kimono",
    "meaning": "kimono; Japanese traditional dress"
  },
  {
    "id": "n4-0357",
    "jp": "おもちゃ",
    "reading": "おもちゃ",
    "romaji": "omocha",
    "meaning": "a toy"
  },
  {
    "id": "n4-0358",
    "jp": "暮れる",
    "reading": "くれる",
    "romaji": "kureru",
    "meaning": "to get dark, to come to an end"
  },
  {
    "id": "n4-0359",
    "jp": "釣る",
    "reading": "つる",
    "romaji": "tsuru",
    "meaning": "to fish"
  },
  {
    "id": "n4-0360",
    "jp": "～ちゃん",
    "reading": "～ちゃん",
    "romaji": "～chan",
    "meaning": "suffix for familiar (female) person"
  },
  {
    "id": "n4-0361",
    "jp": "打つ",
    "reading": "うつ",
    "romaji": "utsu",
    "meaning": "to hit, to strike"
  },
  {
    "id": "n4-0362",
    "jp": "あんな",
    "reading": "あんな",
    "romaji": "anna",
    "meaning": "such, like that"
  },
  {
    "id": "n4-0363",
    "jp": "謝る",
    "reading": "あやまる",
    "romaji": "ayamaru",
    "meaning": "to apologize"
  },
  {
    "id": "n4-0364",
    "jp": "昼間",
    "reading": "ひるま",
    "romaji": "hiruma",
    "meaning": "daytime, during the day"
  },
  {
    "id": "n4-0365",
    "jp": "教育",
    "reading": "きょういく",
    "romaji": "kyouiku",
    "meaning": "education"
  },
  {
    "id": "n4-0366",
    "jp": "女性",
    "reading": "じょせい",
    "romaji": "josei",
    "meaning": "woman"
  },
  {
    "id": "n4-0367",
    "jp": "米",
    "reading": "こめ",
    "romaji": "kome",
    "meaning": "uncooked rice"
  },
  {
    "id": "n4-0368",
    "jp": "邪魔",
    "reading": "じゃま",
    "romaji": "jama",
    "meaning": "hindrance, intrusion"
  },
  {
    "id": "n4-0369",
    "jp": "国際",
    "reading": "こくさい",
    "romaji": "kokusai",
    "meaning": "international"
  },
  {
    "id": "n4-0370",
    "jp": "隅",
    "reading": "すみ",
    "romaji": "sumi",
    "meaning": "corner"
  },
  {
    "id": "n4-0371",
    "jp": "伺う",
    "reading": "うかがう",
    "romaji": "ukagau",
    "meaning": "humble form of 行く (いく), 聞く (きく) and 来る (くる)"
  },
  {
    "id": "n4-0372",
    "jp": "再来週",
    "reading": "さらいしゅう",
    "romaji": "saraishuu",
    "meaning": "the week after next"
  },
  {
    "id": "n4-0373",
    "jp": "夢",
    "reading": "ゆめ",
    "romaji": "yume",
    "meaning": "a dream"
  },
  {
    "id": "n4-0374",
    "jp": "喉",
    "reading": "のど",
    "romaji": "nodo",
    "meaning": "throat"
  },
  {
    "id": "n4-0375",
    "jp": "最近",
    "reading": "さいきん",
    "romaji": "saikin",
    "meaning": "recently, nowadays, in recent years, most recent, latest"
  },
  {
    "id": "n4-0376",
    "jp": "周り",
    "reading": "まわり",
    "romaji": "mawari",
    "meaning": "surroundings"
  },
  {
    "id": "n4-0377",
    "jp": "歴史",
    "reading": "れきし",
    "romaji": "rekishi",
    "meaning": "history"
  },
  {
    "id": "n4-0378",
    "jp": "不便",
    "reading": "ふべん",
    "romaji": "fuben",
    "meaning": "inconvenience"
  },
  {
    "id": "n4-0379",
    "jp": "血",
    "reading": "ち",
    "romaji": "chi",
    "meaning": "blood"
  },
  {
    "id": "n4-0380",
    "jp": "～続ける",
    "reading": "～つづける",
    "romaji": "～tsuzukeru",
    "meaning": "to continue doing ~"
  },
  {
    "id": "n4-0381",
    "jp": "毛",
    "reading": "け",
    "romaji": "ke",
    "meaning": "hair, fur"
  },
  {
    "id": "n4-0382",
    "jp": "ひどい",
    "reading": "ひどい",
    "romaji": "hidoi",
    "meaning": "terrible, awful, unfair, cruel"
  },
  {
    "id": "n4-0383",
    "jp": "例えば",
    "reading": "たとえば",
    "romaji": "tatoeba",
    "meaning": "for example, e.g."
  },
  {
    "id": "n4-0384",
    "jp": "中々",
    "reading": "なかなか",
    "romaji": "nakanaka",
    "meaning": "very, considerably, quite"
  },
  {
    "id": "n4-0385",
    "jp": "随分",
    "reading": "ずいぶん",
    "romaji": "zuibun",
    "meaning": "extremely"
  },
  {
    "id": "n4-0386",
    "jp": "～やすい",
    "reading": "～やすい",
    "romaji": "～yasui",
    "meaning": "easy to do ~"
  },
  {
    "id": "n4-0387",
    "jp": "押し入れ",
    "reading": "おしいれ",
    "romaji": "oshiire",
    "meaning": "closet"
  },
  {
    "id": "n4-0388",
    "jp": "電灯",
    "reading": "でんとう",
    "romaji": "dentou",
    "meaning": "electric light"
  },
  {
    "id": "n4-0389",
    "jp": "叱る",
    "reading": "しかる",
    "romaji": "shikaru",
    "meaning": "to scold"
  },
  {
    "id": "n4-0390",
    "jp": "サンダル",
    "reading": "サンダル",
    "romaji": "サンダル",
    "meaning": "sandal"
  },
  {
    "id": "n4-0391",
    "jp": "びっくりする",
    "reading": "びっくりする",
    "romaji": "bikkurisuru",
    "meaning": "to be surprised"
  },
  {
    "id": "n4-0392",
    "jp": "うまい",
    "reading": "うまい",
    "romaji": "umai",
    "meaning": "delicious; skillful; fortunate"
  },
  {
    "id": "n4-0393",
    "jp": "変える",
    "reading": "かえる",
    "romaji": "kaeru",
    "meaning": "to change, to alter, to vary"
  },
  {
    "id": "n4-0394",
    "jp": "講堂",
    "reading": "こうどう",
    "romaji": "koudou",
    "meaning": "auditorium"
  },
  {
    "id": "n4-0395",
    "jp": "子",
    "reading": "こ",
    "romaji": "ko",
    "meaning": "child"
  },
  {
    "id": "n4-0396",
    "jp": "沸かす",
    "reading": "わかす",
    "romaji": "wakasu",
    "meaning": "to boil"
  },
  {
    "id": "n4-0397",
    "jp": "レジ",
    "reading": "レジ",
    "romaji": "レジ",
    "meaning": "register"
  },
  {
    "id": "n4-0398",
    "jp": "しばらく",
    "reading": "しばらく",
    "romaji": "shibaraku",
    "meaning": "little while"
  },
  {
    "id": "n4-0399",
    "jp": "特に",
    "reading": "とくに",
    "romaji": "tokuni",
    "meaning": "particularly"
  },
  {
    "id": "n4-0400",
    "jp": "空く",
    "reading": "あく",
    "romaji": "aku",
    "meaning": "to open, to become empty (vacant)"
  },
  {
    "id": "n4-0401",
    "jp": "計画",
    "reading": "けいかくする",
    "romaji": "keikakusuru",
    "meaning": "plan, project, schedule"
  },
  {
    "id": "n4-0402",
    "jp": "通り",
    "reading": "とおり",
    "romaji": "toori",
    "meaning": "~ Street, ~ Avenue"
  },
  {
    "id": "n4-0403",
    "jp": "下着",
    "reading": "したぎ",
    "romaji": "shitagi",
    "meaning": "underwear"
  },
  {
    "id": "n4-0404",
    "jp": "経済",
    "reading": "けいざい",
    "romaji": "keizai",
    "meaning": "economics, finance, economy"
  },
  {
    "id": "n4-0405",
    "jp": "こう",
    "reading": "こう",
    "romaji": "kou",
    "meaning": "like this, this way"
  },
  {
    "id": "n4-0406",
    "jp": "是非",
    "reading": "ぜひ",
    "romaji": "zehi",
    "meaning": "certainly, by all means; without fail"
  },
  {
    "id": "n4-0407",
    "jp": "裏",
    "reading": "うら",
    "romaji": "ura",
    "meaning": "reverse side, back"
  },
  {
    "id": "n4-0408",
    "jp": "為",
    "reading": "ため",
    "romaji": "tame",
    "meaning": "good, advantage, in order to"
  },
  {
    "id": "n4-0409",
    "jp": "おいでになる",
    "reading": "おいでになる",
    "romaji": "oideninaru",
    "meaning": "(hon.) to be"
  },
  {
    "id": "n4-0410",
    "jp": "変わる",
    "reading": "かわる",
    "romaji": "kawaru",
    "meaning": "to change (v.i.), to be transformed, to vary"
  },
  {
    "id": "n4-0411",
    "jp": "以外",
    "reading": "いがい",
    "romaji": "igai",
    "meaning": "other than, with the exception of, excepting"
  },
  {
    "id": "n4-0412",
    "jp": "済む",
    "reading": "すむ",
    "romaji": "sumu",
    "meaning": "to finish, to end"
  },
  {
    "id": "n4-0413",
    "jp": "ハンバーグ",
    "reading": "ハンバーグ",
    "romaji": "ハンバーグ",
    "meaning": "hamburger steak"
  },
  {
    "id": "n4-0414",
    "jp": "市",
    "reading": "し",
    "romaji": "shi",
    "meaning": "city"
  },
  {
    "id": "n4-0415",
    "jp": "引き出し",
    "reading": "ひきだし",
    "romaji": "hikidashi",
    "meaning": "drawer"
  },
  {
    "id": "n4-0416",
    "jp": "遊び",
    "reading": "あそび",
    "romaji": "asobi",
    "meaning": "play"
  },
  {
    "id": "n4-0417",
    "jp": "支度",
    "reading": "したくする",
    "romaji": "shitakusuru",
    "meaning": "preparation"
  },
  {
    "id": "n4-0418",
    "jp": "～始める",
    "reading": "～はじめる",
    "romaji": "～hajimeru",
    "meaning": "to start doing ~"
  },
  {
    "id": "n4-0419",
    "jp": "見える",
    "reading": "みえる",
    "romaji": "mieru",
    "meaning": "to be visible; -- polite verb meaning 来る (くる) --"
  },
  {
    "id": "n4-0420",
    "jp": "十分",
    "reading": "じゅうぶん",
    "romaji": "juubun",
    "meaning": "enough"
  },
  {
    "id": "n4-0421",
    "jp": "音",
    "reading": "おと",
    "romaji": "oto",
    "meaning": "sound, note"
  },
  {
    "id": "n4-0422",
    "jp": "きっと",
    "reading": "きっと",
    "romaji": "kitto",
    "meaning": "surely, definitely, undoubtedly, certainly"
  },
  {
    "id": "n4-0423",
    "jp": "まず",
    "reading": "まず",
    "romaji": "mazu",
    "meaning": "first (of all), to start with"
  },
  {
    "id": "n4-0424",
    "jp": "遠く",
    "reading": "とおく",
    "romaji": "tooku",
    "meaning": "far away, distant"
  },
  {
    "id": "n4-0425",
    "jp": "大体",
    "reading": "だいたい",
    "romaji": "daitai",
    "meaning": "approximately; in most cases; in general; to begin with (same as もともと)"
  },
  {
    "id": "n4-0426",
    "jp": "折れる",
    "reading": "おれる",
    "romaji": "oreru",
    "meaning": "to break, to be folded, to give in; to turn (a corner)"
  },
  {
    "id": "n4-0427",
    "jp": "正しい",
    "reading": "ただしい",
    "romaji": "tadashii",
    "meaning": "correct"
  },
  {
    "id": "n4-0428",
    "jp": "輸入",
    "reading": "ゆにゅう",
    "romaji": "yunyuu",
    "meaning": "import"
  },
  {
    "id": "n4-0429",
    "jp": "返事",
    "reading": "へんじ",
    "romaji": "henji",
    "meaning": "reply, answer"
  },
  {
    "id": "n4-0430",
    "jp": "都",
    "reading": "と",
    "romaji": "to",
    "meaning": "metropolitan"
  },
  {
    "id": "n4-0431",
    "jp": "産業",
    "reading": "さんぎょう",
    "romaji": "sangyou",
    "meaning": "industry"
  },
  {
    "id": "n4-0432",
    "jp": "伝える",
    "reading": "つたえる",
    "romaji": "tsutaeru",
    "meaning": "to convey (a message); to tell, to report"
  },
  {
    "id": "n4-0433",
    "jp": "お金持ち",
    "reading": "かねもち; おかねもち",
    "romaji": "kanemochi; okanemochi",
    "meaning": "rich person"
  },
  {
    "id": "n4-0434",
    "jp": "説明",
    "reading": "せつめい",
    "romaji": "setsumei",
    "meaning": "explanation"
  },
  {
    "id": "n4-0435",
    "jp": "島",
    "reading": "しま",
    "romaji": "shima",
    "meaning": "island"
  },
  {
    "id": "n4-0436",
    "jp": "道具",
    "reading": "どうぐ",
    "romaji": "dougu",
    "meaning": "tool"
  },
  {
    "id": "n4-0437",
    "jp": "滑る",
    "reading": "すべる",
    "romaji": "suberu",
    "meaning": "to slide, to slip"
  },
  {
    "id": "n4-0438",
    "jp": "それほど",
    "reading": "それほど",
    "romaji": "sorehodo",
    "meaning": "to that degree; extent"
  },
  {
    "id": "n4-0439",
    "jp": "以上",
    "reading": "いじょう",
    "romaji": "ijou",
    "meaning": "more than; this is all"
  },
  {
    "id": "n4-0440",
    "jp": "～まま",
    "reading": "～まま",
    "romaji": "～mama",
    "meaning": "as it is"
  },
  {
    "id": "n4-0441",
    "jp": "特急",
    "reading": "とっきゅう",
    "romaji": "tokkyuu",
    "meaning": "limited express (train faster than an express)"
  },
  {
    "id": "n4-0442",
    "jp": "プレゼント",
    "reading": "プレゼント",
    "romaji": "プレゼント",
    "meaning": "present, gift"
  },
  {
    "id": "n4-0443",
    "jp": "～(に) よると",
    "reading": "～(に) よると",
    "romaji": "～(ni) yoruto",
    "meaning": "according to ~"
  },
  {
    "id": "n4-0444",
    "jp": "妻",
    "reading": "つま",
    "romaji": "tsuma",
    "meaning": "wife (humble)"
  },
  {
    "id": "n4-0445",
    "jp": "帰り",
    "reading": "かえり",
    "romaji": "kaeri",
    "meaning": "return, coming back"
  },
  {
    "id": "n4-0446",
    "jp": "具合",
    "reading": "ぐあい",
    "romaji": "guai",
    "meaning": "condition, state, health"
  },
  {
    "id": "n4-0447",
    "jp": "堅; 硬; 固い",
    "reading": "かたい",
    "romaji": "katai",
    "meaning": "solid, hard, firm"
  },
  {
    "id": "n4-0448",
    "jp": "駐車場",
    "reading": "ちゅうしゃじょう",
    "romaji": "chuushajou",
    "meaning": "parking lot"
  },
  {
    "id": "n4-0449",
    "jp": "スーツ",
    "reading": "スーツ",
    "romaji": "スーツ",
    "meaning": "suit"
  },
  {
    "id": "n4-0450",
    "jp": "危険",
    "reading": "きけん",
    "romaji": "kiken",
    "meaning": "danger, risk, hazard"
  },
  {
    "id": "n4-0451",
    "jp": "髪",
    "reading": "かみ",
    "romaji": "kami",
    "meaning": "hair"
  },
  {
    "id": "n4-0452",
    "jp": "天気予報",
    "reading": "てんきよほう",
    "romaji": "tenkiyohou",
    "meaning": "weather forecast"
  },
  {
    "id": "n4-0453",
    "jp": "彼女",
    "reading": "かのじょ",
    "romaji": "kanojo",
    "meaning": "girlfriend; she"
  },
  {
    "id": "n4-0454",
    "jp": "間",
    "reading": "あいだ",
    "romaji": "aida",
    "meaning": "space, interval"
  },
  {
    "id": "n4-0455",
    "jp": "卒業",
    "reading": "そつぎょう",
    "romaji": "sotsugyou",
    "meaning": "graduation"
  },
  {
    "id": "n4-0456",
    "jp": "それで",
    "reading": "それで",
    "romaji": "sorede",
    "meaning": "and (conj.), thereupon, because of that"
  },
  {
    "id": "n4-0457",
    "jp": "枝",
    "reading": "えだ",
    "romaji": "eda",
    "meaning": "branch, twig"
  },
  {
    "id": "n4-0458",
    "jp": "専門",
    "reading": "せんもん",
    "romaji": "senmon",
    "meaning": "major; speciality"
  },
  {
    "id": "n4-0459",
    "jp": "そろそろ",
    "reading": "そろそろ",
    "romaji": "sorosoro",
    "meaning": "gradually, soon"
  },
  {
    "id": "n4-0460",
    "jp": "送る",
    "reading": "おくる",
    "romaji": "okuru",
    "meaning": "to send, to dispatch"
  },
  {
    "id": "n4-0461",
    "jp": "あげる",
    "reading": "あげる",
    "romaji": "ageru",
    "meaning": "to give"
  },
  {
    "id": "n4-0462",
    "jp": "騒ぐ",
    "reading": "さわぐ",
    "romaji": "sawagu",
    "meaning": "to make noise, to clamor"
  },
  {
    "id": "n4-0463",
    "jp": "尋ねる",
    "reading": "たずねる",
    "romaji": "tazuneru",
    "meaning": "to inquire (same as 質問する)"
  },
  {
    "id": "n4-0464",
    "jp": "放送",
    "reading": "ほうそうする",
    "romaji": "housousuru",
    "meaning": "broadcasting"
  },
  {
    "id": "n4-0465",
    "jp": "政治",
    "reading": "せいじ",
    "romaji": "seiji",
    "meaning": "politics"
  },
  {
    "id": "n4-0466",
    "jp": "市民",
    "reading": "しみん",
    "romaji": "shimin",
    "meaning": "citizen"
  },
  {
    "id": "n4-0467",
    "jp": "ファックス",
    "reading": "ファックス",
    "romaji": "ファックス",
    "meaning": "fax"
  },
  {
    "id": "n4-0468",
    "jp": "負ける",
    "reading": "まける",
    "romaji": "makeru",
    "meaning": "to lose (a game) (v.i.), to be defeated"
  },
  {
    "id": "n4-0469",
    "jp": "指輪",
    "reading": "ゆびわ",
    "romaji": "yubiwa",
    "meaning": "(finger) ring"
  },
  {
    "id": "n4-0470",
    "jp": "田舎",
    "reading": "いなか",
    "romaji": "inaka",
    "meaning": "rural, countryside"
  },
  {
    "id": "n4-0471",
    "jp": "見つける",
    "reading": "みつける",
    "romaji": "mitsukeru",
    "meaning": "to discover, to find (v.t.)"
  },
  {
    "id": "n4-0472",
    "jp": "高校生",
    "reading": "こうこうせい",
    "romaji": "koukousei",
    "meaning": "high school student"
  },
  {
    "id": "n4-0473",
    "jp": "講義",
    "reading": "こうぎ",
    "romaji": "kougi",
    "meaning": "a lecture"
  },
  {
    "id": "n4-0474",
    "jp": "そんなに",
    "reading": "そんなに",
    "romaji": "sonnani",
    "meaning": "so much, like that"
  },
  {
    "id": "n4-0475",
    "jp": "昼休み",
    "reading": "ひるやすみ",
    "romaji": "hiruyasumi",
    "meaning": "lunch break, noon recess"
  },
  {
    "id": "n4-0476",
    "jp": "忘れ物",
    "reading": "わすれもの",
    "romaji": "wasuremono",
    "meaning": "lost article, something forgotten"
  },
  {
    "id": "n4-0477",
    "jp": "下りる",
    "reading": "おりる",
    "romaji": "oriru",
    "meaning": "to get down, to go; come down"
  },
  {
    "id": "n4-0478",
    "jp": "腕",
    "reading": "うで",
    "romaji": "ude",
    "meaning": "arm (in reference to body)"
  },
  {
    "id": "n4-0479",
    "jp": "訳",
    "reading": "わけ",
    "romaji": "wake",
    "meaning": "reason; explanation"
  },
  {
    "id": "n4-0480",
    "jp": "承知",
    "reading": "しょうちする",
    "romaji": "shouchisuru",
    "meaning": "consent, acceptance"
  },
  {
    "id": "n4-0481",
    "jp": "日記",
    "reading": "にっき",
    "romaji": "nikki",
    "meaning": "diary, journal"
  },
  {
    "id": "n4-0482",
    "jp": "高校; 高等学校",
    "reading": "こうこう; こうとうがっこう",
    "romaji": "koukou; koutougakkou",
    "meaning": "high school; senior high school"
  },
  {
    "id": "n4-0483",
    "jp": "似る",
    "reading": "にる",
    "romaji": "niru",
    "meaning": "to resemble, to be similar"
  },
  {
    "id": "n4-0484",
    "jp": "～おわる",
    "reading": "～おわる",
    "romaji": "～owaru",
    "meaning": "to finish doing ~"
  },
  {
    "id": "n4-0485",
    "jp": "暖房",
    "reading": "だんぼう",
    "romaji": "danbou",
    "meaning": "heating"
  },
  {
    "id": "n4-0486",
    "jp": "留守",
    "reading": "るす",
    "romaji": "rusu",
    "meaning": "absence; not at home"
  },
  {
    "id": "n4-0487",
    "jp": "割合",
    "reading": "わりあい",
    "romaji": "wariai",
    "meaning": "rate, ratio, percentage"
  },
  {
    "id": "n4-0488",
    "jp": "寺",
    "reading": "てら",
    "romaji": "tera",
    "meaning": "Buddhist temple"
  },
  {
    "id": "n4-0489",
    "jp": "慣れる",
    "reading": "なれる",
    "romaji": "nareru",
    "meaning": "to grow accustomed to"
  },
  {
    "id": "n4-0490",
    "jp": "普通",
    "reading": "ふつう",
    "romaji": "futsuu",
    "meaning": "common; usual"
  },
  {
    "id": "n4-0491",
    "jp": "手伝う",
    "reading": "てつだう",
    "romaji": "tetsudau",
    "meaning": "to help"
  },
  {
    "id": "n4-0492",
    "jp": "なるほど",
    "reading": "なるほど",
    "romaji": "naruhodo",
    "meaning": "I see; I now understand"
  },
  {
    "id": "n4-0493",
    "jp": "くださる",
    "reading": "くださる",
    "romaji": "kudasaru",
    "meaning": "(hon.) to give, to confer"
  },
  {
    "id": "n4-0494",
    "jp": "息子",
    "reading": "むすこ",
    "romaji": "musuko",
    "meaning": "(humble) son"
  },
  {
    "id": "n4-0495",
    "jp": "お子さん",
    "reading": "おこさん",
    "romaji": "okosan",
    "meaning": "(someone else's) child (polite)"
  },
  {
    "id": "n4-0496",
    "jp": "会場",
    "reading": "かいじょう",
    "romaji": "kaijou",
    "meaning": "venue, meeting place"
  },
  {
    "id": "n4-0497",
    "jp": "笑う",
    "reading": "わらう",
    "romaji": "warau",
    "meaning": "to laugh, to smile"
  },
  {
    "id": "n4-0498",
    "jp": "運ぶ",
    "reading": "はこぶ",
    "romaji": "hakobu",
    "meaning": "to transport, to carry"
  },
  {
    "id": "n4-0499",
    "jp": "文学",
    "reading": "ぶんがく",
    "romaji": "bungaku",
    "meaning": "literature"
  },
  {
    "id": "n4-0500",
    "jp": "光",
    "reading": "ひかり",
    "romaji": "hikari",
    "meaning": "light"
  },
  {
    "id": "n4-0501",
    "jp": "お見舞い",
    "reading": "おみまい",
    "romaji": "omimai",
    "meaning": "calling on someone who is ill, visit"
  },
  {
    "id": "n4-0502",
    "jp": "席",
    "reading": "せき",
    "romaji": "seki",
    "meaning": "a seat"
  },
  {
    "id": "n4-0503",
    "jp": "～様",
    "reading": "～さま",
    "romaji": "～sama",
    "meaning": "Mr., Mrs., Ms."
  },
  {
    "id": "n4-0504",
    "jp": "ご存じ",
    "reading": "ごぞんじ",
    "romaji": "gozonji",
    "meaning": "knowing, acquaintance"
  },
  {
    "id": "n4-0505",
    "jp": "下る",
    "reading": "さがる",
    "romaji": "sagaru",
    "meaning": "to descend, to drop, to fall"
  },
  {
    "id": "n4-0506",
    "jp": "字",
    "reading": "じ",
    "romaji": "ji",
    "meaning": "letter; character"
  },
  {
    "id": "n4-0507",
    "jp": "アジア",
    "reading": "アジア",
    "romaji": "アジア",
    "meaning": "Asia"
  },
  {
    "id": "n4-0508",
    "jp": "褒める",
    "reading": "ほめる",
    "romaji": "homeru",
    "meaning": "to praise; to say nice things"
  },
  {
    "id": "n4-0509",
    "jp": "空く",
    "reading": "すく",
    "romaji": "suku",
    "meaning": "to be empty (in reference to people), to be less crowded"
  },
  {
    "id": "n4-0510",
    "jp": "あ",
    "reading": "あ",
    "romaji": "a",
    "meaning": "Ah"
  },
  {
    "id": "n4-0511",
    "jp": "最も",
    "reading": "もっとも",
    "romaji": "mottomo",
    "meaning": "most"
  },
  {
    "id": "n4-0512",
    "jp": "合う",
    "reading": "あう",
    "romaji": "au",
    "meaning": "to fit, to match"
  },
  {
    "id": "n4-0513",
    "jp": "～代",
    "reading": "～だい",
    "romaji": "～dai",
    "meaning": "~ age; period"
  },
  {
    "id": "n4-0514",
    "jp": "最後",
    "reading": "さいご",
    "romaji": "saigo",
    "meaning": "last, end"
  },
  {
    "id": "n4-0515",
    "jp": "値段",
    "reading": "ねだん",
    "romaji": "nedan",
    "meaning": "price"
  },
  {
    "id": "n4-0516",
    "jp": "退院",
    "reading": "たいいんする",
    "romaji": "taiinsuru",
    "meaning": "leaving hospital"
  },
  {
    "id": "n4-0517",
    "jp": "展覧会",
    "reading": "てんらんかい",
    "romaji": "tenrankai",
    "meaning": "exhibition"
  },
  {
    "id": "n4-0518",
    "jp": "久しぶり",
    "reading": "ひさしぶり",
    "romaji": "hisashiburi",
    "meaning": "it has been a long time; for the first time in a long time"
  },
  {
    "id": "n4-0519",
    "jp": "カーテン",
    "reading": "カーテン",
    "romaji": "カーテン",
    "meaning": "curtain"
  },
  {
    "id": "n4-0520",
    "jp": "汽車",
    "reading": "きしゃ",
    "romaji": "kisha",
    "meaning": "train (steam)"
  },
  {
    "id": "n4-0521",
    "jp": "遅れる",
    "reading": "おくれる",
    "romaji": "okureru",
    "meaning": "to (be) become late"
  },
  {
    "id": "n4-0522",
    "jp": "見つかる",
    "reading": "みつかる",
    "romaji": "mitsukaru",
    "meaning": "to be found (v.i.), to be discovered"
  },
  {
    "id": "n4-0523",
    "jp": "召し上がる",
    "reading": "めしあがる",
    "romaji": "meshiagaru",
    "meaning": "-- honorific form of 食べる (たべる) and 飲む (のむ) --"
  },
  {
    "id": "n4-0524",
    "jp": "太る",
    "reading": "ふとる",
    "romaji": "futoru",
    "meaning": "to gain weight"
  },
  {
    "id": "n4-0525",
    "jp": "注射",
    "reading": "ちゅうしゃ",
    "romaji": "chuusha",
    "meaning": "injection"
  },
  {
    "id": "n4-0526",
    "jp": "様",
    "reading": "よう",
    "romaji": "you",
    "meaning": "way, manner, kind"
  },
  {
    "id": "n4-0527",
    "jp": "～おき",
    "reading": "～おき",
    "romaji": "～oki",
    "meaning": "after every ~"
  },
  {
    "id": "n4-0528",
    "jp": "最初",
    "reading": "さいしょ",
    "romaji": "saisho",
    "meaning": "beginning, first"
  },
  {
    "id": "n4-0529",
    "jp": "御～",
    "reading": "ご～",
    "romaji": "go～",
    "meaning": "honorable ~"
  },
  {
    "id": "n4-0530",
    "jp": "安心",
    "reading": "あんしん",
    "romaji": "anshin",
    "meaning": "peace of mind, relief"
  },
  {
    "id": "n4-0531",
    "jp": "直る",
    "reading": "なおる",
    "romaji": "naoru",
    "meaning": "to be fixed"
  },
  {
    "id": "n4-0532",
    "jp": "集める",
    "reading": "あつめる",
    "romaji": "atsumeru",
    "meaning": "to collect, to gather (v.t.), to assemble"
  },
  {
    "id": "n4-0533",
    "jp": "直す",
    "reading": "なおす",
    "romaji": "naosu",
    "meaning": "to correct (v.t.); to fix"
  },
  {
    "id": "n4-0534",
    "jp": "続く",
    "reading": "つづく",
    "romaji": "tsuzuku",
    "meaning": "to be continued"
  },
  {
    "id": "n4-0535",
    "jp": "先輩",
    "reading": "せんぱい",
    "romaji": "senpai",
    "meaning": "senior members of a group"
  },
  {
    "id": "n4-0536",
    "jp": "約束",
    "reading": "やくそく",
    "romaji": "yakusoku",
    "meaning": "arrangement, appointment, promise"
  },
  {
    "id": "n4-0537",
    "jp": "世話",
    "reading": "せわする",
    "romaji": "sewasuru",
    "meaning": "looking after; to look after"
  },
  {
    "id": "n4-0538",
    "jp": "近所",
    "reading": "きんじょ",
    "romaji": "kinjo",
    "meaning": "neighborhood"
  },
  {
    "id": "n4-0539",
    "jp": "将来",
    "reading": "しょうらい",
    "romaji": "shourai",
    "meaning": "(in the) future; prospects"
  },
  {
    "id": "n4-0540",
    "jp": "億",
    "reading": "おく",
    "romaji": "oku",
    "meaning": "hundred million"
  },
  {
    "id": "n4-0541",
    "jp": "数学",
    "reading": "すうがく",
    "romaji": "suugaku",
    "meaning": "mathematics"
  },
  {
    "id": "n4-0542",
    "jp": "文化",
    "reading": "ぶんか",
    "romaji": "bunka",
    "meaning": "culture"
  },
  {
    "id": "n4-0543",
    "jp": "払う",
    "reading": "はらう",
    "romaji": "harau",
    "meaning": "to pay"
  },
  {
    "id": "n4-0544",
    "jp": "習慣",
    "reading": "しゅうかん",
    "romaji": "shuukan",
    "meaning": "custom (in reference to culture)"
  },
  {
    "id": "n4-0545",
    "jp": "焼ける",
    "reading": "やける",
    "romaji": "yakeru",
    "meaning": "to burn, to be roasted"
  },
  {
    "id": "n4-0546",
    "jp": "君",
    "reading": "きみ",
    "romaji": "kimi",
    "meaning": "you (informal for men)"
  },
  {
    "id": "n4-0547",
    "jp": "冷える",
    "reading": "ひえる",
    "romaji": "hieru",
    "meaning": "to grow cold, to cool down"
  },
  {
    "id": "n4-0548",
    "jp": "点く",
    "reading": "つく",
    "romaji": "tsuku",
    "meaning": "to be started, to be switched on"
  },
  {
    "id": "n4-0549",
    "jp": "この間",
    "reading": "このあいだ",
    "romaji": "konoaida",
    "meaning": "the other day, recently"
  },
  {
    "id": "n4-0550",
    "jp": "かっこう",
    "reading": "格好",
    "romaji": "格好",
    "meaning": "appearance, manner, shape, form, posture"
  },
  {
    "id": "n4-0551",
    "jp": "続ける",
    "reading": "つづける",
    "romaji": "tsuzukeru",
    "meaning": "to continue, to keep up"
  },
  {
    "id": "n4-0552",
    "jp": "落す",
    "reading": "おとす",
    "romaji": "otosu",
    "meaning": "to drop, to lose"
  },
  {
    "id": "n4-0553",
    "jp": "明日",
    "reading": "あす",
    "romaji": "asu",
    "meaning": "tomorrow"
  },
  {
    "id": "n4-0554",
    "jp": "出発",
    "reading": "しゅっぱつする",
    "romaji": "shuppatsusuru",
    "meaning": "departure"
  },
  {
    "id": "n4-0555",
    "jp": "拝見",
    "reading": "はいけんする",
    "romaji": "haikensuru",
    "meaning": "(humble) (polite) seeing, look at"
  },
  {
    "id": "n4-0556",
    "jp": "割れる",
    "reading": "われる",
    "romaji": "wareru",
    "meaning": "to break"
  },
  {
    "id": "n4-0557",
    "jp": "背中",
    "reading": "せなか",
    "romaji": "senaka",
    "meaning": "back (of body)"
  },
  {
    "id": "n4-0558",
    "jp": "新聞社",
    "reading": "しんぶんしゃ",
    "romaji": "shinbunsha",
    "meaning": "newspaper company"
  },
  {
    "id": "n4-0559",
    "jp": "いじめる",
    "reading": "いじめる",
    "romaji": "ijimeru",
    "meaning": "to bully, to torment"
  },
  {
    "id": "n4-0560",
    "jp": "回る、回す",
    "reading": "まわる、まわす",
    "romaji": "mawaru、mawasu",
    "meaning": "to go around, to revolve"
  },
  {
    "id": "n4-0561",
    "jp": "～君",
    "reading": "～くん",
    "romaji": "～kun",
    "meaning": "Mr. (junior) ~, master ~"
  },
  {
    "id": "n4-0562",
    "jp": "おっしゃる",
    "reading": "おっしゃる",
    "romaji": "ossharu",
    "meaning": "-- honorific expression for いう --"
  },
  {
    "id": "n4-0563",
    "jp": "眠い",
    "reading": "ねむい",
    "romaji": "nemui",
    "meaning": "sleepy, drowsy"
  },
  {
    "id": "n4-0564",
    "jp": "濡れる",
    "reading": "ぬれる",
    "romaji": "nureru",
    "meaning": "to get wet"
  },
  {
    "id": "n4-0565",
    "jp": "倒れる",
    "reading": "たおれる",
    "romaji": "taoreru",
    "meaning": "to collapse, to break down"
  },
  {
    "id": "n4-0566",
    "jp": "スーパー (マーケット)",
    "reading": "スーパー (マーケット)",
    "romaji": "スーパー (マーケット)",
    "meaning": "supermarket"
  },
  {
    "id": "n4-0567",
    "jp": "アクセサリー",
    "reading": "アクセサリー",
    "romaji": "アクセサリー",
    "meaning": "accessory"
  },
  {
    "id": "n4-0568",
    "jp": "考える",
    "reading": "かんがえる",
    "romaji": "kangaeru",
    "meaning": "to think (about); to consider"
  },
  {
    "id": "n4-0569",
    "jp": "向かう",
    "reading": "むかう",
    "romaji": "mukau",
    "meaning": "to face, to go towards"
  },
  {
    "id": "n4-0570",
    "jp": "自由",
    "reading": "じゆう",
    "romaji": "jiyuu",
    "meaning": "freedom"
  },
  {
    "id": "n4-0571",
    "jp": "仕方",
    "reading": "しかた",
    "romaji": "shikata",
    "meaning": "way (of doing something)"
  },
  {
    "id": "n4-0572",
    "jp": "首",
    "reading": "くび",
    "romaji": "kubi",
    "meaning": "neck"
  },
  {
    "id": "n4-0573",
    "jp": "程",
    "reading": "ほど",
    "romaji": "hodo",
    "meaning": "degree, extent"
  },
  {
    "id": "n4-0574",
    "jp": "代わり",
    "reading": "かわり",
    "romaji": "kawari",
    "meaning": "substitute, replacement"
  },
  {
    "id": "n4-0575",
    "jp": "失敗",
    "reading": "しっぱい",
    "romaji": "shippai",
    "meaning": "failure, mistake"
  },
  {
    "id": "n4-0576",
    "jp": "工業",
    "reading": "こうぎょう",
    "romaji": "kougyou",
    "meaning": "(manufacturing) industry"
  },
  {
    "id": "n4-0577",
    "jp": "移る",
    "reading": "うつる",
    "romaji": "utsuru",
    "meaning": "to move (from a house); to transfer (from a department); to shift"
  },
  {
    "id": "n4-0578",
    "jp": "スーツケース",
    "reading": "スーツケース",
    "romaji": "スーツケース",
    "meaning": "suitcase"
  },
  {
    "id": "n4-0579",
    "jp": "ひげ",
    "reading": "ひげ",
    "romaji": "hige",
    "meaning": "beard"
  },
  {
    "id": "n4-0580",
    "jp": "研究室",
    "reading": "けんきゅうしつ",
    "romaji": "kenkyuushitsu",
    "meaning": "the professor's office; laboratory"
  },
  {
    "id": "n4-0581",
    "jp": "工場",
    "reading": "こうじょう",
    "romaji": "koujou",
    "meaning": "factory"
  },
  {
    "id": "n4-0582",
    "jp": "紹介",
    "reading": "しょうかい",
    "romaji": "shoukai",
    "meaning": "an introduction"
  },
  {
    "id": "n4-0583",
    "jp": "けれど; けれども",
    "reading": "けれど; けれども",
    "romaji": "keredo; keredomo",
    "meaning": "but, although"
  },
  {
    "id": "n4-0584",
    "jp": "舟",
    "reading": "ふね",
    "romaji": "fune",
    "meaning": "ship, boat"
  },
  {
    "id": "n4-0585",
    "jp": "動く",
    "reading": "うごく",
    "romaji": "ugoku",
    "meaning": "to move"
  },
  {
    "id": "n4-0586",
    "jp": "～(に) ついて",
    "reading": "～(に) ついて",
    "romaji": "～(ni) tsuite",
    "meaning": "about, concerning"
  },
  {
    "id": "n4-0587",
    "jp": "コンサート",
    "reading": "コンサート",
    "romaji": "コンサート",
    "meaning": "concert"
  },
  {
    "id": "n4-0588",
    "jp": "虫",
    "reading": "むし",
    "romaji": "mushi",
    "meaning": "insect"
  },
  {
    "id": "n4-0589",
    "jp": "優しい",
    "reading": "やさしい",
    "romaji": "yasashii",
    "meaning": "kind (person), gentle (person), easy (problem)"
  },
  {
    "id": "n4-0590",
    "jp": "コンピュータ; コンピューター",
    "reading": "コンピュータ; コンピューター",
    "romaji": "コンピュータ; コンピューター",
    "meaning": "computer"
  },
  {
    "id": "n4-0591",
    "jp": "植える",
    "reading": "うえる",
    "romaji": "ueru",
    "meaning": "to plant"
  },
  {
    "id": "n4-0592",
    "jp": "両方",
    "reading": "りょうほう",
    "romaji": "ryouhou",
    "meaning": "both sides, both parties"
  },
  {
    "id": "n4-0593",
    "jp": "汚れる",
    "reading": "よごれる",
    "romaji": "yogoreru",
    "meaning": "to become dirty"
  },
  {
    "id": "n4-0594",
    "jp": "水泳",
    "reading": "すいえい",
    "romaji": "suiei",
    "meaning": "swimming"
  },
  {
    "id": "n4-0595",
    "jp": "経験",
    "reading": "けいけんする",
    "romaji": "keikensuru",
    "meaning": "experience"
  },
  {
    "id": "n4-0596",
    "jp": "勝つ",
    "reading": "かつ",
    "romaji": "katsu",
    "meaning": "to win"
  },
  {
    "id": "n4-0597",
    "jp": "砂",
    "reading": "すな",
    "romaji": "suna",
    "meaning": "sand"
  },
  {
    "id": "n4-0598",
    "jp": "警察",
    "reading": "けいさつ",
    "romaji": "keisatsu",
    "meaning": "police; police station"
  },
  {
    "id": "n4-0599",
    "jp": "取り替える",
    "reading": "とりかえる",
    "romaji": "torikaeru",
    "meaning": "to exchange, to replace"
  },
  {
    "id": "n4-0600",
    "jp": "急ぐ",
    "reading": "いそぐ",
    "romaji": "isogu",
    "meaning": "to hurry, to be in a hurry, to rush"
  },
  {
    "id": "n4-0601",
    "jp": "簡単",
    "reading": "かんたん",
    "romaji": "kantan",
    "meaning": "simple"
  },
  {
    "id": "n4-0602",
    "jp": "参る",
    "reading": "まいる",
    "romaji": "mairu",
    "meaning": "humble expression for 行く and 来る"
  },
  {
    "id": "n4-0603",
    "jp": "全然",
    "reading": "ぜんぜん",
    "romaji": "zenzen",
    "meaning": "not at all; wholly, entirely"
  },
  {
    "id": "n4-0604",
    "jp": "特別",
    "reading": "とくべつ",
    "romaji": "tokubetsu",
    "meaning": "special"
  },
  {
    "id": "n4-0605",
    "jp": "復習",
    "reading": "ふくしゅう",
    "romaji": "fukushuu",
    "meaning": "review (of lessons), revision"
  },
  {
    "id": "n4-0606",
    "jp": "間に合う",
    "reading": "まにあう",
    "romaji": "maniau",
    "meaning": "to be in time for"
  },
  {
    "id": "n4-0607",
    "jp": "役に立つ",
    "reading": "やくにたつ",
    "romaji": "yakunitatsu",
    "meaning": "to be helpful, to be useful"
  },
  {
    "id": "n4-0608",
    "jp": "もうすぐ",
    "reading": "もうすぐ",
    "romaji": "mousugu",
    "meaning": "very soon; in a few moments; days"
  },
  {
    "id": "n4-0609",
    "jp": "真中",
    "reading": "まんなか",
    "romaji": "mannaka",
    "meaning": "middle, center"
  },
  {
    "id": "n4-0610",
    "jp": "戻る",
    "reading": "もどる",
    "romaji": "modoru",
    "meaning": "to return (v.i.); to come back"
  },
  {
    "id": "n4-0611",
    "jp": "研究",
    "reading": "けんきゅう",
    "romaji": "kenkyuu",
    "meaning": "study, research, investigation"
  },
  {
    "id": "n4-0612",
    "jp": "ケーキ",
    "reading": "ケーキ",
    "romaji": "ケーキ",
    "meaning": "cake"
  },
  {
    "id": "n4-0613",
    "jp": "草",
    "reading": "くさ",
    "romaji": "kusa",
    "meaning": "grass"
  },
  {
    "id": "n4-0614",
    "jp": "込む",
    "reading": "こむ",
    "romaji": "komu",
    "meaning": "to be crowded"
  },
  {
    "id": "n4-0615",
    "jp": "この頃",
    "reading": "このごろ",
    "romaji": "konogoro",
    "meaning": "these days, nowadays"
  },
  {
    "id": "n4-0616",
    "jp": "訪ねる",
    "reading": "たずねる",
    "romaji": "tazuneru",
    "meaning": "to visit"
  },
  {
    "id": "n4-0617",
    "jp": "下げる",
    "reading": "さげる",
    "romaji": "sageru",
    "meaning": "to lower (v.t.); to hang"
  },
  {
    "id": "n4-0618",
    "jp": "花見",
    "reading": "はなみ",
    "romaji": "hanami",
    "meaning": "cherry-blossom viewing"
  },
  {
    "id": "n4-0619",
    "jp": "途中",
    "reading": "とちゅう",
    "romaji": "tochuu",
    "meaning": "on the way, midway"
  },
  {
    "id": "n4-0620",
    "jp": "入院",
    "reading": "にゅういんする",
    "romaji": "nyuuinsuru",
    "meaning": "hospitalization"
  },
  {
    "id": "n4-0621",
    "jp": "乗り換える",
    "reading": "のりかえる",
    "romaji": "norikaeru",
    "meaning": "to transfer (trains), to change (bus, train, etc.)"
  },
  {
    "id": "n4-0622",
    "jp": "別れる",
    "reading": "わかれる",
    "romaji": "wakareru",
    "meaning": "to part from, to separate"
  },
  {
    "id": "n4-0623",
    "jp": "～町",
    "reading": "～ちょう",
    "romaji": "～chou",
    "meaning": "the town of ~"
  },
  {
    "id": "n4-0624",
    "jp": "安全",
    "reading": "あんぜん",
    "romaji": "anzen",
    "meaning": "safety, security"
  },
  {
    "id": "n4-0625",
    "jp": "看護婦",
    "reading": "かんごふ",
    "romaji": "kangofu",
    "meaning": "(female) nurse"
  },
  {
    "id": "n4-0626",
    "jp": "見物",
    "reading": "けんぶつ",
    "romaji": "kenbutsu",
    "meaning": "sightseeing"
  },
  {
    "id": "n4-0627",
    "jp": "相談",
    "reading": "そうだんする",
    "romaji": "soudansuru",
    "meaning": "consultation"
  },
  {
    "id": "n4-0628",
    "jp": "ガソリンスタンド",
    "reading": "ガソリンスタンド",
    "romaji": "ガソリンスタンド",
    "meaning": "gas station, service station"
  },
  {
    "id": "n4-0629",
    "jp": "テニス",
    "reading": "テニス",
    "romaji": "テニス",
    "meaning": "tennis"
  },
  {
    "id": "n4-0630",
    "jp": "眠る",
    "reading": "ねむる",
    "romaji": "nemuru",
    "meaning": "to sleep"
  },
  {
    "id": "n4-0631",
    "jp": "上がる",
    "reading": "あがる",
    "romaji": "agaru",
    "meaning": "to rise, to go up"
  },
  {
    "id": "n4-0632",
    "jp": "翻訳",
    "reading": "ほんやく",
    "romaji": "hon'yaku",
    "meaning": "translation"
  },
  {
    "id": "n4-0633",
    "jp": "食事",
    "reading": "しょくじする",
    "romaji": "shokujisuru",
    "meaning": "meal"
  },
  {
    "id": "n4-0634",
    "jp": "おかげ",
    "reading": "お陰",
    "romaji": "o陰",
    "meaning": "thanks or owing to"
  },
  {
    "id": "n4-0635",
    "jp": "娘",
    "reading": "むすめ",
    "romaji": "musume",
    "meaning": "daughter (humble)"
  },
  {
    "id": "n4-0636",
    "jp": "湯",
    "reading": "ゆ",
    "romaji": "yu",
    "meaning": "hot water"
  },
  {
    "id": "n4-0637",
    "jp": "競争",
    "reading": "きょうそう",
    "romaji": "kyousou",
    "meaning": "competition, contest"
  },
  {
    "id": "n4-0638",
    "jp": "会議",
    "reading": "かいぎ",
    "romaji": "kaigi",
    "meaning": "business meeting; conference"
  },
  {
    "id": "n4-0639",
    "jp": "湖",
    "reading": "みずうみ",
    "romaji": "mizuumi",
    "meaning": "lake"
  },
  {
    "id": "n4-0640",
    "jp": "集まる",
    "reading": "あつまる",
    "romaji": "atsumaru",
    "meaning": "to gather (v.i.), to collect"
  },
  {
    "id": "n4-0641",
    "jp": "～にくい",
    "reading": "～にくい",
    "romaji": "～nikui",
    "meaning": "difficult to do ~"
  },
  {
    "id": "n4-0642",
    "jp": "生活",
    "reading": "せいかつする",
    "romaji": "seikatsusuru",
    "meaning": "living, life; to live"
  },
  {
    "id": "n4-0643",
    "jp": "糸",
    "reading": "いと",
    "romaji": "ito",
    "meaning": "thread"
  },
  {
    "id": "n4-0644",
    "jp": "関係",
    "reading": "かんけい",
    "romaji": "kankei",
    "meaning": "relation(ship), connection"
  },
  {
    "id": "n4-0645",
    "jp": "ピアノ",
    "reading": "ピアノ",
    "romaji": "ピアノ",
    "meaning": "piano"
  },
  {
    "id": "n4-0646",
    "jp": "～目",
    "reading": "～め",
    "romaji": "～me",
    "meaning": "number ~ sequence, ~nd; ~th"
  },
  {
    "id": "n4-0647",
    "jp": "番組",
    "reading": "ばんぐみ",
    "romaji": "bangumi",
    "meaning": "broadcast program"
  },
  {
    "id": "n4-0648",
    "jp": "急",
    "reading": "きゅう",
    "romaji": "kyuu",
    "meaning": "urgent, sudden; steep"
  },
  {
    "id": "n4-0649",
    "jp": "棚",
    "reading": "たな",
    "romaji": "tana",
    "meaning": "shelves, rack"
  },
  {
    "id": "n4-0650",
    "jp": "木綿",
    "reading": "もめん",
    "romaji": "momen",
    "meaning": "cotton"
  },
  {
    "id": "n4-0651",
    "jp": "輸出",
    "reading": "ゆしゅつする",
    "romaji": "yushutsusuru",
    "meaning": "export"
  },
  {
    "id": "n4-0652",
    "jp": "タイプ",
    "reading": "タイプ",
    "romaji": "タイプ",
    "meaning": "type, style"
  },
  {
    "id": "n4-0653",
    "jp": "すり",
    "reading": "すり",
    "romaji": "suri",
    "meaning": "pickpocket"
  },
  {
    "id": "n4-0654",
    "jp": "うれしい",
    "reading": "嬉しい",
    "romaji": "嬉shii",
    "meaning": "to be happy; to be glad"
  },
  {
    "id": "n4-0655",
    "jp": "アルコール",
    "reading": "アルコール",
    "romaji": "アルコール",
    "meaning": "alcohol"
  },
  {
    "id": "n4-0656",
    "jp": "ソフト",
    "reading": "ソフト",
    "romaji": "ソフト",
    "meaning": "soft; soft hat; software"
  },
  {
    "id": "n4-0657",
    "jp": "神社",
    "reading": "じんじゃ",
    "romaji": "jinja",
    "meaning": "Shinto shrine"
  },
  {
    "id": "n4-0658",
    "jp": "大分",
    "reading": "だいぶ",
    "romaji": "daibu",
    "meaning": "fairly well, to a large extent, considerably, pretty much"
  },
  {
    "id": "n4-0659",
    "jp": "楽しみ",
    "reading": "たのしみ",
    "romaji": "tanoshimi",
    "meaning": "pleasure, joy"
  },
  {
    "id": "n4-0660",
    "jp": "趣味",
    "reading": "しゅみ",
    "romaji": "shumi",
    "meaning": "hobby; pastime"
  },
  {
    "id": "n4-0661",
    "jp": "電報",
    "reading": "でんぽう",
    "romaji": "denpou",
    "meaning": "telegram"
  },
  {
    "id": "n4-0662",
    "jp": "家内",
    "reading": "かない",
    "romaji": "kanai",
    "meaning": "(one's own) wife"
  },
  {
    "id": "n4-0663",
    "jp": "指",
    "reading": "ゆび",
    "romaji": "yubi",
    "meaning": "finger"
  },
  {
    "id": "n4-0664",
    "jp": "これから",
    "reading": "これから",
    "romaji": "korekara",
    "meaning": "from now on, after this"
  },
  {
    "id": "n4-0665",
    "jp": "たまに",
    "reading": "たまに",
    "romaji": "tamani",
    "meaning": "occasionally"
  },
  {
    "id": "n4-0666",
    "jp": "社会",
    "reading": "しゃかい",
    "romaji": "shakai",
    "meaning": "society"
  }
]
