// Generated by scripts/import-japanese-data.mjs — do not edit by hand.
// Source: https://github.com/elzup/jlpt-word-list (MIT)
import type { JapaneseWord } from '../types'

export const N5: JapaneseWord[] = [
  {
    "id": "n5-0001",
    "jp": "ああ",
    "reading": "ああ",
    "romaji": "aa",
    "meaning": "Ah!, Oh!"
  },
  {
    "id": "n5-0002",
    "jp": "会う",
    "reading": "あう",
    "romaji": "au",
    "meaning": "to meet, to see"
  },
  {
    "id": "n5-0003",
    "jp": "青",
    "reading": "あお",
    "romaji": "ao",
    "meaning": "blue"
  },
  {
    "id": "n5-0004",
    "jp": "青い",
    "reading": "あおい",
    "romaji": "aoi",
    "meaning": "blue"
  },
  {
    "id": "n5-0005",
    "jp": "赤",
    "reading": "あか",
    "romaji": "aka",
    "meaning": "red"
  },
  {
    "id": "n5-0006",
    "jp": "赤い",
    "reading": "あかい",
    "romaji": "akai",
    "meaning": "red"
  },
  {
    "id": "n5-0007",
    "jp": "明るい",
    "reading": "あかるい",
    "romaji": "akarui",
    "meaning": "bright (in reference to personality or weather); cheerful"
  },
  {
    "id": "n5-0008",
    "jp": "秋",
    "reading": "あき",
    "romaji": "aki",
    "meaning": "fall (season)"
  },
  {
    "id": "n5-0009",
    "jp": "開く",
    "reading": "あく",
    "romaji": "aku",
    "meaning": "to open, to become open"
  },
  {
    "id": "n5-0010",
    "jp": "開ける",
    "reading": "あける",
    "romaji": "akeru",
    "meaning": "to open (v.t.)"
  },
  {
    "id": "n5-0011",
    "jp": "上げる",
    "reading": "あげる",
    "romaji": "ageru",
    "meaning": "to raise, to lift"
  },
  {
    "id": "n5-0012",
    "jp": "朝",
    "reading": "あさ",
    "romaji": "asa",
    "meaning": "morning"
  },
  {
    "id": "n5-0013",
    "jp": "朝御飯",
    "reading": "あさごはん",
    "romaji": "asagohan",
    "meaning": "breakfast"
  },
  {
    "id": "n5-0014",
    "jp": "明後日",
    "reading": "あさって",
    "romaji": "asatte",
    "meaning": "day after tomorrow"
  },
  {
    "id": "n5-0015",
    "jp": "足; 脚",
    "reading": "あし",
    "romaji": "ashi",
    "meaning": "foot; leg"
  },
  {
    "id": "n5-0016",
    "jp": "明日",
    "reading": "あした",
    "romaji": "ashita",
    "meaning": "tomorrow"
  },
  {
    "id": "n5-0017",
    "jp": "あそこ",
    "reading": "あそこ",
    "romaji": "asoko",
    "meaning": "there, over there, that place"
  },
  {
    "id": "n5-0018",
    "jp": "遊ぶ",
    "reading": "あそぶ",
    "romaji": "asobu",
    "meaning": "to play; to spend time pleasantly; to hang out"
  },
  {
    "id": "n5-0019",
    "jp": "暖かい",
    "reading": "あたたかい",
    "romaji": "atatakai",
    "meaning": "warm"
  },
  {
    "id": "n5-0020",
    "jp": "頭",
    "reading": "あたま",
    "romaji": "atama",
    "meaning": "head"
  },
  {
    "id": "n5-0021",
    "jp": "新しい",
    "reading": "あたらしい",
    "romaji": "atarashii",
    "meaning": "new"
  },
  {
    "id": "n5-0022",
    "jp": "あちら",
    "reading": "あちら",
    "romaji": "achira",
    "meaning": "this way (polite)"
  },
  {
    "id": "n5-0023",
    "jp": "暑い",
    "reading": "あつい",
    "romaji": "atsui",
    "meaning": "hot (in reference to weather), warm"
  },
  {
    "id": "n5-0024",
    "jp": "熱い",
    "reading": "あつい",
    "romaji": "atsui",
    "meaning": "hot (objects)"
  },
  {
    "id": "n5-0025",
    "jp": "厚い",
    "reading": "あつい",
    "romaji": "atsui",
    "meaning": "kind, warm(hearted), thick, deep"
  },
  {
    "id": "n5-0026",
    "jp": "あっち",
    "reading": "あっち",
    "romaji": "atchi",
    "meaning": "over there"
  },
  {
    "id": "n5-0027",
    "jp": "後",
    "reading": "あと",
    "romaji": "ato",
    "meaning": "afterwards (later); in the future; the rest; since then"
  },
  {
    "id": "n5-0028",
    "jp": "あなた",
    "reading": "あなた",
    "romaji": "anata",
    "meaning": "you"
  },
  {
    "id": "n5-0029",
    "jp": "兄",
    "reading": "あに",
    "romaji": "ani",
    "meaning": "(my) older brother (humble)"
  },
  {
    "id": "n5-0030",
    "jp": "姉",
    "reading": "あね",
    "romaji": "ane",
    "meaning": "(my) older sister (humble)"
  },
  {
    "id": "n5-0031",
    "jp": "アパート",
    "reading": "アパート",
    "romaji": "アパート",
    "meaning": "apartment (abbr.)"
  },
  {
    "id": "n5-0032",
    "jp": "あの",
    "reading": "あの",
    "romaji": "ano",
    "meaning": "that over there; like that, that way; um..."
  },
  {
    "id": "n5-0033",
    "jp": "浴びる",
    "reading": "あびる",
    "romaji": "abiru",
    "meaning": "to bathe, to shower"
  },
  {
    "id": "n5-0034",
    "jp": "危ない",
    "reading": "あぶない",
    "romaji": "abunai",
    "meaning": "dangerous, critical"
  },
  {
    "id": "n5-0035",
    "jp": "甘い",
    "reading": "あまい",
    "romaji": "amai",
    "meaning": "generous, sweet"
  },
  {
    "id": "n5-0036",
    "jp": "余り",
    "reading": "あまり",
    "romaji": "amari",
    "meaning": "not very; surplus"
  },
  {
    "id": "n5-0037",
    "jp": "雨",
    "reading": "あめ",
    "romaji": "ame",
    "meaning": "rain"
  },
  {
    "id": "n5-0038",
    "jp": "飴",
    "reading": "あめ",
    "romaji": "ame",
    "meaning": "(hard) candy"
  },
  {
    "id": "n5-0039",
    "jp": "洗う",
    "reading": "あらう",
    "romaji": "arau",
    "meaning": "to wash"
  },
  {
    "id": "n5-0040",
    "jp": "在る",
    "reading": "ある",
    "romaji": "aru",
    "meaning": "to be, to have"
  },
  {
    "id": "n5-0041",
    "jp": "有る",
    "reading": "ある",
    "romaji": "aru",
    "meaning": "to be, to have"
  },
  {
    "id": "n5-0042",
    "jp": "歩く",
    "reading": "あるく",
    "romaji": "aruku",
    "meaning": "to walk"
  },
  {
    "id": "n5-0043",
    "jp": "あれ",
    "reading": "あれ",
    "romaji": "are",
    "meaning": "that one (over there)"
  },
  {
    "id": "n5-0044",
    "jp": "いい; よい",
    "reading": "いい; よい",
    "romaji": "ii; yoi",
    "meaning": "good"
  },
  {
    "id": "n5-0045",
    "jp": "いいえ",
    "reading": "いいえ",
    "romaji": "iie",
    "meaning": "no, not at all"
  },
  {
    "id": "n5-0046",
    "jp": "言う",
    "reading": "いう",
    "romaji": "iu",
    "meaning": "to say"
  },
  {
    "id": "n5-0047",
    "jp": "家",
    "reading": "いえ",
    "romaji": "ie",
    "meaning": "house, home"
  },
  {
    "id": "n5-0048",
    "jp": "いかが",
    "reading": "いかが",
    "romaji": "ikaga",
    "meaning": "how, in what way"
  },
  {
    "id": "n5-0049",
    "jp": "行く",
    "reading": "いく; ゆく",
    "romaji": "iku; yuku",
    "meaning": "to go"
  },
  {
    "id": "n5-0050",
    "jp": "いくつ",
    "reading": "いくつ",
    "romaji": "ikutsu",
    "meaning": "how many, how old"
  },
  {
    "id": "n5-0051",
    "jp": "いくら",
    "reading": "いくら",
    "romaji": "ikura",
    "meaning": "how much, how many"
  },
  {
    "id": "n5-0052",
    "jp": "池",
    "reading": "いけ",
    "romaji": "ike",
    "meaning": "pond"
  },
  {
    "id": "n5-0053",
    "jp": "医者",
    "reading": "いしゃ",
    "romaji": "isha",
    "meaning": "doctor; physician"
  },
  {
    "id": "n5-0054",
    "jp": "椅子",
    "reading": "いす",
    "romaji": "isu",
    "meaning": "chair"
  },
  {
    "id": "n5-0055",
    "jp": "忙しい",
    "reading": "いそがしい",
    "romaji": "isogashii",
    "meaning": "busy (people, days)"
  },
  {
    "id": "n5-0056",
    "jp": "痛い",
    "reading": "いたい",
    "romaji": "itai",
    "meaning": "hurt; painful; sore"
  },
  {
    "id": "n5-0057",
    "jp": "一",
    "reading": "いち",
    "romaji": "ichi",
    "meaning": "one"
  },
  {
    "id": "n5-0058",
    "jp": "一日",
    "reading": "いちにち",
    "romaji": "ichinichi",
    "meaning": "one day (duration)"
  },
  {
    "id": "n5-0059",
    "jp": "一番",
    "reading": "いちばん",
    "romaji": "ichiban",
    "meaning": "best (most), first, number one"
  },
  {
    "id": "n5-0060",
    "jp": "いつ",
    "reading": "いつ",
    "romaji": "itsu",
    "meaning": "when"
  },
  {
    "id": "n5-0061",
    "jp": "五日",
    "reading": "いつか",
    "romaji": "itsuka",
    "meaning": "five days; fifth day of the month"
  },
  {
    "id": "n5-0062",
    "jp": "一緒",
    "reading": "いっしょ",
    "romaji": "issho",
    "meaning": "together"
  },
  {
    "id": "n5-0063",
    "jp": "五つ",
    "reading": "いつつ",
    "romaji": "itsutsu",
    "meaning": "five things"
  },
  {
    "id": "n5-0064",
    "jp": "いつも",
    "reading": "いつも",
    "romaji": "itsumo",
    "meaning": "always, usually, every time, never (with neg. verb)"
  },
  {
    "id": "n5-0065",
    "jp": "犬",
    "reading": "いぬ",
    "romaji": "inu",
    "meaning": "dog"
  },
  {
    "id": "n5-0066",
    "jp": "今",
    "reading": "いま",
    "romaji": "ima",
    "meaning": "now"
  },
  {
    "id": "n5-0067",
    "jp": "意味",
    "reading": "いみ",
    "romaji": "imi",
    "meaning": "meaning, significance"
  },
  {
    "id": "n5-0068",
    "jp": "妹",
    "reading": "いもうと",
    "romaji": "imouto",
    "meaning": "younger sister (humble)"
  },
  {
    "id": "n5-0069",
    "jp": "嫌",
    "reading": "いや",
    "romaji": "iya",
    "meaning": "disagreeable, detestable, unpleasant"
  },
  {
    "id": "n5-0070",
    "jp": "入口",
    "reading": "いりぐち",
    "romaji": "iriguchi",
    "meaning": "entrance"
  },
  {
    "id": "n5-0071",
    "jp": "居る",
    "reading": "いる",
    "romaji": "iru",
    "meaning": "(humble) to be (animate), to exist"
  },
  {
    "id": "n5-0072",
    "jp": "要る",
    "reading": "いる",
    "romaji": "iru",
    "meaning": "to need"
  },
  {
    "id": "n5-0073",
    "jp": "入れる",
    "reading": "いれる",
    "romaji": "ireru",
    "meaning": "to put in"
  },
  {
    "id": "n5-0074",
    "jp": "色",
    "reading": "いろ",
    "romaji": "iro",
    "meaning": "color"
  },
  {
    "id": "n5-0075",
    "jp": "色々",
    "reading": "いろいろ",
    "romaji": "iroiro",
    "meaning": "various"
  },
  {
    "id": "n5-0076",
    "jp": "上",
    "reading": "うえ",
    "romaji": "ue",
    "meaning": "above (up, top, etc.), over, on top of"
  },
  {
    "id": "n5-0077",
    "jp": "後ろ",
    "reading": "うしろ",
    "romaji": "ushiro",
    "meaning": "back, behind, rear"
  },
  {
    "id": "n5-0078",
    "jp": "薄い",
    "reading": "うすい",
    "romaji": "usui",
    "meaning": "thin, weak"
  },
  {
    "id": "n5-0079",
    "jp": "歌",
    "reading": "うた",
    "romaji": "uta",
    "meaning": "a song"
  },
  {
    "id": "n5-0080",
    "jp": "歌う",
    "reading": "うたう",
    "romaji": "utau",
    "meaning": "to sing"
  },
  {
    "id": "n5-0081",
    "jp": "うち",
    "reading": "うち",
    "romaji": "uchi",
    "meaning": "home; house; my place"
  },
  {
    "id": "n5-0082",
    "jp": "生まれる",
    "reading": "うまれる",
    "romaji": "umareru",
    "meaning": "to be born"
  },
  {
    "id": "n5-0083",
    "jp": "海",
    "reading": "うみ",
    "romaji": "umi",
    "meaning": "sea, beach"
  },
  {
    "id": "n5-0084",
    "jp": "売る",
    "reading": "うる",
    "romaji": "uru",
    "meaning": "to sell (v.t.)"
  },
  {
    "id": "n5-0085",
    "jp": "うるさい",
    "reading": "うるさい",
    "romaji": "urusai",
    "meaning": "noisy; annoying"
  },
  {
    "id": "n5-0086",
    "jp": "上着",
    "reading": "うわぎ",
    "romaji": "uwagi",
    "meaning": "coat, jacket"
  },
  {
    "id": "n5-0087",
    "jp": "絵",
    "reading": "え",
    "romaji": "e",
    "meaning": "a painting; a picture; a drawing"
  },
  {
    "id": "n5-0088",
    "jp": "映画",
    "reading": "えいが",
    "romaji": "eiga",
    "meaning": "movie, film"
  },
  {
    "id": "n5-0089",
    "jp": "映画館",
    "reading": "えいがかん",
    "romaji": "eigakan",
    "meaning": "movie theater, cinema"
  },
  {
    "id": "n5-0090",
    "jp": "英語",
    "reading": "えいご",
    "romaji": "eigo",
    "meaning": "English (language)"
  },
  {
    "id": "n5-0091",
    "jp": "ええ",
    "reading": "ええ",
    "romaji": "ee",
    "meaning": "yes"
  },
  {
    "id": "n5-0092",
    "jp": "駅",
    "reading": "えき",
    "romaji": "eki",
    "meaning": "station"
  },
  {
    "id": "n5-0093",
    "jp": "エレベーター",
    "reading": "エレベーター",
    "romaji": "エレベーター",
    "meaning": "elevator"
  },
  {
    "id": "n5-0094",
    "jp": "～円",
    "reading": "～えん",
    "romaji": "～en",
    "meaning": "Yen"
  },
  {
    "id": "n5-0095",
    "jp": "鉛筆",
    "reading": "えんぴつ",
    "romaji": "enpitsu",
    "meaning": "pencil"
  },
  {
    "id": "n5-0096",
    "jp": "お～",
    "reading": "お～",
    "romaji": "o～",
    "meaning": "honorable ~ (honorific)"
  },
  {
    "id": "n5-0097",
    "jp": "美味しい",
    "reading": "おいしい",
    "romaji": "oishii",
    "meaning": "delicious, tasty"
  },
  {
    "id": "n5-0098",
    "jp": "多い",
    "reading": "おおい",
    "romaji": "ooi",
    "meaning": "many; there are a lot"
  },
  {
    "id": "n5-0099",
    "jp": "大きい",
    "reading": "おおきい",
    "romaji": "ookii",
    "meaning": "big, large"
  },
  {
    "id": "n5-0100",
    "jp": "大きな",
    "reading": "おおきな",
    "romaji": "ookina",
    "meaning": "big"
  },
  {
    "id": "n5-0101",
    "jp": "大勢",
    "reading": "おおぜい",
    "romaji": "oozei",
    "meaning": "great number of people"
  },
  {
    "id": "n5-0102",
    "jp": "お母さん",
    "reading": "おかあさん",
    "romaji": "okaasan",
    "meaning": "mother (formal)"
  },
  {
    "id": "n5-0103",
    "jp": "お菓子",
    "reading": "おかし",
    "romaji": "okashi",
    "meaning": "confections, sweets, snack"
  },
  {
    "id": "n5-0104",
    "jp": "お金",
    "reading": "おかね",
    "romaji": "okane",
    "meaning": "money"
  },
  {
    "id": "n5-0105",
    "jp": "起きる",
    "reading": "おきる",
    "romaji": "okiru",
    "meaning": "to get up (e.g., from sleeping); to happen"
  },
  {
    "id": "n5-0106",
    "jp": "置く",
    "reading": "おく",
    "romaji": "oku",
    "meaning": "to put; to lay; to place"
  },
  {
    "id": "n5-0107",
    "jp": "奥さん",
    "reading": "おくさん",
    "romaji": "okusan",
    "meaning": "(someone else's) wife (hon.)"
  },
  {
    "id": "n5-0108",
    "jp": "お酒",
    "reading": "おさけ",
    "romaji": "osake",
    "meaning": "sake; alcohol"
  },
  {
    "id": "n5-0109",
    "jp": "お皿",
    "reading": "おさら",
    "romaji": "osara",
    "meaning": "plate, dish"
  },
  {
    "id": "n5-0110",
    "jp": "伯父; 叔父さん",
    "reading": "おじさん",
    "romaji": "ojisan",
    "meaning": "uncle, middle-aged man"
  },
  {
    "id": "n5-0111",
    "jp": "おじいさん",
    "reading": "おじいさん",
    "romaji": "ojiisan",
    "meaning": "grandfather, male senior citizen"
  },
  {
    "id": "n5-0112",
    "jp": "教える",
    "reading": "おしえる",
    "romaji": "oshieru",
    "meaning": "to teach, to inform, to instruct"
  },
  {
    "id": "n5-0113",
    "jp": "押す",
    "reading": "おす",
    "romaji": "osu",
    "meaning": "to push, to press, to stamp (e.g., a passport)"
  },
  {
    "id": "n5-0114",
    "jp": "遅い",
    "reading": "おそい",
    "romaji": "osoi",
    "meaning": "slow; (to be) late"
  },
  {
    "id": "n5-0115",
    "jp": "お茶",
    "reading": "おちゃ",
    "romaji": "ocha",
    "meaning": "(green) tea"
  },
  {
    "id": "n5-0116",
    "jp": "お手洗い",
    "reading": "おてあらい",
    "romaji": "otearai",
    "meaning": "toilet, restroom, bathroom (lit., a place to wash one's hands)"
  },
  {
    "id": "n5-0117",
    "jp": "お父さん",
    "reading": "おとうさん",
    "romaji": "otousan",
    "meaning": "father (formal)"
  },
  {
    "id": "n5-0118",
    "jp": "弟",
    "reading": "おとうと",
    "romaji": "otouto",
    "meaning": "younger brother"
  },
  {
    "id": "n5-0119",
    "jp": "男",
    "reading": "おとこ",
    "romaji": "otoko",
    "meaning": "man, male"
  },
  {
    "id": "n5-0120",
    "jp": "男の子",
    "reading": "おとこのこ",
    "romaji": "otokonoko",
    "meaning": "boy"
  },
  {
    "id": "n5-0121",
    "jp": "一昨日",
    "reading": "おととい",
    "romaji": "ototoi",
    "meaning": "the day before yesterday"
  },
  {
    "id": "n5-0122",
    "jp": "おととし",
    "reading": "おととし",
    "romaji": "ototoshi",
    "meaning": "year before last"
  },
  {
    "id": "n5-0123",
    "jp": "大人",
    "reading": "おとな",
    "romaji": "otona",
    "meaning": "adult"
  },
  {
    "id": "n5-0124",
    "jp": "お腹",
    "reading": "おなか",
    "romaji": "onaka",
    "meaning": "stomach"
  },
  {
    "id": "n5-0125",
    "jp": "同じ",
    "reading": "おなじ",
    "romaji": "onaji",
    "meaning": "same, identical"
  },
  {
    "id": "n5-0126",
    "jp": "お兄さん",
    "reading": "おにいさん",
    "romaji": "oniisan",
    "meaning": "(someone else's) older brother (formal)"
  },
  {
    "id": "n5-0127",
    "jp": "お姉さん",
    "reading": "おねえさん",
    "romaji": "oneesan",
    "meaning": "older sister (formal)"
  },
  {
    "id": "n5-0128",
    "jp": "伯母さん; 叔母さん",
    "reading": "おばさん",
    "romaji": "obasan",
    "meaning": "aunt"
  },
  {
    "id": "n5-0129",
    "jp": "おばあさん",
    "reading": "おばあさん",
    "romaji": "obaasan",
    "meaning": "grandmother, female senior-citizen"
  },
  {
    "id": "n5-0130",
    "jp": "お風呂",
    "reading": "おふろ",
    "romaji": "ofuro",
    "meaning": "a bath"
  },
  {
    "id": "n5-0131",
    "jp": "お弁当",
    "reading": "おべんとう",
    "romaji": "obentou",
    "meaning": "a boxed lunch"
  },
  {
    "id": "n5-0132",
    "jp": "覚える",
    "reading": "おぼえる",
    "romaji": "oboeru",
    "meaning": "to learn, to commit to memory, to remember, to memorize"
  },
  {
    "id": "n5-0133",
    "jp": "おまわりさん",
    "reading": "おまわりさん",
    "romaji": "omawarisan",
    "meaning": "policeman (friendly term)"
  },
  {
    "id": "n5-0134",
    "jp": "重い",
    "reading": "おもい",
    "romaji": "omoi",
    "meaning": "heavy; serious"
  },
  {
    "id": "n5-0135",
    "jp": "面白い",
    "reading": "おもしろい",
    "romaji": "omoshiroi",
    "meaning": "interesting, amusing"
  },
  {
    "id": "n5-0136",
    "jp": "泳ぐ",
    "reading": "およぐ",
    "romaji": "oyogu",
    "meaning": "to swim"
  },
  {
    "id": "n5-0137",
    "jp": "降りる",
    "reading": "おりる",
    "romaji": "oriru",
    "meaning": "to get off"
  },
  {
    "id": "n5-0138",
    "jp": "終る",
    "reading": "おわる",
    "romaji": "owaru",
    "meaning": "to finish, to close"
  },
  {
    "id": "n5-0139",
    "jp": "音楽",
    "reading": "おんがく",
    "romaji": "ongaku",
    "meaning": "Music"
  },
  {
    "id": "n5-0140",
    "jp": "女",
    "reading": "おんな",
    "romaji": "onna",
    "meaning": "woman, female"
  },
  {
    "id": "n5-0141",
    "jp": "女の子",
    "reading": "おんなのこ",
    "romaji": "onnanoko",
    "meaning": "girl"
  },
  {
    "id": "n5-0142",
    "jp": "～回",
    "reading": "～かい",
    "romaji": "～kai",
    "meaning": "counter for occurrences (~ times)"
  },
  {
    "id": "n5-0143",
    "jp": "～階",
    "reading": "～かい",
    "romaji": "～kai",
    "meaning": "counter for stories (floors) of a building"
  },
  {
    "id": "n5-0144",
    "jp": "外国",
    "reading": "がいこく",
    "romaji": "gaikoku",
    "meaning": "foreign country; abroad"
  },
  {
    "id": "n5-0145",
    "jp": "外国人",
    "reading": "がいこくじん",
    "romaji": "gaikokujin",
    "meaning": "foreigner"
  },
  {
    "id": "n5-0146",
    "jp": "会社",
    "reading": "かいしゃ",
    "romaji": "kaisha",
    "meaning": "company, corporation"
  },
  {
    "id": "n5-0147",
    "jp": "階段",
    "reading": "かいだん",
    "romaji": "kaidan",
    "meaning": "stairs"
  },
  {
    "id": "n5-0148",
    "jp": "買い物",
    "reading": "かいもの",
    "romaji": "kaimono",
    "meaning": "shopping"
  },
  {
    "id": "n5-0149",
    "jp": "買う",
    "reading": "かう",
    "romaji": "kau",
    "meaning": "to buy"
  },
  {
    "id": "n5-0150",
    "jp": "返す",
    "reading": "かえす",
    "romaji": "kaesu",
    "meaning": "to return something"
  },
  {
    "id": "n5-0151",
    "jp": "帰る",
    "reading": "かえる",
    "romaji": "kaeru",
    "meaning": "to go back, to go home, to return"
  },
  {
    "id": "n5-0152",
    "jp": "顔",
    "reading": "かお",
    "romaji": "kao",
    "meaning": "face (body part)"
  },
  {
    "id": "n5-0153",
    "jp": "かかる",
    "reading": "かかる",
    "romaji": "kakaru",
    "meaning": "it takes (amount of time, money) (v.i.)"
  },
  {
    "id": "n5-0154",
    "jp": "鍵",
    "reading": "かぎ",
    "romaji": "kagi",
    "meaning": "a lock; a key"
  },
  {
    "id": "n5-0155",
    "jp": "書く",
    "reading": "かく",
    "romaji": "kaku",
    "meaning": "to write"
  },
  {
    "id": "n5-0156",
    "jp": "学生",
    "reading": "がくせい",
    "romaji": "gakusei",
    "meaning": "student"
  },
  {
    "id": "n5-0157",
    "jp": "～か月",
    "reading": "～かげつ",
    "romaji": "～kagetsu",
    "meaning": "(number of) months"
  },
  {
    "id": "n5-0158",
    "jp": "掛ける",
    "reading": "かける",
    "romaji": "kakeru",
    "meaning": "to put on (e.g., glasses); to hang (e.g., on a wall)"
  },
  {
    "id": "n5-0159",
    "jp": "かける",
    "reading": "かける",
    "romaji": "kakeru",
    "meaning": "to dial/call (e.g., phone); to sit down"
  },
  {
    "id": "n5-0160",
    "jp": "傘",
    "reading": "かさ",
    "romaji": "kasa",
    "meaning": "umbrella, parasol"
  },
  {
    "id": "n5-0161",
    "jp": "貸す",
    "reading": "かす",
    "romaji": "kasu",
    "meaning": "to lend"
  },
  {
    "id": "n5-0162",
    "jp": "風",
    "reading": "かぜ",
    "romaji": "kaze",
    "meaning": "wind, breeze"
  },
  {
    "id": "n5-0163",
    "jp": "風邪",
    "reading": "かぜ",
    "romaji": "kaze",
    "meaning": "cold, flu"
  },
  {
    "id": "n5-0164",
    "jp": "方",
    "reading": "かた",
    "romaji": "kata",
    "meaning": "-- honorific form for 人 (ひと) --; way of doing"
  },
  {
    "id": "n5-0165",
    "jp": "家族",
    "reading": "かぞく",
    "romaji": "kazoku",
    "meaning": "family, members of a family"
  },
  {
    "id": "n5-0166",
    "jp": "片仮名",
    "reading": "かたかな",
    "romaji": "katakana",
    "meaning": "katakana"
  },
  {
    "id": "n5-0167",
    "jp": "～月",
    "reading": "～がつ",
    "romaji": "～gatsu",
    "meaning": "month of year"
  },
  {
    "id": "n5-0168",
    "jp": "学校",
    "reading": "がっこう",
    "romaji": "gakkou",
    "meaning": "a school"
  },
  {
    "id": "n5-0169",
    "jp": "カップ",
    "reading": "カップ",
    "romaji": "カップ",
    "meaning": "cup"
  },
  {
    "id": "n5-0170",
    "jp": "家庭",
    "reading": "かてい",
    "romaji": "katei",
    "meaning": "home; family"
  },
  {
    "id": "n5-0171",
    "jp": "角",
    "reading": "かど",
    "romaji": "kado",
    "meaning": "corner (e.g., desk, pavement)"
  },
  {
    "id": "n5-0172",
    "jp": "かばん",
    "reading": "かばん",
    "romaji": "kaban",
    "meaning": "bag, basket"
  },
  {
    "id": "n5-0173",
    "jp": "花瓶",
    "reading": "かびん",
    "romaji": "kabin",
    "meaning": "(flower) vase"
  },
  {
    "id": "n5-0174",
    "jp": "かぶる",
    "reading": "かぶる",
    "romaji": "kaburu",
    "meaning": "to wear, to put on (e.g., a hat on the head)"
  },
  {
    "id": "n5-0175",
    "jp": "紙",
    "reading": "かみ",
    "romaji": "kami",
    "meaning": "paper"
  },
  {
    "id": "n5-0176",
    "jp": "カメラ",
    "reading": "カメラ",
    "romaji": "カメラ",
    "meaning": "camera"
  },
  {
    "id": "n5-0177",
    "jp": "火曜日",
    "reading": "かようび",
    "romaji": "kayoubi",
    "meaning": "Tuesday"
  },
  {
    "id": "n5-0178",
    "jp": "辛い",
    "reading": "からい",
    "romaji": "karai",
    "meaning": "hot and spicy; salty"
  },
  {
    "id": "n5-0179",
    "jp": "体",
    "reading": "からだ",
    "romaji": "karada",
    "meaning": "body; health"
  },
  {
    "id": "n5-0180",
    "jp": "借りる",
    "reading": "かりる",
    "romaji": "kariru",
    "meaning": "to borrow, to owe"
  },
  {
    "id": "n5-0181",
    "jp": "～がる",
    "reading": "～がる",
    "romaji": "～garu",
    "meaning": "feel"
  },
  {
    "id": "n5-0182",
    "jp": "軽い",
    "reading": "かるい",
    "romaji": "karui",
    "meaning": "light, non-serious, minor"
  },
  {
    "id": "n5-0183",
    "jp": "カレー",
    "reading": "カレー",
    "romaji": "カレー",
    "meaning": "curry (abbr. for curry and rice)"
  },
  {
    "id": "n5-0184",
    "jp": "カレンダー",
    "reading": "カレンダー",
    "romaji": "カレンダー",
    "meaning": "calendar"
  },
  {
    "id": "n5-0185",
    "jp": "川; 河",
    "reading": "かわ",
    "romaji": "kawa",
    "meaning": "river"
  },
  {
    "id": "n5-0186",
    "jp": "～側",
    "reading": "～がわ",
    "romaji": "～gawa",
    "meaning": "~ side"
  },
  {
    "id": "n5-0187",
    "jp": "可愛い",
    "reading": "かわいい",
    "romaji": "kawaii",
    "meaning": "cute, adorable"
  },
  {
    "id": "n5-0188",
    "jp": "漢字",
    "reading": "かんじ",
    "romaji": "kanji",
    "meaning": "kanji; Chinese character"
  },
  {
    "id": "n5-0189",
    "jp": "木",
    "reading": "き",
    "romaji": "ki",
    "meaning": "tree, wood, timber"
  },
  {
    "id": "n5-0190",
    "jp": "黄色",
    "reading": "きいろ",
    "romaji": "kiiro",
    "meaning": "yellow"
  },
  {
    "id": "n5-0191",
    "jp": "黄色い",
    "reading": "きいろい",
    "romaji": "kiiroi",
    "meaning": "yellow"
  },
  {
    "id": "n5-0192",
    "jp": "消える",
    "reading": "きえる",
    "romaji": "kieru",
    "meaning": "to vanish, to disappear"
  },
  {
    "id": "n5-0193",
    "jp": "聞く",
    "reading": "きく",
    "romaji": "kiku",
    "meaning": "to hear, to listen, to ask"
  },
  {
    "id": "n5-0194",
    "jp": "北",
    "reading": "きた",
    "romaji": "kita",
    "meaning": "north"
  },
  {
    "id": "n5-0195",
    "jp": "ギター",
    "reading": "ギター",
    "romaji": "ギター",
    "meaning": "guitar"
  },
  {
    "id": "n5-0196",
    "jp": "汚い",
    "reading": "きたない",
    "romaji": "kitanai",
    "meaning": "dirty, unclean, filthy"
  },
  {
    "id": "n5-0197",
    "jp": "喫茶店",
    "reading": "きっさてん",
    "romaji": "kissaten",
    "meaning": "café"
  },
  {
    "id": "n5-0198",
    "jp": "切手",
    "reading": "きって",
    "romaji": "kitte",
    "meaning": "postal (postage) stamps"
  },
  {
    "id": "n5-0199",
    "jp": "切符",
    "reading": "きっぷ",
    "romaji": "kippu",
    "meaning": "a ticket"
  },
  {
    "id": "n5-0200",
    "jp": "昨日",
    "reading": "きのう",
    "romaji": "kinou",
    "meaning": "yesterday"
  },
  {
    "id": "n5-0201",
    "jp": "九",
    "reading": "きゅう",
    "romaji": "kyuu",
    "meaning": "nine"
  },
  {
    "id": "n5-0202",
    "jp": "牛肉",
    "reading": "ぎゅうにく",
    "romaji": "gyuuniku",
    "meaning": "beef"
  },
  {
    "id": "n5-0203",
    "jp": "牛乳",
    "reading": "ぎゅうにゅう",
    "romaji": "gyuunyuu",
    "meaning": "milk"
  },
  {
    "id": "n5-0204",
    "jp": "今日",
    "reading": "きょう",
    "romaji": "kyou",
    "meaning": "today, this day"
  },
  {
    "id": "n5-0205",
    "jp": "教室",
    "reading": "きょうしつ",
    "romaji": "kyoushitsu",
    "meaning": "classroom"
  },
  {
    "id": "n5-0206",
    "jp": "兄弟",
    "reading": "きょうだい",
    "romaji": "kyoudai",
    "meaning": "siblings (humble), brothers and sisters"
  },
  {
    "id": "n5-0207",
    "jp": "去年",
    "reading": "きょねん",
    "romaji": "kyonen",
    "meaning": "last year"
  },
  {
    "id": "n5-0208",
    "jp": "嫌い",
    "reading": "きらい",
    "romaji": "kirai",
    "meaning": "dislike"
  },
  {
    "id": "n5-0209",
    "jp": "切る",
    "reading": "きる",
    "romaji": "kiru",
    "meaning": "to cut; to hang up (a phone)"
  },
  {
    "id": "n5-0210",
    "jp": "着る",
    "reading": "きる",
    "romaji": "kiru",
    "meaning": "to put on (clothes above your waist); to wear"
  },
  {
    "id": "n5-0211",
    "jp": "綺麗",
    "reading": "きれい",
    "romaji": "kirei",
    "meaning": "pretty, clean, tidy"
  },
  {
    "id": "n5-0212",
    "jp": "キロ; キログラム",
    "reading": "キロ; キログラム",
    "romaji": "キロ; キログラム",
    "meaning": "(abbr.) kilo (kilogram)"
  },
  {
    "id": "n5-0213",
    "jp": "キロ; キロメートル",
    "reading": "キロ; キロメートル",
    "romaji": "キロ; キロメートル",
    "meaning": "(abbr.) kilo (kilometer)"
  },
  {
    "id": "n5-0214",
    "jp": "銀行",
    "reading": "ぎんこう",
    "romaji": "ginkou",
    "meaning": "bank"
  },
  {
    "id": "n5-0215",
    "jp": "金曜日",
    "reading": "きんようび",
    "romaji": "kin'youbi",
    "meaning": "Friday"
  },
  {
    "id": "n5-0216",
    "jp": "九",
    "reading": "く",
    "romaji": "ku",
    "meaning": "nine"
  },
  {
    "id": "n5-0217",
    "jp": "薬",
    "reading": "くすり",
    "romaji": "kusuri",
    "meaning": "medicine"
  },
  {
    "id": "n5-0218",
    "jp": "下さい",
    "reading": "ください",
    "romaji": "kudasai",
    "meaning": "(with te-form verb) please do for me"
  },
  {
    "id": "n5-0219",
    "jp": "果物",
    "reading": "くだもの",
    "romaji": "kudamono",
    "meaning": "fruit"
  },
  {
    "id": "n5-0220",
    "jp": "口",
    "reading": "くち",
    "romaji": "kuchi",
    "meaning": "job opening; mouth"
  },
  {
    "id": "n5-0221",
    "jp": "靴",
    "reading": "くつ",
    "romaji": "kutsu",
    "meaning": "shoes, footwear"
  },
  {
    "id": "n5-0222",
    "jp": "靴下",
    "reading": "くつした",
    "romaji": "kutsushita",
    "meaning": "socks"
  },
  {
    "id": "n5-0223",
    "jp": "国",
    "reading": "くに",
    "romaji": "kuni",
    "meaning": "country; place of origin"
  },
  {
    "id": "n5-0224",
    "jp": "曇り",
    "reading": "くもり",
    "romaji": "kumori",
    "meaning": "cloudiness, cloudy weather"
  },
  {
    "id": "n5-0225",
    "jp": "曇る",
    "reading": "くもる",
    "romaji": "kumoru",
    "meaning": "to become cloudy, to become dim"
  },
  {
    "id": "n5-0226",
    "jp": "暗い",
    "reading": "くらい",
    "romaji": "kurai",
    "meaning": "dark, gloomy"
  },
  {
    "id": "n5-0227",
    "jp": "～くらい; ぐらい",
    "reading": "～くらい; ぐらい",
    "romaji": "～kurai; gurai",
    "meaning": "approximate (quantity)"
  },
  {
    "id": "n5-0228",
    "jp": "クラス",
    "reading": "クラス",
    "romaji": "クラス",
    "meaning": "a class"
  },
  {
    "id": "n5-0229",
    "jp": "グラム",
    "reading": "グラム",
    "romaji": "グラム",
    "meaning": "gram"
  },
  {
    "id": "n5-0230",
    "jp": "来る",
    "reading": "くる",
    "romaji": "kuru",
    "meaning": "to come"
  },
  {
    "id": "n5-0231",
    "jp": "車",
    "reading": "くるま",
    "romaji": "kuruma",
    "meaning": "car, vehicle"
  },
  {
    "id": "n5-0232",
    "jp": "黒",
    "reading": "くろ",
    "romaji": "kuro",
    "meaning": "black"
  },
  {
    "id": "n5-0233",
    "jp": "黒い",
    "reading": "くろい",
    "romaji": "kuroi",
    "meaning": "black; dark"
  },
  {
    "id": "n5-0234",
    "jp": "警官",
    "reading": "けいかん",
    "romaji": "keikan",
    "meaning": "police officer"
  },
  {
    "id": "n5-0235",
    "jp": "今朝",
    "reading": "けさ",
    "romaji": "kesa",
    "meaning": "this morning"
  },
  {
    "id": "n5-0236",
    "jp": "消す",
    "reading": "けす",
    "romaji": "kesu",
    "meaning": "to erase, to delete, to turn off power"
  },
  {
    "id": "n5-0237",
    "jp": "結構",
    "reading": "けっこう",
    "romaji": "kekkou",
    "meaning": "splendid; enough, tolerably"
  },
  {
    "id": "n5-0238",
    "jp": "結婚",
    "reading": "けっこん (する)",
    "romaji": "kekkon (suru)",
    "meaning": "marriage (get married)"
  },
  {
    "id": "n5-0239",
    "jp": "月曜日",
    "reading": "げつようび",
    "romaji": "getsuyoubi",
    "meaning": "Monday"
  },
  {
    "id": "n5-0240",
    "jp": "玄関",
    "reading": "げんかん",
    "romaji": "genkan",
    "meaning": "entrance (to a house or a building)"
  },
  {
    "id": "n5-0241",
    "jp": "元気",
    "reading": "げんき",
    "romaji": "genki",
    "meaning": "health(y), energetic"
  },
  {
    "id": "n5-0242",
    "jp": "～個",
    "reading": "～こ",
    "romaji": "～ko",
    "meaning": "counter for small items (e.g., fruits, cups)"
  },
  {
    "id": "n5-0243",
    "jp": "五",
    "reading": "ご",
    "romaji": "go",
    "meaning": "five"
  },
  {
    "id": "n5-0244",
    "jp": "～語",
    "reading": "～ご",
    "romaji": "～go",
    "meaning": "word, language"
  },
  {
    "id": "n5-0245",
    "jp": "公園",
    "reading": "こうえん",
    "romaji": "kouen",
    "meaning": "a park"
  },
  {
    "id": "n5-0246",
    "jp": "交差点",
    "reading": "こうさてん",
    "romaji": "kousaten",
    "meaning": "intersection"
  },
  {
    "id": "n5-0247",
    "jp": "紅茶",
    "reading": "こうちゃ",
    "romaji": "koucha",
    "meaning": "black tea"
  },
  {
    "id": "n5-0248",
    "jp": "交番",
    "reading": "こうばん",
    "romaji": "kouban",
    "meaning": "police box"
  },
  {
    "id": "n5-0249",
    "jp": "声",
    "reading": "こえ",
    "romaji": "koe",
    "meaning": "voice"
  },
  {
    "id": "n5-0250",
    "jp": "コート",
    "reading": "コート",
    "romaji": "コート",
    "meaning": "coat; court (e.g., tennis)"
  },
  {
    "id": "n5-0251",
    "jp": "コーヒー",
    "reading": "コーヒー",
    "romaji": "コーヒー",
    "meaning": "coffee"
  },
  {
    "id": "n5-0252",
    "jp": "ここ",
    "reading": "ここ",
    "romaji": "koko",
    "meaning": "here, this place"
  },
  {
    "id": "n5-0253",
    "jp": "午後",
    "reading": "ごご",
    "romaji": "gogo",
    "meaning": "afternoon, P.M."
  },
  {
    "id": "n5-0254",
    "jp": "九日",
    "reading": "ここのか",
    "romaji": "kokonoka",
    "meaning": "nine days; ninth day of the month"
  },
  {
    "id": "n5-0255",
    "jp": "九つ",
    "reading": "ここのつ",
    "romaji": "kokonotsu",
    "meaning": "nine things"
  },
  {
    "id": "n5-0256",
    "jp": "午前",
    "reading": "ごぜん",
    "romaji": "gozen",
    "meaning": "morning, A.M."
  },
  {
    "id": "n5-0257",
    "jp": "答える",
    "reading": "こたえる",
    "romaji": "kotaeru",
    "meaning": "to answer, to reply"
  },
  {
    "id": "n5-0258",
    "jp": "こちら",
    "reading": "こちら",
    "romaji": "kochira",
    "meaning": "this person (polite); this way (polite)"
  },
  {
    "id": "n5-0259",
    "jp": "こっち",
    "reading": "こっち",
    "romaji": "kotchi",
    "meaning": "this person; this direction; this side"
  },
  {
    "id": "n5-0260",
    "jp": "コップ",
    "reading": "コップ",
    "romaji": "コップ",
    "meaning": "a tumbler; a glass"
  },
  {
    "id": "n5-0261",
    "jp": "今年",
    "reading": "ことし",
    "romaji": "kotoshi",
    "meaning": "this year"
  },
  {
    "id": "n5-0262",
    "jp": "言葉",
    "reading": "ことば",
    "romaji": "kotoba",
    "meaning": "language; word(s); expression(s)"
  },
  {
    "id": "n5-0263",
    "jp": "子供",
    "reading": "こども",
    "romaji": "kodomo",
    "meaning": "child(ren)"
  },
  {
    "id": "n5-0264",
    "jp": "この",
    "reading": "この",
    "romaji": "kono",
    "meaning": "this"
  },
  {
    "id": "n5-0265",
    "jp": "御飯",
    "reading": "ごはん",
    "romaji": "gohan",
    "meaning": "rice (cooked); meal"
  },
  {
    "id": "n5-0266",
    "jp": "コピーする",
    "reading": "コピーする",
    "romaji": "コピーsuru",
    "meaning": "to copy"
  },
  {
    "id": "n5-0267",
    "jp": "困る",
    "reading": "こまる",
    "romaji": "komaru",
    "meaning": "to be bothered, to have difficulty"
  },
  {
    "id": "n5-0268",
    "jp": "これ",
    "reading": "これ",
    "romaji": "kore",
    "meaning": "this one"
  },
  {
    "id": "n5-0269",
    "jp": "～ころ; ～ごろ",
    "reading": "～ころ; ～ごろ",
    "romaji": "～koro; ～goro",
    "meaning": "about, toward, approximately (time)"
  },
  {
    "id": "n5-0270",
    "jp": "今月",
    "reading": "こんげつ",
    "romaji": "kongetsu",
    "meaning": "this month"
  },
  {
    "id": "n5-0271",
    "jp": "今週",
    "reading": "こんしゅう",
    "romaji": "konshuu",
    "meaning": "this week"
  },
  {
    "id": "n5-0272",
    "jp": "こんな",
    "reading": "こんな",
    "romaji": "konna",
    "meaning": "such, like this"
  },
  {
    "id": "n5-0273",
    "jp": "今晩",
    "reading": "こんばん",
    "romaji": "konban",
    "meaning": "tonight, this evening"
  },
  {
    "id": "n5-0274",
    "jp": "さあ",
    "reading": "さあ",
    "romaji": "saa",
    "meaning": "come now, well"
  },
  {
    "id": "n5-0275",
    "jp": "～歳",
    "reading": "～さい",
    "romaji": "～sai",
    "meaning": "~ years old"
  },
  {
    "id": "n5-0276",
    "jp": "財布",
    "reading": "さいふ",
    "romaji": "saifu",
    "meaning": "wallet"
  },
  {
    "id": "n5-0277",
    "jp": "魚",
    "reading": "さかな",
    "romaji": "sakana",
    "meaning": "fish"
  },
  {
    "id": "n5-0278",
    "jp": "先",
    "reading": "さき",
    "romaji": "saki",
    "meaning": "future; recent, previous"
  },
  {
    "id": "n5-0279",
    "jp": "咲く",
    "reading": "さく",
    "romaji": "saku",
    "meaning": "to bloom"
  },
  {
    "id": "n5-0280",
    "jp": "作文",
    "reading": "さくぶん",
    "romaji": "sakubun",
    "meaning": "essay; composition"
  },
  {
    "id": "n5-0281",
    "jp": "差す",
    "reading": "さす",
    "romaji": "sasu",
    "meaning": "to raise (stretch out) hands, to raise (e.g., umbrella)"
  },
  {
    "id": "n5-0282",
    "jp": "～冊",
    "reading": "～さつ",
    "romaji": "～satsu",
    "meaning": "counter for books"
  },
  {
    "id": "n5-0283",
    "jp": "雑誌",
    "reading": "ざっし",
    "romaji": "zasshi",
    "meaning": "magazine, journal"
  },
  {
    "id": "n5-0284",
    "jp": "砂糖",
    "reading": "さとう",
    "romaji": "satou",
    "meaning": "sugar"
  },
  {
    "id": "n5-0285",
    "jp": "寒い",
    "reading": "さむい",
    "romaji": "samui",
    "meaning": "cold (in reference to weather)"
  },
  {
    "id": "n5-0286",
    "jp": "さ来年",
    "reading": "さらいねん",
    "romaji": "sarainen",
    "meaning": "year after next"
  },
  {
    "id": "n5-0287",
    "jp": "～さん",
    "reading": "～さん",
    "romaji": "～san",
    "meaning": "Mr. ~, Ms. ~"
  },
  {
    "id": "n5-0288",
    "jp": "三",
    "reading": "さん",
    "romaji": "san",
    "meaning": "three"
  },
  {
    "id": "n5-0289",
    "jp": "散歩",
    "reading": "さんぽ (する)",
    "romaji": "sanpo (suru)",
    "meaning": "walk, stroll"
  },
  {
    "id": "n5-0290",
    "jp": "四",
    "reading": "し",
    "romaji": "shi",
    "meaning": "four"
  },
  {
    "id": "n5-0291",
    "jp": "～時",
    "reading": "～じ",
    "romaji": "～ji",
    "meaning": "~ o'clock (time)"
  },
  {
    "id": "n5-0292",
    "jp": "塩",
    "reading": "しお",
    "romaji": "shio",
    "meaning": "salt"
  },
  {
    "id": "n5-0293",
    "jp": "しかし",
    "reading": "しかし",
    "romaji": "shikashi",
    "meaning": "however; but"
  },
  {
    "id": "n5-0294",
    "jp": "時間",
    "reading": "じかん",
    "romaji": "jikan",
    "meaning": "time"
  },
  {
    "id": "n5-0295",
    "jp": "～時間",
    "reading": "～じかん",
    "romaji": "～jikan",
    "meaning": "~ hours"
  },
  {
    "id": "n5-0296",
    "jp": "仕事",
    "reading": "しごと",
    "romaji": "shigoto",
    "meaning": "work, job, occupation, employment"
  },
  {
    "id": "n5-0297",
    "jp": "辞書",
    "reading": "じしょ",
    "romaji": "jisho",
    "meaning": "dictionary"
  },
  {
    "id": "n5-0298",
    "jp": "静か",
    "reading": "しずか",
    "romaji": "shizuka",
    "meaning": "quiet, calm"
  },
  {
    "id": "n5-0299",
    "jp": "下",
    "reading": "した",
    "romaji": "shita",
    "meaning": "under, below, beneath"
  },
  {
    "id": "n5-0300",
    "jp": "七",
    "reading": "しち",
    "romaji": "shichi",
    "meaning": "seven"
  },
  {
    "id": "n5-0301",
    "jp": "質問",
    "reading": "しつもん",
    "romaji": "shitsumon",
    "meaning": "question, inquiry"
  },
  {
    "id": "n5-0302",
    "jp": "自転車",
    "reading": "じてんしゃ",
    "romaji": "jitensha",
    "meaning": "bicycle"
  },
  {
    "id": "n5-0303",
    "jp": "自動車",
    "reading": "じどうしゃ",
    "romaji": "jidousha",
    "meaning": "automobile"
  },
  {
    "id": "n5-0304",
    "jp": "死ぬ",
    "reading": "しぬ",
    "romaji": "shinu",
    "meaning": "to die"
  },
  {
    "id": "n5-0305",
    "jp": "字引",
    "reading": "じびき",
    "romaji": "jibiki",
    "meaning": "dictionary"
  },
  {
    "id": "n5-0306",
    "jp": "自分",
    "reading": "じぶん",
    "romaji": "jibun",
    "meaning": "myself, oneself"
  },
  {
    "id": "n5-0307",
    "jp": "閉まる",
    "reading": "しまる",
    "romaji": "shimaru",
    "meaning": "to close, to be closed"
  },
  {
    "id": "n5-0308",
    "jp": "閉める",
    "reading": "しめる",
    "romaji": "shimeru",
    "meaning": "to close, to shut"
  },
  {
    "id": "n5-0309",
    "jp": "締める",
    "reading": "しめる",
    "romaji": "shimeru",
    "meaning": "to tie, to fasten, to tighten"
  },
  {
    "id": "n5-0310",
    "jp": "じゃ; じゃあ",
    "reading": "じゃ; じゃあ",
    "romaji": "ja; jaa",
    "meaning": "well, well then"
  },
  {
    "id": "n5-0311",
    "jp": "写真",
    "reading": "しゃしん",
    "romaji": "shashin",
    "meaning": "a picture; a photograph"
  },
  {
    "id": "n5-0312",
    "jp": "シャツ",
    "reading": "シャツ",
    "romaji": "シャツ",
    "meaning": "shirt"
  },
  {
    "id": "n5-0313",
    "jp": "シャワー",
    "reading": "シャワー",
    "romaji": "シャワー",
    "meaning": "shower"
  },
  {
    "id": "n5-0314",
    "jp": "十",
    "reading": "じゅう",
    "romaji": "juu",
    "meaning": "ten"
  },
  {
    "id": "n5-0315",
    "jp": "～中",
    "reading": "～じゅう",
    "romaji": "～juu",
    "meaning": "during, while"
  },
  {
    "id": "n5-0316",
    "jp": "～週間",
    "reading": "～しゅうかん",
    "romaji": "～shuukan",
    "meaning": "~ weeks"
  },
  {
    "id": "n5-0317",
    "jp": "授業",
    "reading": "じゅぎょう",
    "romaji": "jugyou",
    "meaning": "a class (of school)"
  },
  {
    "id": "n5-0318",
    "jp": "宿題",
    "reading": "しゅくだい",
    "romaji": "shukudai",
    "meaning": "homework"
  },
  {
    "id": "n5-0319",
    "jp": "上手",
    "reading": "じょうず",
    "romaji": "jouzu",
    "meaning": "be good at, skillful"
  },
  {
    "id": "n5-0320",
    "jp": "丈夫",
    "reading": "じょうぶ",
    "romaji": "joubu",
    "meaning": "strong, solid, durable"
  },
  {
    "id": "n5-0321",
    "jp": "醤油",
    "reading": "しょうゆ",
    "romaji": "shouyu",
    "meaning": "soy sauce"
  },
  {
    "id": "n5-0322",
    "jp": "食堂",
    "reading": "しょくどう",
    "romaji": "shokudou",
    "meaning": "cafeteria, dining hall"
  },
  {
    "id": "n5-0323",
    "jp": "知る",
    "reading": "しる",
    "romaji": "shiru",
    "meaning": "to know, to understand"
  },
  {
    "id": "n5-0324",
    "jp": "白",
    "reading": "しろ",
    "romaji": "shiro",
    "meaning": "white"
  },
  {
    "id": "n5-0325",
    "jp": "白い",
    "reading": "しろい",
    "romaji": "shiroi",
    "meaning": "white"
  },
  {
    "id": "n5-0326",
    "jp": "～人",
    "reading": "～じん",
    "romaji": "～jin",
    "meaning": "counter for people"
  },
  {
    "id": "n5-0327",
    "jp": "新聞",
    "reading": "しんぶん",
    "romaji": "shinbun",
    "meaning": "newspaper"
  },
  {
    "id": "n5-0328",
    "jp": "水曜日",
    "reading": "すいようび",
    "romaji": "suiyoubi",
    "meaning": "Wednesday"
  },
  {
    "id": "n5-0329",
    "jp": "吸う",
    "reading": "すう",
    "romaji": "suu",
    "meaning": "to breathe in, to suck"
  },
  {
    "id": "n5-0330",
    "jp": "スカート",
    "reading": "スカート",
    "romaji": "スカート",
    "meaning": "skirt"
  },
  {
    "id": "n5-0331",
    "jp": "好き",
    "reading": "すき",
    "romaji": "suki",
    "meaning": "liking, fondness, love"
  },
  {
    "id": "n5-0332",
    "jp": "～すぎ",
    "reading": "～すぎ",
    "romaji": "～sugi",
    "meaning": "past; to exceed, ~ too much"
  },
  {
    "id": "n5-0333",
    "jp": "少ない",
    "reading": "すくない",
    "romaji": "sukunai",
    "meaning": "a little; a few"
  },
  {
    "id": "n5-0334",
    "jp": "すぐに",
    "reading": "すぐに",
    "romaji": "suguni",
    "meaning": "immediately, soon"
  },
  {
    "id": "n5-0335",
    "jp": "少し",
    "reading": "すこし",
    "romaji": "sukoshi",
    "meaning": "little, few"
  },
  {
    "id": "n5-0336",
    "jp": "涼しい",
    "reading": "すずしい",
    "romaji": "suzushii",
    "meaning": "cool, refreshing (in reference to weather)"
  },
  {
    "id": "n5-0337",
    "jp": "～ずつ",
    "reading": "～ずつ",
    "romaji": "～zutsu",
    "meaning": "at a time"
  },
  {
    "id": "n5-0338",
    "jp": "ストーブ",
    "reading": "ストーブ",
    "romaji": "ストーブ",
    "meaning": "heater (lit: stove)"
  },
  {
    "id": "n5-0339",
    "jp": "スプーン",
    "reading": "スプーン",
    "romaji": "スプーン",
    "meaning": "spoon"
  },
  {
    "id": "n5-0340",
    "jp": "スポーツ",
    "reading": "スポーツ",
    "romaji": "スポーツ",
    "meaning": "sport(s)"
  },
  {
    "id": "n5-0341",
    "jp": "ズボン",
    "reading": "ズボン",
    "romaji": "ズボン",
    "meaning": "trousers"
  },
  {
    "id": "n5-0342",
    "jp": "住む",
    "reading": "すむ",
    "romaji": "sumu",
    "meaning": "to reside, to live in"
  },
  {
    "id": "n5-0343",
    "jp": "する",
    "reading": "する",
    "romaji": "suru",
    "meaning": "to do, to try; to wear small items (e.g., necktie, watch, etc.)"
  },
  {
    "id": "n5-0344",
    "jp": "座る",
    "reading": "すわる",
    "romaji": "suwaru",
    "meaning": "to sit"
  },
  {
    "id": "n5-0345",
    "jp": "背",
    "reading": "せい",
    "romaji": "sei",
    "meaning": "(one's) height, stature"
  },
  {
    "id": "n5-0346",
    "jp": "生徒",
    "reading": "せいと",
    "romaji": "seito",
    "meaning": "student; pupil"
  },
  {
    "id": "n5-0347",
    "jp": "セーター",
    "reading": "セーター",
    "romaji": "セーター",
    "meaning": "sweater"
  },
  {
    "id": "n5-0348",
    "jp": "石鹸",
    "reading": "せっけん",
    "romaji": "sekken",
    "meaning": "soap"
  },
  {
    "id": "n5-0349",
    "jp": "背広",
    "reading": "せびろ",
    "romaji": "sebiro",
    "meaning": "men's suit"
  },
  {
    "id": "n5-0350",
    "jp": "狭い",
    "reading": "せまい",
    "romaji": "semai",
    "meaning": "narrow; not spacious"
  },
  {
    "id": "n5-0351",
    "jp": "ゼロ",
    "reading": "ゼロ",
    "romaji": "ゼロ",
    "meaning": "zero"
  },
  {
    "id": "n5-0352",
    "jp": "千",
    "reading": "せん",
    "romaji": "sen",
    "meaning": "thousand"
  },
  {
    "id": "n5-0353",
    "jp": "先月",
    "reading": "せんげつ",
    "romaji": "sengetsu",
    "meaning": "last month"
  },
  {
    "id": "n5-0354",
    "jp": "先週",
    "reading": "せんしゅう",
    "romaji": "senshuu",
    "meaning": "last week"
  },
  {
    "id": "n5-0355",
    "jp": "先生",
    "reading": "せんせい",
    "romaji": "sensei",
    "meaning": "teacher, professor; master; doctor"
  },
  {
    "id": "n5-0356",
    "jp": "洗濯",
    "reading": "せんたく",
    "romaji": "sentaku",
    "meaning": "washing, laundry"
  },
  {
    "id": "n5-0357",
    "jp": "全部",
    "reading": "ぜんぶ",
    "romaji": "zenbu",
    "meaning": "all, entire, whole"
  },
  {
    "id": "n5-0358",
    "jp": "そう; そうです",
    "reading": "そう; そうです",
    "romaji": "sou; soudesu",
    "meaning": "yes; appears, to be the case"
  },
  {
    "id": "n5-0359",
    "jp": "掃除",
    "reading": "そうじ (する)",
    "romaji": "souji (suru)",
    "meaning": "cleaning, sweeping"
  },
  {
    "id": "n5-0360",
    "jp": "そうして; そして",
    "reading": "そうして; そして",
    "romaji": "soushite; soshite",
    "meaning": "and, like that"
  },
  {
    "id": "n5-0361",
    "jp": "そこ",
    "reading": "そこ",
    "romaji": "soko",
    "meaning": "that place, there; bottom, sole"
  },
  {
    "id": "n5-0362",
    "jp": "そちら",
    "reading": "そちら",
    "romaji": "sochira",
    "meaning": "over there"
  },
  {
    "id": "n5-0363",
    "jp": "そっち",
    "reading": "そっち",
    "romaji": "sotchi",
    "meaning": "over there"
  },
  {
    "id": "n5-0364",
    "jp": "外",
    "reading": "そと",
    "romaji": "soto",
    "meaning": "outside, exterior"
  },
  {
    "id": "n5-0365",
    "jp": "その",
    "reading": "その",
    "romaji": "sono",
    "meaning": "that"
  },
  {
    "id": "n5-0366",
    "jp": "そば",
    "reading": "そば",
    "romaji": "soba",
    "meaning": "near, close, beside; Japanese traditional buckwheat noodle"
  },
  {
    "id": "n5-0367",
    "jp": "空",
    "reading": "そら",
    "romaji": "sora",
    "meaning": "sky"
  },
  {
    "id": "n5-0368",
    "jp": "それ",
    "reading": "それ",
    "romaji": "sore",
    "meaning": "that one"
  },
  {
    "id": "n5-0369",
    "jp": "それから",
    "reading": "それから",
    "romaji": "sorekara",
    "meaning": "and then, after that"
  },
  {
    "id": "n5-0370",
    "jp": "それでは",
    "reading": "それでは",
    "romaji": "soredeha",
    "meaning": "in that situation, well then..."
  },
  {
    "id": "n5-0371",
    "jp": "～台",
    "reading": "～だい",
    "romaji": "～dai",
    "meaning": "counter for vehicles; machines"
  },
  {
    "id": "n5-0372",
    "jp": "大学",
    "reading": "だいがく",
    "romaji": "daigaku",
    "meaning": "college; university"
  },
  {
    "id": "n5-0373",
    "jp": "大使館",
    "reading": "たいしかん",
    "romaji": "taishikan",
    "meaning": "embassy"
  },
  {
    "id": "n5-0374",
    "jp": "大丈夫",
    "reading": "だいじょうぶ",
    "romaji": "daijoubu",
    "meaning": "It's ok (all right); No need to worry; Everything is under control"
  },
  {
    "id": "n5-0375",
    "jp": "大好き",
    "reading": "だいすき",
    "romaji": "daisuki",
    "meaning": "very like-able, like very much"
  },
  {
    "id": "n5-0376",
    "jp": "大切",
    "reading": "たいせつ",
    "romaji": "taisetsu",
    "meaning": "important"
  },
  {
    "id": "n5-0377",
    "jp": "台所",
    "reading": "だいどころ",
    "romaji": "daidokoro",
    "meaning": "kitchen"
  },
  {
    "id": "n5-0378",
    "jp": "大変",
    "reading": "たいへん",
    "romaji": "taihen",
    "meaning": "very; difficult, hard"
  },
  {
    "id": "n5-0379",
    "jp": "高い",
    "reading": "たかい",
    "romaji": "takai",
    "meaning": "tall, high; expensive"
  },
  {
    "id": "n5-0380",
    "jp": "～だけ",
    "reading": "～だけ",
    "romaji": "～dake",
    "meaning": "only ~, just ~, as ~"
  },
  {
    "id": "n5-0381",
    "jp": "沢山",
    "reading": "たくさん",
    "romaji": "takusan",
    "meaning": "many, much"
  },
  {
    "id": "n5-0382",
    "jp": "タクシー",
    "reading": "タクシー",
    "romaji": "タクシー",
    "meaning": "taxi"
  },
  {
    "id": "n5-0383",
    "jp": "出す",
    "reading": "だす",
    "romaji": "dasu",
    "meaning": "to take (something) out; to hand in (something)"
  },
  {
    "id": "n5-0384",
    "jp": "～たち",
    "reading": "～たち",
    "romaji": "～tachi",
    "meaning": "plural suffix"
  },
  {
    "id": "n5-0385",
    "jp": "立つ",
    "reading": "たつ",
    "romaji": "tatsu",
    "meaning": "to stand up"
  },
  {
    "id": "n5-0386",
    "jp": "たて",
    "reading": "たて",
    "romaji": "tate",
    "meaning": "length, height"
  },
  {
    "id": "n5-0387",
    "jp": "建物",
    "reading": "たてもの",
    "romaji": "tatemono",
    "meaning": "building"
  },
  {
    "id": "n5-0388",
    "jp": "楽しい",
    "reading": "たのしい",
    "romaji": "tanoshii",
    "meaning": "enjoyable, fun"
  },
  {
    "id": "n5-0389",
    "jp": "頼む",
    "reading": "たのむ",
    "romaji": "tanomu",
    "meaning": "to request, to ask (a favor)"
  },
  {
    "id": "n5-0390",
    "jp": "たばこ",
    "reading": "たばこ",
    "romaji": "tabako",
    "meaning": "tobacco, cigarettes"
  },
  {
    "id": "n5-0391",
    "jp": "多分",
    "reading": "たぶん",
    "romaji": "tabun",
    "meaning": "perhaps, probably, maybe"
  },
  {
    "id": "n5-0392",
    "jp": "食べ物",
    "reading": "たべもの",
    "romaji": "tabemono",
    "meaning": "food"
  },
  {
    "id": "n5-0393",
    "jp": "食べる",
    "reading": "たべる",
    "romaji": "taberu",
    "meaning": "to eat"
  },
  {
    "id": "n5-0394",
    "jp": "卵",
    "reading": "たまご",
    "romaji": "tamago",
    "meaning": "egg"
  },
  {
    "id": "n5-0395",
    "jp": "誰",
    "reading": "だれ",
    "romaji": "dare",
    "meaning": "who"
  },
  {
    "id": "n5-0396",
    "jp": "誰か",
    "reading": "だれか",
    "romaji": "dareka",
    "meaning": "someone"
  },
  {
    "id": "n5-0397",
    "jp": "誕生日",
    "reading": "たんじょうび",
    "romaji": "tanjoubi",
    "meaning": "birthday"
  },
  {
    "id": "n5-0398",
    "jp": "段々",
    "reading": "だんだん",
    "romaji": "dandan",
    "meaning": "gradually, by degrees"
  },
  {
    "id": "n5-0399",
    "jp": "小さい",
    "reading": "ちいさい",
    "romaji": "chiisai",
    "meaning": "small, little"
  },
  {
    "id": "n5-0400",
    "jp": "小さな",
    "reading": "ちいさな",
    "romaji": "chiisana",
    "meaning": "small, little"
  },
  {
    "id": "n5-0401",
    "jp": "近い",
    "reading": "ちかい",
    "romaji": "chikai",
    "meaning": "near, close by, short"
  },
  {
    "id": "n5-0402",
    "jp": "違う",
    "reading": "ちがう",
    "romaji": "chigau",
    "meaning": "to be different; to differ; wrong"
  },
  {
    "id": "n5-0403",
    "jp": "近く",
    "reading": "ちかく",
    "romaji": "chikaku",
    "meaning": "nearby; in the neighborhood"
  },
  {
    "id": "n5-0404",
    "jp": "地下鉄",
    "reading": "ちかてつ",
    "romaji": "chikatetsu",
    "meaning": "underground train, subway"
  },
  {
    "id": "n5-0405",
    "jp": "地図",
    "reading": "ちず",
    "romaji": "chizu",
    "meaning": "a map"
  },
  {
    "id": "n5-0406",
    "jp": "父",
    "reading": "ちち",
    "romaji": "chichi",
    "meaning": "(my) father"
  },
  {
    "id": "n5-0407",
    "jp": "茶色",
    "reading": "ちゃいろ",
    "romaji": "chairo",
    "meaning": "brown"
  },
  {
    "id": "n5-0408",
    "jp": "茶碗",
    "reading": "ちゃわん",
    "romaji": "chawan",
    "meaning": "rice bowl"
  },
  {
    "id": "n5-0409",
    "jp": "～中",
    "reading": "～ちゅう",
    "romaji": "～chuu",
    "meaning": "during, while ~ing"
  },
  {
    "id": "n5-0410",
    "jp": "丁度",
    "reading": "ちょうど",
    "romaji": "choudo",
    "meaning": "just, right, exactly"
  },
  {
    "id": "n5-0411",
    "jp": "ちょっと",
    "reading": "ちょっと",
    "romaji": "chotto",
    "meaning": "a little, somewhat; just a little, somewhat"
  },
  {
    "id": "n5-0412",
    "jp": "一日",
    "reading": "ついたち",
    "romaji": "tsuitachi",
    "meaning": "one day; first day of the month"
  },
  {
    "id": "n5-0413",
    "jp": "使う",
    "reading": "つかう",
    "romaji": "tsukau",
    "meaning": "to use"
  },
  {
    "id": "n5-0414",
    "jp": "疲れる",
    "reading": "つかれる",
    "romaji": "tsukareru",
    "meaning": "to get (become) tired; to become fatigued"
  },
  {
    "id": "n5-0415",
    "jp": "次",
    "reading": "つぎ",
    "romaji": "tsugi",
    "meaning": "next"
  },
  {
    "id": "n5-0416",
    "jp": "着く",
    "reading": "つく",
    "romaji": "tsuku",
    "meaning": "to arrive at, to reach"
  },
  {
    "id": "n5-0417",
    "jp": "机",
    "reading": "つくえ",
    "romaji": "tsukue",
    "meaning": "desk"
  },
  {
    "id": "n5-0418",
    "jp": "作る",
    "reading": "つくる",
    "romaji": "tsukuru",
    "meaning": "to make, to create"
  },
  {
    "id": "n5-0419",
    "jp": "つける",
    "reading": "つける",
    "romaji": "tsukeru",
    "meaning": "to turn on (e.g., a light); to take"
  },
  {
    "id": "n5-0420",
    "jp": "勤める",
    "reading": "つとめる",
    "romaji": "tsutomeru",
    "meaning": "to work (for)"
  },
  {
    "id": "n5-0421",
    "jp": "つまらない",
    "reading": "つまらない",
    "romaji": "tsumaranai",
    "meaning": "boring, dull; insignificant"
  },
  {
    "id": "n5-0422",
    "jp": "冷たい",
    "reading": "つめたい",
    "romaji": "tsumetai",
    "meaning": "cold (things, people)"
  },
  {
    "id": "n5-0423",
    "jp": "強い",
    "reading": "つよい",
    "romaji": "tsuyoi",
    "meaning": "strong, powerful"
  },
  {
    "id": "n5-0424",
    "jp": "手",
    "reading": "て",
    "romaji": "te",
    "meaning": "hand"
  },
  {
    "id": "n5-0425",
    "jp": "テープ",
    "reading": "テープ",
    "romaji": "テープ",
    "meaning": "tape"
  },
  {
    "id": "n5-0426",
    "jp": "テープレコーダー",
    "reading": "テープレコーダー",
    "romaji": "テープレコーダー",
    "meaning": "tape recorder"
  },
  {
    "id": "n5-0427",
    "jp": "テーブル",
    "reading": "テーブル",
    "romaji": "テーブル",
    "meaning": "table"
  },
  {
    "id": "n5-0428",
    "jp": "出かける",
    "reading": "でかける",
    "romaji": "dekakeru",
    "meaning": "to go out; to depart"
  },
  {
    "id": "n5-0429",
    "jp": "手紙",
    "reading": "てがみ",
    "romaji": "tegami",
    "meaning": "letter"
  },
  {
    "id": "n5-0430",
    "jp": "できる",
    "reading": "できる",
    "romaji": "dekiru",
    "meaning": "to be able to (to accomplish)"
  },
  {
    "id": "n5-0431",
    "jp": "出口",
    "reading": "でぐち",
    "romaji": "deguchi",
    "meaning": "an exit"
  },
  {
    "id": "n5-0432",
    "jp": "テスト",
    "reading": "テスト",
    "romaji": "テスト",
    "meaning": "test"
  },
  {
    "id": "n5-0433",
    "jp": "では",
    "reading": "では",
    "romaji": "deha",
    "meaning": "then, well, so"
  },
  {
    "id": "n5-0434",
    "jp": "デパート",
    "reading": "デパート",
    "romaji": "デパート",
    "meaning": "(abbr.) department store"
  },
  {
    "id": "n5-0435",
    "jp": "でも",
    "reading": "でも",
    "romaji": "demo",
    "meaning": "but, however"
  },
  {
    "id": "n5-0436",
    "jp": "出る",
    "reading": "でる",
    "romaji": "deru",
    "meaning": "to appear, to leave"
  },
  {
    "id": "n5-0437",
    "jp": "テレビ",
    "reading": "テレビ",
    "romaji": "テレビ",
    "meaning": "television, TV"
  },
  {
    "id": "n5-0438",
    "jp": "天気",
    "reading": "てんき",
    "romaji": "tenki",
    "meaning": "weather"
  },
  {
    "id": "n5-0439",
    "jp": "電気",
    "reading": "でんき",
    "romaji": "denki",
    "meaning": "electricity, (electric) light"
  },
  {
    "id": "n5-0440",
    "jp": "電車",
    "reading": "でんしゃ",
    "romaji": "densha",
    "meaning": "electric train"
  },
  {
    "id": "n5-0441",
    "jp": "電話",
    "reading": "でんわ",
    "romaji": "denwa",
    "meaning": "a telephone"
  },
  {
    "id": "n5-0442",
    "jp": "戸",
    "reading": "と",
    "romaji": "to",
    "meaning": "door (Japanese style)"
  },
  {
    "id": "n5-0443",
    "jp": "～度",
    "reading": "～ど",
    "romaji": "～do",
    "meaning": "counter for occurrences; ~ degree; ~ point"
  },
  {
    "id": "n5-0444",
    "jp": "ドア",
    "reading": "ドア",
    "romaji": "ドア",
    "meaning": "door (Western style)"
  },
  {
    "id": "n5-0445",
    "jp": "トイレ",
    "reading": "トイレ",
    "romaji": "トイレ",
    "meaning": "bathroom; toilet"
  },
  {
    "id": "n5-0446",
    "jp": "どう",
    "reading": "どう",
    "romaji": "dou",
    "meaning": "how, in what way"
  },
  {
    "id": "n5-0447",
    "jp": "どうして",
    "reading": "どうして",
    "romaji": "doushite",
    "meaning": "why, for what reason"
  },
  {
    "id": "n5-0448",
    "jp": "どうぞ",
    "reading": "どうぞ",
    "romaji": "douzo",
    "meaning": "please, kindly, by all means"
  },
  {
    "id": "n5-0449",
    "jp": "動物",
    "reading": "どうぶつ",
    "romaji": "doubutsu",
    "meaning": "animal"
  },
  {
    "id": "n5-0450",
    "jp": "どうも",
    "reading": "どうも",
    "romaji": "doumo",
    "meaning": "Thank you; somehow; no matter how hard one may try"
  },
  {
    "id": "n5-0451",
    "jp": "十",
    "reading": "(〜を) とお",
    "romaji": "(〜wo) too",
    "meaning": "ten (~)"
  },
  {
    "id": "n5-0452",
    "jp": "遠い",
    "reading": "とおい",
    "romaji": "tooi",
    "meaning": "far (away), distant"
  },
  {
    "id": "n5-0453",
    "jp": "十日",
    "reading": "とおか",
    "romaji": "tooka",
    "meaning": "ten days; tenth day of the month"
  },
  {
    "id": "n5-0454",
    "jp": "～時",
    "reading": "～とき",
    "romaji": "～toki",
    "meaning": "at the time of ~"
  },
  {
    "id": "n5-0455",
    "jp": "時々",
    "reading": "ときどき",
    "romaji": "tokidoki",
    "meaning": "sometimes"
  },
  {
    "id": "n5-0456",
    "jp": "時計",
    "reading": "とけい",
    "romaji": "tokei",
    "meaning": "a watch; a clock"
  },
  {
    "id": "n5-0457",
    "jp": "どこ",
    "reading": "どこ",
    "romaji": "doko",
    "meaning": "where, what place"
  },
  {
    "id": "n5-0458",
    "jp": "所",
    "reading": "ところ",
    "romaji": "tokoro",
    "meaning": "place"
  },
  {
    "id": "n5-0459",
    "jp": "年",
    "reading": "とし",
    "romaji": "toshi",
    "meaning": "year, age"
  },
  {
    "id": "n5-0460",
    "jp": "図書館",
    "reading": "としょかん",
    "romaji": "toshokan",
    "meaning": "library"
  },
  {
    "id": "n5-0461",
    "jp": "どちら",
    "reading": "どちら",
    "romaji": "dochira",
    "meaning": "which (one) (way); where (polite)"
  },
  {
    "id": "n5-0462",
    "jp": "どっち",
    "reading": "どっち",
    "romaji": "dotchi",
    "meaning": "which one, which way"
  },
  {
    "id": "n5-0463",
    "jp": "とても",
    "reading": "とても",
    "romaji": "totemo",
    "meaning": "very (much), greatly, exceedingly"
  },
  {
    "id": "n5-0464",
    "jp": "どなた",
    "reading": "どなた",
    "romaji": "donata",
    "meaning": "who"
  },
  {
    "id": "n5-0465",
    "jp": "隣",
    "reading": "となり",
    "romaji": "tonari",
    "meaning": "next to, next door to"
  },
  {
    "id": "n5-0466",
    "jp": "どの",
    "reading": "どの",
    "romaji": "dono",
    "meaning": "which"
  },
  {
    "id": "n5-0467",
    "jp": "飛ぶ",
    "reading": "とぶ",
    "romaji": "tobu",
    "meaning": "to fly, to hop"
  },
  {
    "id": "n5-0468",
    "jp": "止まる",
    "reading": "とまる",
    "romaji": "tomaru",
    "meaning": "to come to a halt"
  },
  {
    "id": "n5-0469",
    "jp": "友達",
    "reading": "ともだち",
    "romaji": "tomodachi",
    "meaning": "friend"
  },
  {
    "id": "n5-0470",
    "jp": "土曜日",
    "reading": "どようび",
    "romaji": "doyoubi",
    "meaning": "Saturday"
  },
  {
    "id": "n5-0471",
    "jp": "鳥",
    "reading": "とり",
    "romaji": "tori",
    "meaning": "chicken (lit., bird)"
  },
  {
    "id": "n5-0472",
    "jp": "鶏肉",
    "reading": "とりにく",
    "romaji": "toriniku",
    "meaning": "chicken meat"
  },
  {
    "id": "n5-0473",
    "jp": "取る",
    "reading": "とる",
    "romaji": "toru",
    "meaning": "to take (a class); to get (a grade)"
  },
  {
    "id": "n5-0474",
    "jp": "撮る",
    "reading": "とる",
    "romaji": "toru",
    "meaning": "to take (a photo), to make (a film)"
  },
  {
    "id": "n5-0475",
    "jp": "どれ",
    "reading": "どれ",
    "romaji": "dore",
    "meaning": "which one"
  },
  {
    "id": "n5-0476",
    "jp": "どんな",
    "reading": "どんな",
    "romaji": "donna",
    "meaning": "what, what kind of"
  },
  {
    "id": "n5-0477",
    "jp": "ない",
    "reading": "ない",
    "romaji": "nai",
    "meaning": "there isn't, doesn't have"
  },
  {
    "id": "n5-0478",
    "jp": "ナイフ",
    "reading": "ナイフ",
    "romaji": "ナイフ",
    "meaning": "knife"
  },
  {
    "id": "n5-0479",
    "jp": "中",
    "reading": "なか",
    "romaji": "naka",
    "meaning": "inside, middle, among"
  },
  {
    "id": "n5-0480",
    "jp": "長い",
    "reading": "ながい",
    "romaji": "nagai",
    "meaning": "long, lengthy"
  },
  {
    "id": "n5-0481",
    "jp": "鳴く",
    "reading": "なく",
    "romaji": "naku",
    "meaning": "to make sound (animal)"
  },
  {
    "id": "n5-0482",
    "jp": "無くす",
    "reading": "なくす",
    "romaji": "nakusu",
    "meaning": "to lose something"
  },
  {
    "id": "n5-0483",
    "jp": "なぜ",
    "reading": "なぜ",
    "romaji": "naze",
    "meaning": "why (same as どうして)"
  },
  {
    "id": "n5-0484",
    "jp": "夏",
    "reading": "なつ",
    "romaji": "natsu",
    "meaning": "summer"
  },
  {
    "id": "n5-0485",
    "jp": "夏休み",
    "reading": "なつやすみ",
    "romaji": "natsuyasumi",
    "meaning": "summer vacation"
  },
  {
    "id": "n5-0486",
    "jp": "～など",
    "reading": "～など",
    "romaji": "～nado",
    "meaning": "et cetera"
  },
  {
    "id": "n5-0487",
    "jp": "七つ",
    "reading": "ななつ",
    "romaji": "nanatsu",
    "meaning": "seven things"
  },
  {
    "id": "n5-0488",
    "jp": "何",
    "reading": "なん; なに",
    "romaji": "nan; nani",
    "meaning": "what"
  },
  {
    "id": "n5-0489",
    "jp": "七日",
    "reading": "なのか",
    "romaji": "nanoka",
    "meaning": "seven days; seventh day (of the month)"
  },
  {
    "id": "n5-0490",
    "jp": "名前",
    "reading": "なまえ",
    "romaji": "namae",
    "meaning": "name"
  },
  {
    "id": "n5-0491",
    "jp": "習う",
    "reading": "ならう",
    "romaji": "narau",
    "meaning": "to learn"
  },
  {
    "id": "n5-0492",
    "jp": "並ぶ",
    "reading": "ならぶ",
    "romaji": "narabu",
    "meaning": "to line up, to stand in a line (v.i.)"
  },
  {
    "id": "n5-0493",
    "jp": "並べる",
    "reading": "ならべる",
    "romaji": "naraberu",
    "meaning": "to put (things) side by side; to line up"
  },
  {
    "id": "n5-0494",
    "jp": "なる",
    "reading": "なる",
    "romaji": "naru",
    "meaning": "to become"
  },
  {
    "id": "n5-0495",
    "jp": "何～",
    "reading": "なん～",
    "romaji": "nan～",
    "meaning": "what sort of ~"
  },
  {
    "id": "n5-0496",
    "jp": "二",
    "reading": "に",
    "romaji": "ni",
    "meaning": "two"
  },
  {
    "id": "n5-0497",
    "jp": "にぎやか",
    "reading": "にぎやか",
    "romaji": "nigiyaka",
    "meaning": "bustling, busy"
  },
  {
    "id": "n5-0498",
    "jp": "肉",
    "reading": "にく",
    "romaji": "niku",
    "meaning": "meat"
  },
  {
    "id": "n5-0499",
    "jp": "西",
    "reading": "にし",
    "romaji": "nishi",
    "meaning": "west"
  },
  {
    "id": "n5-0500",
    "jp": "～日",
    "reading": "～にち",
    "romaji": "～nichi",
    "meaning": "~ day of the month, for ~ days"
  },
  {
    "id": "n5-0501",
    "jp": "日曜日",
    "reading": "にちようび",
    "romaji": "nichiyoubi",
    "meaning": "Sunday"
  },
  {
    "id": "n5-0502",
    "jp": "荷物",
    "reading": "にもつ",
    "romaji": "nimotsu",
    "meaning": "luggage; baggage"
  },
  {
    "id": "n5-0503",
    "jp": "ニュース",
    "reading": "ニュース",
    "romaji": "ニュース",
    "meaning": "news"
  },
  {
    "id": "n5-0504",
    "jp": "庭",
    "reading": "にわ",
    "romaji": "niwa",
    "meaning": "garden"
  },
  {
    "id": "n5-0505",
    "jp": "～人",
    "reading": "～にん",
    "romaji": "～nin",
    "meaning": "counter for people"
  },
  {
    "id": "n5-0506",
    "jp": "脱ぐ",
    "reading": "ぬぐ",
    "romaji": "nugu",
    "meaning": "to take off (clothes)"
  },
  {
    "id": "n5-0507",
    "jp": "温い",
    "reading": "ぬるい",
    "romaji": "nurui",
    "meaning": "lukewarm"
  },
  {
    "id": "n5-0508",
    "jp": "ネクタイ",
    "reading": "ネクタイ",
    "romaji": "ネクタイ",
    "meaning": "tie, necktie"
  },
  {
    "id": "n5-0509",
    "jp": "猫",
    "reading": "ねこ",
    "romaji": "neko",
    "meaning": "cat"
  },
  {
    "id": "n5-0510",
    "jp": "寝る",
    "reading": "ねる",
    "romaji": "neru",
    "meaning": "to sleep; to go to sleep; to go to bed"
  },
  {
    "id": "n5-0511",
    "jp": "～年",
    "reading": "～ねん",
    "romaji": "～nen",
    "meaning": "~ years"
  },
  {
    "id": "n5-0512",
    "jp": "ノート",
    "reading": "ノート",
    "romaji": "ノート",
    "meaning": "notebook"
  },
  {
    "id": "n5-0513",
    "jp": "登る",
    "reading": "のぼる",
    "romaji": "noboru",
    "meaning": "to climb"
  },
  {
    "id": "n5-0514",
    "jp": "飲み物",
    "reading": "のみもの",
    "romaji": "nomimono",
    "meaning": "drink, beverage"
  },
  {
    "id": "n5-0515",
    "jp": "飲む",
    "reading": "のむ",
    "romaji": "nomu",
    "meaning": "to drink"
  },
  {
    "id": "n5-0516",
    "jp": "乗る",
    "reading": "のる",
    "romaji": "noru",
    "meaning": "to get on, to ride in, to board"
  },
  {
    "id": "n5-0517",
    "jp": "歯",
    "reading": "は",
    "romaji": "ha",
    "meaning": "tooth"
  },
  {
    "id": "n5-0518",
    "jp": "パーティー",
    "reading": "パーティー",
    "romaji": "パーティー",
    "meaning": "a party"
  },
  {
    "id": "n5-0519",
    "jp": "はい",
    "reading": "はい",
    "romaji": "hai",
    "meaning": "yes"
  },
  {
    "id": "n5-0520",
    "jp": "～杯",
    "reading": "～はい",
    "romaji": "～hai",
    "meaning": "counter for cupfuls"
  },
  {
    "id": "n5-0521",
    "jp": "灰皿",
    "reading": "はいざら",
    "romaji": "haizara",
    "meaning": "ashtray"
  },
  {
    "id": "n5-0522",
    "jp": "入る",
    "reading": "はいる",
    "romaji": "hairu",
    "meaning": "to enter, to contain, to hold"
  },
  {
    "id": "n5-0523",
    "jp": "葉書",
    "reading": "はがき",
    "romaji": "hagaki",
    "meaning": "postcard"
  },
  {
    "id": "n5-0524",
    "jp": "はく",
    "reading": "はく",
    "romaji": "haku",
    "meaning": "to put on (items below your waist)"
  },
  {
    "id": "n5-0525",
    "jp": "箱",
    "reading": "はこ",
    "romaji": "hako",
    "meaning": "box"
  },
  {
    "id": "n5-0526",
    "jp": "橋",
    "reading": "はし",
    "romaji": "hashi",
    "meaning": "bridge"
  },
  {
    "id": "n5-0527",
    "jp": "箸",
    "reading": "はし",
    "romaji": "hashi",
    "meaning": "chopsticks"
  },
  {
    "id": "n5-0528",
    "jp": "始まる",
    "reading": "はじまる",
    "romaji": "hajimaru",
    "meaning": "(something) begins"
  },
  {
    "id": "n5-0529",
    "jp": "初め; 始め",
    "reading": "はじめ",
    "romaji": "hajime",
    "meaning": "beginning, start"
  },
  {
    "id": "n5-0530",
    "jp": "初めて",
    "reading": "はじめて",
    "romaji": "hajimete",
    "meaning": "for the first time"
  },
  {
    "id": "n5-0531",
    "jp": "走る",
    "reading": "はしる",
    "romaji": "hashiru",
    "meaning": "to run"
  },
  {
    "id": "n5-0532",
    "jp": "バス",
    "reading": "バス",
    "romaji": "バス",
    "meaning": "bus; bath; bass"
  },
  {
    "id": "n5-0533",
    "jp": "バター",
    "reading": "バター",
    "romaji": "バター",
    "meaning": "butter"
  },
  {
    "id": "n5-0534",
    "jp": "二十歳",
    "reading": "はたち",
    "romaji": "hatachi",
    "meaning": "20 years old"
  },
  {
    "id": "n5-0535",
    "jp": "働く",
    "reading": "はたらく",
    "romaji": "hataraku",
    "meaning": "to work"
  },
  {
    "id": "n5-0536",
    "jp": "八",
    "reading": "はち",
    "romaji": "hachi",
    "meaning": "eight"
  },
  {
    "id": "n5-0537",
    "jp": "二十日",
    "reading": "はつか",
    "romaji": "hatsuka",
    "meaning": "twenty days, twentieth (day of the month)"
  },
  {
    "id": "n5-0538",
    "jp": "花",
    "reading": "はな",
    "romaji": "hana",
    "meaning": "flower"
  },
  {
    "id": "n5-0539",
    "jp": "鼻",
    "reading": "はな",
    "romaji": "hana",
    "meaning": "nose"
  },
  {
    "id": "n5-0540",
    "jp": "話",
    "reading": "はなし",
    "romaji": "hanashi",
    "meaning": "talk (chat), story"
  },
  {
    "id": "n5-0541",
    "jp": "話す",
    "reading": "はなす",
    "romaji": "hanasu",
    "meaning": "to speak"
  },
  {
    "id": "n5-0542",
    "jp": "母",
    "reading": "はは",
    "romaji": "haha",
    "meaning": "(my) mother"
  },
  {
    "id": "n5-0543",
    "jp": "早い",
    "reading": "はやい",
    "romaji": "hayai",
    "meaning": "early"
  },
  {
    "id": "n5-0544",
    "jp": "速い",
    "reading": "はやい",
    "romaji": "hayai",
    "meaning": "fast, quick"
  },
  {
    "id": "n5-0545",
    "jp": "春",
    "reading": "はる",
    "romaji": "haru",
    "meaning": "spring"
  },
  {
    "id": "n5-0546",
    "jp": "貼る",
    "reading": "はる",
    "romaji": "haru",
    "meaning": "to post; to paste; to attach"
  },
  {
    "id": "n5-0547",
    "jp": "晴れ",
    "reading": "はれ",
    "romaji": "hare",
    "meaning": "clear (sunny) weather"
  },
  {
    "id": "n5-0548",
    "jp": "晴れる",
    "reading": "はれる",
    "romaji": "hareru",
    "meaning": "to be sunny"
  },
  {
    "id": "n5-0549",
    "jp": "半",
    "reading": "はん",
    "romaji": "han",
    "meaning": "half (e.g., にじはん | half-past two)"
  },
  {
    "id": "n5-0550",
    "jp": "晩",
    "reading": "ばん",
    "romaji": "ban",
    "meaning": "evening"
  },
  {
    "id": "n5-0551",
    "jp": "～番",
    "reading": "～ばん",
    "romaji": "～ban",
    "meaning": "~st; ~th best"
  },
  {
    "id": "n5-0552",
    "jp": "パン",
    "reading": "パン",
    "romaji": "パン",
    "meaning": "bread"
  },
  {
    "id": "n5-0553",
    "jp": "ハンカチ",
    "reading": "ハンカチ",
    "romaji": "ハンカチ",
    "meaning": "handkerchief"
  },
  {
    "id": "n5-0554",
    "jp": "番号",
    "reading": "ばんごう",
    "romaji": "bangou",
    "meaning": "number, series of digits"
  },
  {
    "id": "n5-0555",
    "jp": "晩御飯",
    "reading": "ばんごはん",
    "romaji": "bangohan",
    "meaning": "dinner, evening meal"
  },
  {
    "id": "n5-0556",
    "jp": "半分",
    "reading": "はんぶん",
    "romaji": "hanbun",
    "meaning": "half"
  },
  {
    "id": "n5-0557",
    "jp": "東",
    "reading": "ひがし",
    "romaji": "higashi",
    "meaning": "east"
  },
  {
    "id": "n5-0558",
    "jp": "～匹",
    "reading": "～ひき",
    "romaji": "～hiki",
    "meaning": "counter for small animals"
  },
  {
    "id": "n5-0559",
    "jp": "引く",
    "reading": "ひく",
    "romaji": "hiku",
    "meaning": "to pull, to draw; subtract"
  },
  {
    "id": "n5-0560",
    "jp": "弾く",
    "reading": "ひく",
    "romaji": "hiku",
    "meaning": "to play (a string instrument or piano)"
  },
  {
    "id": "n5-0561",
    "jp": "低い",
    "reading": "ひくい",
    "romaji": "hikui",
    "meaning": "short, low"
  },
  {
    "id": "n5-0562",
    "jp": "飛行機",
    "reading": "ひこうき",
    "romaji": "hikouki",
    "meaning": "airplane"
  },
  {
    "id": "n5-0563",
    "jp": "左",
    "reading": "ひだり",
    "romaji": "hidari",
    "meaning": "left hand side"
  },
  {
    "id": "n5-0564",
    "jp": "人",
    "reading": "ひと",
    "romaji": "hito",
    "meaning": "man, person"
  },
  {
    "id": "n5-0565",
    "jp": "一つ",
    "reading": "ひとつ",
    "romaji": "hitotsu",
    "meaning": "one thing"
  },
  {
    "id": "n5-0566",
    "jp": "一月",
    "reading": "ひとつき",
    "romaji": "hitotsuki",
    "meaning": "one month"
  },
  {
    "id": "n5-0567",
    "jp": "一人",
    "reading": "ひとり",
    "romaji": "hitori",
    "meaning": "one person"
  },
  {
    "id": "n5-0568",
    "jp": "暇",
    "reading": "ひま",
    "romaji": "hima",
    "meaning": "free time, leisure"
  },
  {
    "id": "n5-0569",
    "jp": "百",
    "reading": "ひゃく",
    "romaji": "hyaku",
    "meaning": "hundred"
  },
  {
    "id": "n5-0570",
    "jp": "病院",
    "reading": "びょういん",
    "romaji": "byouin",
    "meaning": "hospital"
  },
  {
    "id": "n5-0571",
    "jp": "病気",
    "reading": "びょうき",
    "romaji": "byouki",
    "meaning": "illness; sickness"
  },
  {
    "id": "n5-0572",
    "jp": "平仮名",
    "reading": "ひらがな",
    "romaji": "hiragana",
    "meaning": "hiragana"
  },
  {
    "id": "n5-0573",
    "jp": "昼",
    "reading": "ひる",
    "romaji": "hiru",
    "meaning": "noon, daytime"
  },
  {
    "id": "n5-0574",
    "jp": "昼御飯",
    "reading": "ひるごはん",
    "romaji": "hirugohan",
    "meaning": "lunch, midday meal"
  },
  {
    "id": "n5-0575",
    "jp": "広い",
    "reading": "ひろい",
    "romaji": "hiroi",
    "meaning": "spacious; wide; broad"
  },
  {
    "id": "n5-0576",
    "jp": "フィルム",
    "reading": "フィルム",
    "romaji": "フィルム",
    "meaning": "film (roll of)"
  },
  {
    "id": "n5-0577",
    "jp": "封筒",
    "reading": "ふうとう",
    "romaji": "fuutou",
    "meaning": "envelope"
  },
  {
    "id": "n5-0578",
    "jp": "プール",
    "reading": "プール",
    "romaji": "プール",
    "meaning": "swimming pool"
  },
  {
    "id": "n5-0579",
    "jp": "フォーク",
    "reading": "フォーク",
    "romaji": "フォーク",
    "meaning": "fork"
  },
  {
    "id": "n5-0580",
    "jp": "吹く",
    "reading": "ふく",
    "romaji": "fuku",
    "meaning": "to blow (wind, etc.)"
  },
  {
    "id": "n5-0581",
    "jp": "服",
    "reading": "ふく",
    "romaji": "fuku",
    "meaning": "clothes"
  },
  {
    "id": "n5-0582",
    "jp": "二つ",
    "reading": "ふたつ",
    "romaji": "futatsu",
    "meaning": "two things"
  },
  {
    "id": "n5-0583",
    "jp": "豚肉",
    "reading": "ぶたにく",
    "romaji": "butaniku",
    "meaning": "pork"
  },
  {
    "id": "n5-0584",
    "jp": "二人",
    "reading": "ふたり",
    "romaji": "futari",
    "meaning": "two people"
  },
  {
    "id": "n5-0585",
    "jp": "二日",
    "reading": "ふつか",
    "romaji": "futsuka",
    "meaning": "two days; second day of the month"
  },
  {
    "id": "n5-0586",
    "jp": "太い",
    "reading": "ふとい",
    "romaji": "futoi",
    "meaning": "fat, thick"
  },
  {
    "id": "n5-0587",
    "jp": "冬",
    "reading": "ふゆ",
    "romaji": "fuyu",
    "meaning": "winter"
  },
  {
    "id": "n5-0588",
    "jp": "降る",
    "reading": "ふる",
    "romaji": "furu",
    "meaning": "to precipitate, to fall (e.g., rain, snow, etc.)"
  },
  {
    "id": "n5-0589",
    "jp": "古い",
    "reading": "ふるい",
    "romaji": "furui",
    "meaning": "old (in reference to objects, not people), aged, ancient"
  },
  {
    "id": "n5-0590",
    "jp": "～分",
    "reading": "～ふん",
    "romaji": "～fun",
    "meaning": "~ minutes"
  },
  {
    "id": "n5-0591",
    "jp": "文章",
    "reading": "ぶんしょう",
    "romaji": "bunshou",
    "meaning": "sentence, text"
  },
  {
    "id": "n5-0592",
    "jp": "ページ",
    "reading": "ページ",
    "romaji": "ページ",
    "meaning": "a page"
  },
  {
    "id": "n5-0593",
    "jp": "下手",
    "reading": "へた",
    "romaji": "heta",
    "meaning": "unskillful, poor"
  },
  {
    "id": "n5-0594",
    "jp": "ベッド",
    "reading": "ベッド",
    "romaji": "ベッド",
    "meaning": "bed"
  },
  {
    "id": "n5-0595",
    "jp": "ペット",
    "reading": "ペット",
    "romaji": "ペット",
    "meaning": "pet"
  },
  {
    "id": "n5-0596",
    "jp": "部屋",
    "reading": "へや",
    "romaji": "heya",
    "meaning": "a room"
  },
  {
    "id": "n5-0597",
    "jp": "辺",
    "reading": "へん",
    "romaji": "hen",
    "meaning": "area, vicinity"
  },
  {
    "id": "n5-0598",
    "jp": "ペン",
    "reading": "ペン",
    "romaji": "ペン",
    "meaning": "pen"
  },
  {
    "id": "n5-0599",
    "jp": "勉強",
    "reading": "べんきょう (する)",
    "romaji": "benkyou (suru)",
    "meaning": "study"
  },
  {
    "id": "n5-0600",
    "jp": "便利",
    "reading": "べんり",
    "romaji": "benri",
    "meaning": "convenient, handy"
  },
  {
    "id": "n5-0601",
    "jp": "帽子",
    "reading": "ぼうし",
    "romaji": "boushi",
    "meaning": "hat; cap"
  },
  {
    "id": "n5-0602",
    "jp": "ボールペン",
    "reading": "ボールペン",
    "romaji": "ボールペン",
    "meaning": "ball-point pen"
  },
  {
    "id": "n5-0603",
    "jp": "外",
    "reading": "ほか",
    "romaji": "hoka",
    "meaning": "other, the rest"
  },
  {
    "id": "n5-0604",
    "jp": "ポケット",
    "reading": "ポケット",
    "romaji": "ポケット",
    "meaning": "pocket"
  },
  {
    "id": "n5-0605",
    "jp": "欲しい",
    "reading": "ほしい",
    "romaji": "hoshii",
    "meaning": "to want, in need of"
  },
  {
    "id": "n5-0606",
    "jp": "ポスト",
    "reading": "ポスト",
    "romaji": "ポスト",
    "meaning": "mailbox; post, position"
  },
  {
    "id": "n5-0607",
    "jp": "細い",
    "reading": "ほそい",
    "romaji": "hosoi",
    "meaning": "thin, slender, fine"
  },
  {
    "id": "n5-0608",
    "jp": "ボタン",
    "reading": "ボタン",
    "romaji": "ボタン",
    "meaning": "button"
  },
  {
    "id": "n5-0609",
    "jp": "ホテル",
    "reading": "ホテル",
    "romaji": "ホテル",
    "meaning": "hotel"
  },
  {
    "id": "n5-0610",
    "jp": "本",
    "reading": "ほん",
    "romaji": "hon",
    "meaning": "book"
  },
  {
    "id": "n5-0611",
    "jp": "～本",
    "reading": "～ほん",
    "romaji": "～hon",
    "meaning": "counter for long cylindrical things"
  },
  {
    "id": "n5-0612",
    "jp": "本棚",
    "reading": "ほんだな",
    "romaji": "hondana",
    "meaning": "bookshelf"
  },
  {
    "id": "n5-0613",
    "jp": "本当",
    "reading": "ほんとう",
    "romaji": "hontou",
    "meaning": "real, true"
  },
  {
    "id": "n5-0614",
    "jp": "～枚",
    "reading": "～まい",
    "romaji": "～mai",
    "meaning": "counter for flat things"
  },
  {
    "id": "n5-0615",
    "jp": "毎朝",
    "reading": "まいあさ",
    "romaji": "maiasa",
    "meaning": "every morning"
  },
  {
    "id": "n5-0616",
    "jp": "毎月",
    "reading": "まいげつ; まいつき",
    "romaji": "maigetsu; maitsuki",
    "meaning": "every month, monthly"
  },
  {
    "id": "n5-0617",
    "jp": "毎週",
    "reading": "まいしゅう",
    "romaji": "maishuu",
    "meaning": "every week"
  },
  {
    "id": "n5-0618",
    "jp": "毎日",
    "reading": "まいにち",
    "romaji": "mainichi",
    "meaning": "every day"
  },
  {
    "id": "n5-0619",
    "jp": "毎年",
    "reading": "まいねん; まいとし",
    "romaji": "mainen; maitoshi",
    "meaning": "every year, yearly, annually"
  },
  {
    "id": "n5-0620",
    "jp": "毎晩",
    "reading": "まいばん",
    "romaji": "maiban",
    "meaning": "every night"
  },
  {
    "id": "n5-0621",
    "jp": "前",
    "reading": "まえ",
    "romaji": "mae",
    "meaning": "before, in front"
  },
  {
    "id": "n5-0622",
    "jp": "～前",
    "reading": "～まえ",
    "romaji": "～mae",
    "meaning": "in front of ~"
  },
  {
    "id": "n5-0623",
    "jp": "曲る",
    "reading": "まがる",
    "romaji": "magaru",
    "meaning": "to turn, to bend"
  },
  {
    "id": "n5-0624",
    "jp": "まずい",
    "reading": "まずい",
    "romaji": "mazui",
    "meaning": "terrible (in reference to food), unappetizing, unpleasant (taste)"
  },
  {
    "id": "n5-0625",
    "jp": "また",
    "reading": "また",
    "romaji": "mata",
    "meaning": "and; furthermore"
  },
  {
    "id": "n5-0626",
    "jp": "まだ",
    "reading": "まだ",
    "romaji": "mada",
    "meaning": "yet, still, besides"
  },
  {
    "id": "n5-0627",
    "jp": "町",
    "reading": "まち",
    "romaji": "machi",
    "meaning": "town; city"
  },
  {
    "id": "n5-0628",
    "jp": "待つ",
    "reading": "まつ",
    "romaji": "matsu",
    "meaning": "to wait"
  },
  {
    "id": "n5-0629",
    "jp": "まっすぐ",
    "reading": "まっすぐ",
    "romaji": "massugu",
    "meaning": "straight (ahead), direct"
  },
  {
    "id": "n5-0630",
    "jp": "マッチ",
    "reading": "マッチ",
    "romaji": "マッチ",
    "meaning": "match"
  },
  {
    "id": "n5-0631",
    "jp": "窓",
    "reading": "まど",
    "romaji": "mado",
    "meaning": "window"
  },
  {
    "id": "n5-0632",
    "jp": "丸い; 円い",
    "reading": "まるい",
    "romaji": "marui",
    "meaning": "round, circular"
  },
  {
    "id": "n5-0633",
    "jp": "万",
    "reading": "まん",
    "romaji": "man",
    "meaning": "ten thousand"
  },
  {
    "id": "n5-0634",
    "jp": "万年筆",
    "reading": "まんねんひつ",
    "romaji": "mannenhitsu",
    "meaning": "fountain pen"
  },
  {
    "id": "n5-0635",
    "jp": "磨く",
    "reading": "みがく",
    "romaji": "migaku",
    "meaning": "to brush (teeth); to polish"
  },
  {
    "id": "n5-0636",
    "jp": "右",
    "reading": "みぎ",
    "romaji": "migi",
    "meaning": "right hand side"
  },
  {
    "id": "n5-0637",
    "jp": "短い",
    "reading": "みじかい",
    "romaji": "mijikai",
    "meaning": "short (length)"
  },
  {
    "id": "n5-0638",
    "jp": "水",
    "reading": "みず",
    "romaji": "mizu",
    "meaning": "water"
  },
  {
    "id": "n5-0639",
    "jp": "店",
    "reading": "みせ",
    "romaji": "mise",
    "meaning": "store, shop"
  },
  {
    "id": "n5-0640",
    "jp": "見せる",
    "reading": "みせる",
    "romaji": "miseru",
    "meaning": "to show, to display"
  },
  {
    "id": "n5-0641",
    "jp": "道",
    "reading": "みち",
    "romaji": "michi",
    "meaning": "road, street; way, directions"
  },
  {
    "id": "n5-0642",
    "jp": "三日",
    "reading": "みっか",
    "romaji": "mikka",
    "meaning": "three days, third day of the month"
  },
  {
    "id": "n5-0643",
    "jp": "三つ",
    "reading": "みっつ",
    "romaji": "mittsu",
    "meaning": "three things"
  },
  {
    "id": "n5-0644",
    "jp": "緑",
    "reading": "みどり",
    "romaji": "midori",
    "meaning": "green"
  },
  {
    "id": "n5-0645",
    "jp": "皆さん",
    "reading": "みなさん",
    "romaji": "minasan",
    "meaning": "all of you, everyone"
  },
  {
    "id": "n5-0646",
    "jp": "南",
    "reading": "みなみ",
    "romaji": "minami",
    "meaning": "South"
  },
  {
    "id": "n5-0647",
    "jp": "耳",
    "reading": "みみ",
    "romaji": "mimi",
    "meaning": "ear"
  },
  {
    "id": "n5-0648",
    "jp": "見る",
    "reading": "みる",
    "romaji": "miru",
    "meaning": "to see, to look"
  },
  {
    "id": "n5-0649",
    "jp": "みんな",
    "reading": "みんな",
    "romaji": "minna",
    "meaning": "all, everyone, everybody"
  },
  {
    "id": "n5-0650",
    "jp": "六日",
    "reading": "むいか",
    "romaji": "muika",
    "meaning": "six days; sixth day of month"
  },
  {
    "id": "n5-0651",
    "jp": "向こう",
    "reading": "むこう",
    "romaji": "mukou",
    "meaning": "beyond, over there"
  },
  {
    "id": "n5-0652",
    "jp": "難しい",
    "reading": "むずかしい",
    "romaji": "muzukashii",
    "meaning": "difficult"
  },
  {
    "id": "n5-0653",
    "jp": "六つ",
    "reading": "むっつ",
    "romaji": "muttsu",
    "meaning": "six things"
  },
  {
    "id": "n5-0654",
    "jp": "村",
    "reading": "むら",
    "romaji": "mura",
    "meaning": "village"
  },
  {
    "id": "n5-0655",
    "jp": "目",
    "reading": "め",
    "romaji": "me",
    "meaning": "eye(s)"
  },
  {
    "id": "n5-0656",
    "jp": "メートル",
    "reading": "メートル",
    "romaji": "メートル",
    "meaning": "meter"
  },
  {
    "id": "n5-0657",
    "jp": "眼鏡",
    "reading": "めがね",
    "romaji": "megane",
    "meaning": "eye glasses"
  },
  {
    "id": "n5-0658",
    "jp": "もう",
    "reading": "もう",
    "romaji": "mou",
    "meaning": "already; again; more"
  },
  {
    "id": "n5-0659",
    "jp": "木曜日",
    "reading": "もくようび",
    "romaji": "mokuyoubi",
    "meaning": "Thursday"
  },
  {
    "id": "n5-0660",
    "jp": "もしもし",
    "reading": "もしもし",
    "romaji": "moshimoshi",
    "meaning": "Hello? (used on the phone)"
  },
  {
    "id": "n5-0661",
    "jp": "持つ",
    "reading": "もつ",
    "romaji": "motsu",
    "meaning": "to hold, to carry; to possess"
  },
  {
    "id": "n5-0662",
    "jp": "もっと",
    "reading": "もっと",
    "romaji": "motto",
    "meaning": "more"
  },
  {
    "id": "n5-0663",
    "jp": "物",
    "reading": "もの",
    "romaji": "mono",
    "meaning": "thing (concrete object)"
  },
  {
    "id": "n5-0664",
    "jp": "門",
    "reading": "もん",
    "romaji": "mon",
    "meaning": "gate"
  },
  {
    "id": "n5-0665",
    "jp": "問題",
    "reading": "もんだい",
    "romaji": "mondai",
    "meaning": "a problem"
  },
  {
    "id": "n5-0666",
    "jp": "～屋",
    "reading": "～や",
    "romaji": "～ya",
    "meaning": "~ shop"
  },
  {
    "id": "n5-0667",
    "jp": "八百屋",
    "reading": "やおや",
    "romaji": "yaoya",
    "meaning": "greengrocer"
  },
  {
    "id": "n5-0668",
    "jp": "野菜",
    "reading": "やさい",
    "romaji": "yasai",
    "meaning": "vegetable"
  },
  {
    "id": "n5-0669",
    "jp": "易しい",
    "reading": "やさしい",
    "romaji": "yasashii",
    "meaning": "easy, plain, simple"
  },
  {
    "id": "n5-0670",
    "jp": "安い",
    "reading": "やすい",
    "romaji": "yasui",
    "meaning": "inexpensive; cheap (things)"
  },
  {
    "id": "n5-0671",
    "jp": "休み",
    "reading": "やすみ",
    "romaji": "yasumi",
    "meaning": "holiday; day off; absence"
  },
  {
    "id": "n5-0672",
    "jp": "休む",
    "reading": "やすむ",
    "romaji": "yasumu",
    "meaning": "to rest, to have a break, to get time off"
  },
  {
    "id": "n5-0673",
    "jp": "八つ",
    "reading": "やっつ",
    "romaji": "yattsu",
    "meaning": "eight things"
  },
  {
    "id": "n5-0674",
    "jp": "山",
    "reading": "やま",
    "romaji": "yama",
    "meaning": "mountain"
  },
  {
    "id": "n5-0675",
    "jp": "やる",
    "reading": "やる",
    "romaji": "yaru",
    "meaning": "to do; to give (to pets, parents, siblings, etc.)"
  },
  {
    "id": "n5-0676",
    "jp": "夕方",
    "reading": "ゆうがた",
    "romaji": "yuugata",
    "meaning": "late afternoon (typically just before dinner time), evening"
  },
  {
    "id": "n5-0677",
    "jp": "夕飯",
    "reading": "ゆうはん",
    "romaji": "yuuhan",
    "meaning": "dinner, supper, evening meal"
  },
  {
    "id": "n5-0678",
    "jp": "郵便局",
    "reading": "ゆうびんきょく",
    "romaji": "yuubinkyoku",
    "meaning": "post office"
  },
  {
    "id": "n5-0679",
    "jp": "昨夜",
    "reading": "ゆうべ",
    "romaji": "yuube",
    "meaning": "last night"
  },
  {
    "id": "n5-0680",
    "jp": "有名",
    "reading": "ゆうめい",
    "romaji": "yuumei",
    "meaning": "famous"
  },
  {
    "id": "n5-0681",
    "jp": "雪",
    "reading": "ゆき",
    "romaji": "yuki",
    "meaning": "snow"
  },
  {
    "id": "n5-0682",
    "jp": "ゆっくりと",
    "reading": "ゆっくりと",
    "romaji": "yukkurito",
    "meaning": "slowly, at ease"
  },
  {
    "id": "n5-0683",
    "jp": "八日",
    "reading": "ようか",
    "romaji": "youka",
    "meaning": "eight days; eighth day of the month"
  },
  {
    "id": "n5-0684",
    "jp": "洋服",
    "reading": "ようふく",
    "romaji": "youfuku",
    "meaning": "Western-style clothes"
  },
  {
    "id": "n5-0685",
    "jp": "よく",
    "reading": "よく",
    "romaji": "yoku",
    "meaning": "frequently, often (much); well, skillfully"
  },
  {
    "id": "n5-0686",
    "jp": "横",
    "reading": "よこ",
    "romaji": "yoko",
    "meaning": "beside; side; width"
  },
  {
    "id": "n5-0687",
    "jp": "四日",
    "reading": "よっか",
    "romaji": "yokka",
    "meaning": "four days; fourth day of the month"
  },
  {
    "id": "n5-0688",
    "jp": "四つ",
    "reading": "よっつ",
    "romaji": "yottsu",
    "meaning": "four things"
  },
  {
    "id": "n5-0689",
    "jp": "呼ぶ",
    "reading": "よぶ",
    "romaji": "yobu",
    "meaning": "to call (one's name); to invite"
  },
  {
    "id": "n5-0690",
    "jp": "読む",
    "reading": "よむ",
    "romaji": "yomu",
    "meaning": "to read"
  },
  {
    "id": "n5-0691",
    "jp": "夜",
    "reading": "よる",
    "romaji": "yoru",
    "meaning": "evening, night"
  },
  {
    "id": "n5-0692",
    "jp": "弱い",
    "reading": "よわい",
    "romaji": "yowai",
    "meaning": "weak"
  },
  {
    "id": "n5-0693",
    "jp": "来月",
    "reading": "らいげつ",
    "romaji": "raigetsu",
    "meaning": "next month"
  },
  {
    "id": "n5-0694",
    "jp": "来週",
    "reading": "らいしゅう",
    "romaji": "raishuu",
    "meaning": "next week"
  },
  {
    "id": "n5-0695",
    "jp": "来年",
    "reading": "らいねん",
    "romaji": "rainen",
    "meaning": "next year"
  },
  {
    "id": "n5-0696",
    "jp": "ラジオ",
    "reading": "ラジオ",
    "romaji": "ラジオ",
    "meaning": "radio"
  },
  {
    "id": "n5-0697",
    "jp": "ラジオカセ",
    "reading": "ラジオカセ",
    "romaji": "ラジオカセ",
    "meaning": "radio cassette player"
  },
  {
    "id": "n5-0698",
    "jp": "りっぱ",
    "reading": "りっぱ",
    "romaji": "rippa",
    "meaning": "splendid, fine"
  },
  {
    "id": "n5-0699",
    "jp": "留学生",
    "reading": "りゅうがくせい",
    "romaji": "ryuugakusei",
    "meaning": "international student"
  },
  {
    "id": "n5-0700",
    "jp": "両親",
    "reading": "りょうしん",
    "romaji": "ryoushin",
    "meaning": "parents (lit., both parents)"
  },
  {
    "id": "n5-0701",
    "jp": "料理",
    "reading": "りょうり",
    "romaji": "ryouri",
    "meaning": "cooking; cuisine"
  },
  {
    "id": "n5-0702",
    "jp": "旅行",
    "reading": "りょこう",
    "romaji": "ryokou",
    "meaning": "travel, trip"
  },
  {
    "id": "n5-0703",
    "jp": "零",
    "reading": "れい",
    "romaji": "rei",
    "meaning": "zero, nought"
  },
  {
    "id": "n5-0704",
    "jp": "冷蔵庫",
    "reading": "れいぞうこ",
    "romaji": "reizouko",
    "meaning": "refrigerator"
  },
  {
    "id": "n5-0705",
    "jp": "レコード",
    "reading": "レコード",
    "romaji": "レコード",
    "meaning": "record"
  },
  {
    "id": "n5-0706",
    "jp": "レストラン",
    "reading": "レストラン",
    "romaji": "レストラン",
    "meaning": "restaurant"
  },
  {
    "id": "n5-0707",
    "jp": "練習",
    "reading": "れんしゅう (する)",
    "romaji": "renshuu (suru)",
    "meaning": "(to) practice"
  },
  {
    "id": "n5-0708",
    "jp": "廊下",
    "reading": "ろうか",
    "romaji": "rouka",
    "meaning": "corridor"
  },
  {
    "id": "n5-0709",
    "jp": "六",
    "reading": "ろく",
    "romaji": "roku",
    "meaning": "six"
  },
  {
    "id": "n5-0710",
    "jp": "ワイシャツ",
    "reading": "ワイシャツ",
    "romaji": "ワイシャツ",
    "meaning": "shirt (lit: white shirt), business shirt"
  },
  {
    "id": "n5-0711",
    "jp": "若い",
    "reading": "わかい",
    "romaji": "wakai",
    "meaning": "young"
  },
  {
    "id": "n5-0712",
    "jp": "分かる",
    "reading": "わかる",
    "romaji": "wakaru",
    "meaning": "to understand"
  },
  {
    "id": "n5-0713",
    "jp": "忘れる",
    "reading": "わすれる",
    "romaji": "wasureru",
    "meaning": "to forget"
  },
  {
    "id": "n5-0714",
    "jp": "私",
    "reading": "わたし",
    "romaji": "watashi",
    "meaning": "I, myself"
  },
  {
    "id": "n5-0715",
    "jp": "私",
    "reading": "わたくし",
    "romaji": "watakushi",
    "meaning": "I (formal), myself, private affairs"
  },
  {
    "id": "n5-0716",
    "jp": "渡す",
    "reading": "わたす",
    "romaji": "watasu",
    "meaning": "to hand (something) over (v.t.); to get across"
  },
  {
    "id": "n5-0717",
    "jp": "渡る",
    "reading": "わたる",
    "romaji": "wataru",
    "meaning": "to cross over, to go across"
  },
  {
    "id": "n5-0718",
    "jp": "悪い",
    "reading": "わるい",
    "romaji": "warui",
    "meaning": "bad, sinful; inferior"
  }
]
